### PR TITLE
Remove lower-case requirement for language/grammar

### LINKED ISSUE #4346: Inconsistent/undocumented lowercase usage for grammars/languages
### Summary

I tried to integrate a [grammar for BitBake](https://github.com/nateglims/tree-sitter-bb) files into helix. This grammar uses `BB` as its name. While a bit odd, I don't think its prohibited to use uppercase letters for the grammar name.

However this proves to be difficult to use with helix, as it will use `to_ascii_lowercase()` for some operations. Furthermore this is not even consistent, so declaring a grammar with `name = "BB"` and building it will produce a `BB.so` but loading fails because it can not find a `bb.so`. (I know that even if that would have worked it still would not find the `tree_sitter_<name>` symbol, as it is also lowercased.)

Note: when changing the tree-sitter grammar to use a lowercase name, and adjusting all my configs accordingly it works fine.

Is this forced lowercase there for a reason? Then I think this should be both documented and at least `hx --grammar build` should be fixed.

In my opinion, helix should just use the case supplied.

### Reproduction Steps

Put the following into `languages.toml`:
```toml
[[language]]
name = "BB"
scope = "source.BB"
file-types = ["bb", "bbclass", "bbappend", "inc"]
roots = []
grammar = "BB"
comment-token = "#"

[[grammar]]
name = "BB"
source = { git = "https://github.com/nateglims/tree-sitter-bb.git", rev = "d8c986da8cd043551e3084280c2f3c1edd6e49c8" }
```

Place the [queries](https://github.com/nateglims/tree-sitter-bb/tree/main/queries) into `runtime/grammars/BB/`.

Fetch and build `hx --grammar fetch && hx --grammar build`

Open a BitBake file and be happy. (Example file to be found [here](https://github.com/openembedded/bitbake/blob/master/classes/base.bbclass)

### Platform

Linux

### Terminal Emulator

alacritty 0.10.1

### Helix Version

helix 22.08.1 (9b7f349f)

### PR DESCRIPTION
**Pull request by kleinweby**
As described in #4346 both language and grammar names are sometimes lower-cased. For grammars this is incompatible with ones using uppercase names. And for languages this can be a bit surprising. (At least I stumbled across helix ignoring my queries because of this).

Note that the syntax part is  not strictly necessary to get grammars as described in the issue to work.

Closes #4346

### CODE REVIEW

**Comment by the-mikedavis** [comment]
One more to remove here: https://github.com/helix-editor/helix/blob/418a622db9d957d09e10ccbc3897d8ac9268dc8e/xtask/src/querycheck.rs#L17

**Comment by kleinweby** [comment]
Ah thanks. I've removed the missing to lowercase.

Two of the tests actually used this lowercase conversion. I've simply changed them. I've also checked `language.toml` that every language/grammar currently used lower-case names, which is the case.

File: xtask/src/querycheck.rs [hunk 1]
```diff
@@ -14,17 +14,16 @@ pub fn query_check() -> Result<(), DynError> {
     ];
 
     for language in lang_config().language {
-        let language_name = language.language_id.to_ascii_lowercase();
         let grammar_name = language.grammar.unwrap_or(language.language_id);
         for query_file in query_files {
             let language = get_language(&grammar_name);
-            let query_text = read_query(&language_name, query_file);
+            let query_text = read_query(&language.language_id, query_file);
```
Comment (the-mikedavis) [inline xtask/src/querycheck.rs:20]: `language` gets shadowed above which is causing the compilation to fail

Comment (kleinweby) [reply xtask/src/querycheck.rs]: Thanks, sorry I missed that :)

**Comment by the-mikedavis** [comment]
I missed this in the review of the PR that added it but there's a real test failure now from the uppercasing on this line: https://github.com/helix-editor/helix/blob/e25af1f7441fd1eccae580ba2e8e0eebc2be74f8/helix-core/src/syntax.rs#L2278 - could you set that to lowercase?

**Comment by kleinweby** [comment]
Sure, I rebased the PR and lowercased the failing test.

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Thanks!
