### PR TITLE
Mark buffers created from stdin as modified

### LINKED ISSUE #3305: Initial scratch buffer is discarded when non-empty and unmodified
### Summary

The initial scratch buffer created when opening `hx` without a filename may be erroneously closed when navigated away from. This is expected behavior when the scratch buffer is empty and unmodified but it can occur when the scratch buffer is non-empty and unmodified by piping in initial text.

https://github.com/helix-editor/helix/discussions/3118

### Reproduction Steps

Fill the initial scratch buffer with files for example

```
find . -name \*.md | hx
```

Then use `gf` to open up one of those buffers. The buffer picker (`Space-b`) then shows

If you leave some modifications in the scratch buffer before using `gf` then the scratch buffer stays open.

(This is not reproducible on macos because piping in is not currently supported https://github.com/helix-editor/helix/blob/69f84e25165d62d0f38bcc80bf9108f9c0802cad/helix-term/src/application.rs#L197)

### Helix log

_No response_

### Platform

Linux (NixOS 21.11)

### Terminal Emulator

Kitty 0.25.2

### Helix Version

22.05-351-g69f84e25

### PR DESCRIPTION
**Pull request by the-mikedavis**
This resolves some confusing behavior where a scratch document created by piping into hx is discarded when navigating away from that document.

We discard any scratch documents that are not modified and the original `Editor::new_file_from_stdin` would create unmodified documents. We refactor this function to create an empty document first and then to apply the text from stdin as a change.

This comes out of the discussion in #3306
Closes #3306 
Closes #3305

### CODE REVIEW

File: helix-view/src/document.rs [hunk 1]
```diff
@@ -493,6 +471,81 @@ pub fn from_reader<R: std::io::Read + ?Sized>(
     Ok((rope, encoding, has_bom))
 }
 
+pub fn read_to_string<R: std::io::Read + ?Sized>(
```
Comment (the-mikedavis) [inline helix-view/src/document.rs:474]: This would also be useful for #3966
