### PR TITLE
Expand tildes in `:read` command

### LINKED ISSUE #12255: Read (:r) command does not properly expand ~ to mean "user's home directory"
### Summary

If you try to read in a file like this:

```
:r ~/some/file
```

This will result in the error:

```
path is not a file: "~/some/file"
```

Even though (a) the file exists, and (b) the path autocompletes successfully.

### Reproduction Steps

(I think the summary covers this)

### Helix log

(nothing is logged in helix.log in reponse to this failure)

### Platform

Linux

### Terminal Emulator

ptyxis

### Installation Method

source

### Helix Version

24.07-328-ge14c346e

### PR DESCRIPTION
**Pull request by Aaalibaba42**
Fixes #12255

### CODE REVIEW

File: helix-term/src/commands/typed.rs [hunk 1]
```diff
@@ -2507,7 +2508,19 @@ fn read(cx: &mut compositor::Context, args: &[Cow<str>], event: PromptEvent) ->
     ensure!(args.len() == 1, "only the file name is expected");
 
     let filename = args.first().unwrap();
-    let path = PathBuf::from(filename.to_string());
+    let path = PathBuf::from(if filename.starts_with('~') {
```
Comment (the-mikedavis) [inline helix-term/src/commands/typed.rs:2511]: There's a helper `helix_stdx::path::expand_tilde` that can be used here instead

Comment (Aaalibaba42) [reply helix-term/src/commands/typed.rs]: There is indeed, fixed o/

**Review by the-mikedavis — APPROVED** [review]
