### PR TITLE
LSP: Key diagnostics off file path instead of URI

### LINKED ISSUE #3267: Looking up diagnostics by URL is ambigous
### Summary

Errors do not show up in the local diagnostic picker (Shift g) while writing rust code with the rust analyzer. But they do show up in the global diagnostic picker (Shift G). Screenshots below as an example.

Note that issues are shown in the top right of the screen if my cursor is on the error. As well as indicating the error presence on the left diagnostic gutter.

Code with obvious issues
image

Empty local diagnostic picker
image

Global picker has all the errors and warnings.
image

I found this issue only with rust and rust analyzer. Other languages work well, with file issues in local and workspace issues in the global diagnostic picker.

Helix :
- built from source ( dfc31e74 )
- cargo version  : cargo 1.62.0 (a748cf5a3 2022-06-08)
- rustc version : rustc 1.62.0 (a8314ef7d 2022-06-27)

Rust Analyzer: 
- built from source ( 897a7ec4b )

I have attached helix logs for today and the last time I used helix while omitting the rest as those would be too much. If you need more comprehensive date ranged logs, I'd be happy to provide them.

I don't have much experience with rust so I am not sure if this is a rust issue, a rust analyzer issue, or a helix issue.

### Reproduction Steps

 

I tried this:

1. `hx`
2. Open a rust file.
3. Add some code with errors (any kind which rust analyzer will notify)
4.  Use local diagnostic picker (Shift g)

I expected this to happen:

The issues in the currently open file to show up there

Instead, this happened:

no errors listed in the local diagnostic picker.

Opening global diagnostic picker (Shift G) shows the errors as expected.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-07-24T00:50:06.819 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-07-24T00:53:07.436 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-07-24T00:53:33.455 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-07-24T00:54:19.304 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-24T00:54:19.305 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-24T00:54:27.368 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-07-24T00:57:34.012 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-07-24T00:57:52.634 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-24T00:58:32.992 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-07-24T00:59:50.604 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-24T00:59:50.605 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-24T01:01:26.954 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2022-07-24T01:05:15.300 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-24T01:05:15.302 helix_lsp::transport [ERROR] err: <- StreamClosed
2022-07-31T01:16:44.031 helix_lsp::transport [ERROR] <- ServerError(-32801): waiting for cargo metadata or cargo check
2022-07-31T01:16:45.551 helix_lsp::transport [ERROR] <- ServerError(-32801): waiting for cargo metadata or cargo check
2022-07-31T01:16:46.149 helix_lsp::transport [ERROR] <- ServerError(-32801): waiting for cargo metadata or cargo check
2022-07-31T01:16:47.801 helix_lsp::transport [ERROR] err <- "[ERROR project_model::workspace] cyclic deps: helix_view(CrateId(66)) -> helix_tui(CrateId(60)), alternative path: helix_tui(CrateId(60)) -> helix_view(CrateId(66))\n"
2022-07-31T01:17:10.680 helix_lsp::transport [ERROR] err <- "[ERROR project_model::workspace] cyclic deps: helix_view(CrateId(66)) -> helix_tui(CrateId(60)), alternative path: helix_tui(CrateId(60)) -> helix_view(CrateId(66))\n"
2022-07-31T01:18:54.795 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 137.2607ms" }
```

</details>

### Platform

Windows

### Terminal Emulator

windows terminal 1.14.1963.0

### Helix Version

22.05-272-gdfc31e74

### PR DESCRIPTION
**Pull request by the-mikedavis**
URIs need to be normalized to be comparable. For example a language server could send a URI for a path containing `+` as `%2B` but we might encode this in something like `Document::url` as just `+`. We can normalize the URI straight into a PathBuf though since this is the only value we compare these diagnostics URIs against. This also covers edge-cases like windows drive letter capitalization.

Closes #3267 
Also see https://github.com/helix-editor/helix/discussions/7321 (thanks for the pointer on this @pascalkuthe!)

### CODE REVIEW

File: helix-term/src/application.rs [hunk 1]
```diff
@@ -867,7 +867,7 @@ impl Application {
                         // Insert the original lsp::Diagnostics here because we may have no open document
                         // for diagnosic message and so we can't calculate the exact position.
                         // When using them later in the diagnostics picker, we calculate them on-demand.
-                        match self.editor.diagnostics.entry(params.uri) {
+                        match self.editor.diagnostics.entry(path) {
```
Comment (pascalkuthe) [inline helix-term/src/application.rs:870]: The path is not normalized here so this could still lead to inconsistencies/problems. We should normalize the path. I can't make a comment to the relative code since it's unchanged. Just call normalize functuon from helix core lm the result of `params.uri.to_file_path()` above. We already do this for other paths we receive from the LSP too.

**Review by pascalkuthe — COMMENTED** [review]
Thanks for working on this! This was

**Review by pascalkuthe — APPROVED** [review]

**Review by pascalkuthe — DISMISSED** [review]

**Review by pascalkuthe — APPROVED** [review]

**Review by pascalkuthe — APPROVED** [review]

**Comment by sbromberger** [comment]
This PR might fix the problem where a directory has a `+` sign: LSP doesn't work in these directories since the URI is normalized/encoded:

```
helix_lsp::transport [INFO] clangd <- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"diagnostics":[{"code":"undeclared_var_use","message":"Use of undeclared identifier 'lkasdjlkasdj'","range":{"end":{"character":14,"line":18},"start":{"character":2,"line":18}},"severity":1,"source":"clang"}],"uri":"file:///home/me/dev/c%2B%2B/advcpp/test.cpp","version":0}}
```

**Comment by kayoscode** [comment]
I'm getting this issue on windows as well. Helix version 23.10

**Review by pascalkuthe — APPROVED** [review]

**Comment by gzmorell** [comment]
Applying this patch in windows brings diagnosis back.  Thanks a lot

**Review by archseer — APPROVED** [review]
