### PR TITLE
Handle disambiguated keycodes

### LINKED ISSUE #4125: Panic on XF86 keycodes
### Summary

I know this is kind of an edge case, but if your system does not do anything with volume control/media playback control keys, they pass through to Helix, causing a panic with the following message:
```
thread 'main' panicked at 'internal error: entered unreachable code: Shouldn't get this key without enabling DISAMBIGUATE_ESCAPE_CODES in crossterm', helix-view/src/keyboard.rs:158:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Reproduction Steps

So this wouldn't be too easy if you don't have access to the guts of your operating system and desktop environment or window manager, but with i3 you can edit your config and comment any line that starts with `bindsym XF86____`, save it and reload your config, then in Helix send to your PC (presumably with a keyboard button) the keycode corresponding to what you just commented out. 

### Helix log

The log didn't contain anything in regards to this error

### Platform

EndeavourOS Arch Linux with i3-gaps

### Terminal Emulator

Kitty

### Helix Version

helix 22.08.1 (5dbca0fc)

### PR DESCRIPTION
**Pull request by the-mikedavis**
Media keys are sent despite `DISAMBIGUATE_ESCAPE_CODES` being unset. Previously we panicked on these. This change translates the disambiguated keys from crossterm so that they do not cause a panic.

Closes #4125.
Supersedes #4576.
Closes #4576.

### CODE REVIEW

File: helix-view/src/keyboard.rs [hunk 1]
```diff
@@ -53,6 +53,164 @@ impl From<crossterm::event::KeyModifiers> for KeyModifiers {
...
+            CMediaKeyCode::LowerVolume => MediaKeyCode::LowerVolume,
+            CMediaKeyCode::RaiseVolume => MediaKeyCode::RaiseVolume,
+            CMediaKeyCode::MuteVolume => MediaKeyCode::MuteVolume,
+        }
+    }
+}
+
+/// Represents a media key (as part of [`KeyCode::Modifier`]).
+#[derive(Debug, PartialOrd, Ord, PartialEq, Eq, Clone, Copy, Hash)]
+pub enum ModifierKeyCode {
```
Comment (the-mikedavis) [inline helix-view/src/keyboard.rs:135]: Modifier keys are controlled with a different flag (see [crossterm's event-read example](https://github.com/crossterm-rs/crossterm/blob/b13e8ef64d57a3b9a642194b6beb069b55d6ef43/examples/event-read.rs#L77-L81)) and we haven't seen reports of terminals sending these without the flag, but I have added them here for completeness.

**Review by dead10ck — APPROVED** [review]
I haven't exhaustively reviewed all the key codes, but this generally looks good to me! Am I understanding that this will also close #3725 as well? i.e. does this generally add the ability to use every key combo with the kitty protocol extension?

**Comment by the-mikedavis** [comment]
Not quite yet - we also need to set the `DISAMBIGUATE_ESCAPE_CODES` flag to fix that. We'll need to figure out how to do that in a way that works with terminals that don't support the flag and do some testing to make sure it doesn't break compatiblity with older terminals

**Comment by dead10ck** [comment]
We could always start simple and make the whole feature opt-in.

**Comment by archseer** [comment]
I want to avoid temporary config flags that we later remove though. The detection is described here: https://sw.kovidgoyal.net/kitty/keyboard-protocol/#detection-of-support-for-this-protocol

**Comment by dead10ck** [comment]
For sure, but would it be temporary? I think it makes sense to keep a flag that can turn off the feature if desired.

**Comment by the-mikedavis** [comment]
It took a look at the detection; I'll make a PR to crossterm. We need to solve it upstream since it needs to use some of crossterm's private functions

**Comment by archseer** [comment]
> For sure, but would it be temporary? I think it makes sense to keep a flag that can turn off the feature if desired.

This transparently improves key parsing to disambiguate things like `tab` vs `ctrl-i`. I can't imagine you'd ever want to turn this off. If you'd like to map something to both keys, then you can just define it twice in your config.
