### PR TITLE
Delay auto-save until exiting insert mode

### LINKED ISSUE #10991: :q (quit) command unexpected behaviour (unsaved buffer) with auto-save by delay
### Summary

When you enable autosave by delay, the :q (quit) command does not work as expected, the editor does not allow you to exit, although the changes have already been made to the disk.

At the same time, changes in .toml (may other also) files or files without extension, it works correctly.

On video the expected behavior is shown first, then the problem described.

https://github.com/helix-editor/helix/assets/173177041/c9317884-5e6f-4ffb-abf2-576964cd1178

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen: write change with auto-save, then just quit

Instead, this happened: occurs warning of unsaved buffer

### Helix log

**It is unexpected behaviour only.**

<details><summary>~/.cache/helix/helix.log</summary>

[helix.log](https://github.com/user-attachments/files/15890688/helix.log)

</details>

### Platform

Linux/Devuan

### Terminal Emulator

Kitty

### Installation Method

source

### Helix Version

helix 24.3

### PR DESCRIPTION
**Pull request by the-mikedavis**
Saving while in insert mode causes issues with the modification indicator and this is very easy to reproduce with the current state of the auto-save hook. We can tweak the hook slightly to await the mode switch out of insert mode to perform the save.

The debounce is preserved: if you save and then immediately exit insert mode the debounce will be respected. If the debounce lapses while you are in insert mode, the save occurs as you switch out of insert mode immediately.

Fixes #10991

### CODE REVIEW

File: helix-term/src/handlers/auto_save.rs [hunk 1]
```diff
@@ -4,36 +4,68 @@ use anyhow::Ok;
...
         &mut self,
-        timeout: Self::Event,
-        _: Option<tokio::time::Instant>,
+        event: Self::Event,
+        existing_debounce: Option<tokio::time::Instant>,
     ) -> Option<Instant> {
-        Some(Instant::now() + Duration::from_millis(timeout))
+        match event {
+            Self::Event::DocumentChanged { debounce } => {
+                self.save_pending = true;
```
Comment (pascalkuthe) [inline helix-term/src/handlers/auto_save.rs:44]: as far as I can see we never reset `save_pending` back to false. I guess that would need to happen when leaving insertmodel? This also sets this to true in normal mode would also cause excess/incorrect saves. 

I actually had something else in mind:

* make `save_pending` an `Arc<AtomicBool>`, only inside finish_deboucne/dispatch_blocking if the mode is insert mode store true in there (needs to be an Arc/AtomicBool so we can move it inside the callback)
* Another clone of the arc is moved into the mode switch callback. When going from insert to normal mode that callback will check the value of the shared bool. If it's true it will instantly save (not send an even, save right in the mode switch handler) and then store false in the callback

I think doing it as an event that triggers a new save could work too. But I think the Arc/AtomicBool that only gets set to true if the calblack actually failed (so only we we are actually in normal mode when trying to save) is definitly necessary

Comment (the-mikedavis) [reply helix-term/src/handlers/auto_save.rs:44]: Ah yep I forgot to reset it. But I like the sound of the atomic bool more!

Comment (the-mikedavis) [reply helix-term/src/handlers/auto_save.rs]: I switched to the atomic bool so we can set it in the dispatch callback but I didn't also do the part about passing the bool to the mode switch hook. I'd like to keep the behavior where we delay even when switching modes rather than saving immediately on mode switch.

Maybe auto-save on mode switch should be a separate auto-save option though?

Comment (pascalkuthe) [reply helix-term/src/handlers/auto_save.rs]: hmm so I wasn't necessarily thinking of always saving immediately on mode switch but rather:

* the save should happen in insert-mode, the timeout already expired we just can't save right now due to internal limitations so we set a flag that an autosave is "pending"
* as soon as we exiting insertmode we execute this "pending" write right away. We execute it right aways since it really should have executed earlier in insertmode, we just couldn't execute it due to internal limitations so we execute it first thing we get

(the pending flag would be the `Arc<AtomicBool>`)

this is kind of orthogonal to saving on mode switch/exiting insertmode in general. The main difference is that it's a bit more robust by not passing trough the timeout mechanism. 

On the other hand I am not sure if savin in the mode switch hook is even possible. I think we only create the history entry after the mode switch hook executes so going trough the event handler is probably necessary/the right thing to do.

File: helix-term/src/handlers/auto_save.rs [hunk 2]
```diff
@@ -1,39 +1,75 @@
...
-        AutoSaveHandler
+        AutoSaveHandler {
+            save_pending: Default::default(),
+        }
     }
 }
 
 impl helix_event::AsyncHook for AutoSaveHandler {
-    type Event = u64;
+    type Event = Option<u64>;
```
Comment (pascalkuthe) [inline helix-term/src/handlers/auto_save.rs:36]: I think you had an enum here previously instead of just an option which I found slightly nicer.

But that's just a small visual thing. I will approve and you can decide wether to add the enum back.

**Review by pascalkuthe — APPROVED** [review]

File: helix-term/src/handlers/auto_save.rs (hunk 1 above)
Comment (the-mikedavis) [reply helix-term/src/handlers/auto_save.rs]: Oh I see now, I misunderstood. I was also curious about the ordering and I believe you're correct that we need to go through the event handler so that we save to history before attempting to write.

**Review by pascalkuthe — APPROVED** [review]
