### PR TITLE
Do not crash when run goto command without line number

### LINKED ISSUE #1159: :goto should not crash if it doesn't input the line number?
I'm not sure is it a bug. The `:goto` command will be panic if I just typing `:goto` and enter. The stacktrace is:

```
thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', helix-term/src/commands.rs:2489:20
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by wingyplus**
Report an error when running goto command without entering a
line number.

Fixes #1159

### CODE REVIEW

File: helix-term/src/commands.rs [hunk 1]
```diff
@@ -2485,6 +2485,10 @@ mod cmd {
         args: &[&str],
         _event: PromptEvent,
     ) -> anyhow::Result<()> {
+        if args.len() == 0 {
+            return Ok(());
```
Comment (Omnikar) [inline helix-term/src/commands.rs:2489]: We should return an error here, rather than failing silently.
```suggestion
            bail!("Line number required");
```

Comment (wingyplus) [reply helix-term/src/commands.rs:2489]: Thanks, that would be better than silencing the false path. :)

Comment (wingyplus) [reply helix-term/src/commands.rs]: @Omnikar Fixed. :)

File: helix-term/src/commands.rs [hunk 2]
```diff
@@ -2485,6 +2485,10 @@ mod cmd {
         args: &[&str],
         _event: PromptEvent,
     ) -> anyhow::Result<()> {
+        if args.len() == 0 {
```
Comment (wingyplus) [inline helix-term/src/commands.rs:2488]:
```suggestion
        if args.is_empty() {
```

**Review by s1ck — APPROVED** [review]
Since I introduced the feature recently (it was merged today) I felt like giving a review :)

Thanks @wingyplus for catching it. I'm not sure how this could be caught by testing :thinking: 
Anyways, the fix is solid and solves the problem :+1:
