### PR TITLE
Fix bugs in popup

### LINKED ISSUE #10569: Tracking issue for popup
- [ ] panic when resizing (pr #10507)

- [ ] hidden popup items with borders enabled (issue #10553) (pr #10566)

- [ ] popup too small to fit below (pr #10566)

popup_below_before_border

- [ ] scroll tracks in wrong place after pushing key down multiple times, when the space is small and the menu opens above
menu_scroll_track

- [ ] panic after pressing the down key on the last visible item, if the menu is opened below and has more items than what is visible
seven_items

### PR DESCRIPTION
**Pull request by pascalkuthe**
fixes #10569

this fixes regression introduced by #10257 both regarding general crashes and bugs when popup borders are used (#10566/https://github.com/helix-editor/helix/issues/10553). While working on this I noticed there were actually existing bugs where the border size wasn't quite taken into account while scrolling which I also fixed. Since borders now need to be accounted for in the popup I made the border config and entirely internal config so its moore self contained.

Also incorporated the fixes from #10507 with some slight adjustments.

Marked for the next release since this fixes newly introduced crashes that are fairly easy to trigger

### CODE REVIEW

File: helix-term/src/ui/popup.rs [hunk 1]
```diff
@@ -296,32 +318,30 @@ impl<T: Component> Component for Popup<T> {
...
-        let render_borders = cx.editor.popup_border();
-
-        let inner = if self
-            .contents
-            .type_name()
-            .starts_with("helix_term::ui::menu::Menu")
-        {
-            area
+        let background = if is_menu {
+            // TODO: consisently style menu
```
Comment (the-mikedavis) [inline helix-term/src/ui/popup.rs:322]:
```suggestion
            // TODO: consistently style menu
```

**Review by the-mikedavis — COMMENTED** [review]
I found a typo but otherwise this looks good. I've been using it locally since you posted it

**Review by the-mikedavis — DISMISSED** [review]

**Comment by pascalkuthe** [comment]
(I will rebase later to absorb that commit sp we don't have to Squash merge)

File: helix-term/src/ui/popup.rs [hunk 2]
```diff
@@ -163,7 +165,40 @@ impl<T: Component> Popup<T> {
...
+        }
+
+        // compute required child size and reclamp
+        let (mut width, child_height) = self
+            .contents
+            .required_size((max_width, max_height))
+            .expect("Component needs required_size implemented in order to be embedded in a popup");
+
+        width = width.min(MAX_WIDTH);
+        let height = if render_borders {
```
Comment (ath3) [inline helix-term/src/ui/popup.rs:188]:
```suggestion
        let height = if render_borders && is_menu {
```

**Review by ath3 — CHANGES_REQUESTED** [review]

File: helix-term/src/ui/popup.rs [hunk 3]
```diff
@@ -118,38 +120,38 @@ impl<T: Component> Popup<T> {
...
-        if viewport.width <= rel_x + width {
-            rel_x = rel_x.saturating_sub((rel_x + width).saturating_sub(viewport.width));
-        }
 
+        // if there's a orientation preference, use that
+        // if we're on the top part of the screen, do below
+        // if we're on the bottom part, do above
         let can_put_below = viewport.height > rel_y + MIN_HEIGHT;
         let can_put_above = rel_y.checked_sub(MIN_HEIGHT).is_some();
         let final_pos = match self.position_bias {
```
Comment (ath3) [inline helix-term/src/ui/popup.rs:157]:
```suggestion
        let mut final_pos = match self.position_bias {
```

File: helix-term/src/ui/popup.rs [hunk 4]
```diff
@@ -163,7 +165,40 @@ impl<T: Component> Popup<T> {
...
+            max_width -= 2;
+            max_height -= 2;
+        }
+
+        // compute required child size and reclamp
+        let (mut width, child_height) = self
+            .contents
+            .required_size((max_width, max_height))
+            .expect("Component needs required_size implemented in order to be embedded in a popup");
+
```
Comment (ath3) [inline helix-term/src/ui/popup.rs:186]:
```suggestion

        if max_height < child_height && final_pos == Open::Below && rel_y > max_height {
            final_pos = Open::Above;
        }
        

```
For documentation popups, i would like to see as much information as possible, so if it doesnt fit below, and we have more space above, then display it above.
Does not affect menus.

**Review by ath3 — CHANGES_REQUESTED** [review]

File: helix-term/src/ui/popup.rs (hunk 4 above)
Comment (pascalkuthe) [reply helix-term/src/ui/popup.rs:186]: That was part of the previous PR that changed the popup positioning. I really don't want to start adding edgecases like that. The whole special case for menu thing is extremely temporary and something I want to get rid of and instead of lean on more

File: helix-term/src/ui/popup.rs [hunk 5]
```diff
@@ -296,32 +318,30 @@ impl<T: Component> Component for Popup<T> {
...
         } else {
-            area.inner(&self.margin)
+            cx.editor.theme.get("ui.popup")
         };
+        surface.clear_with(area, background);
 
-        let border = usize::from(render_borders);
+        let mut inner = area;
         if render_borders {
+            inner = area.inner(&Margin::all(1));
```
[the remark this answers is not in the document]
Comment (pascalkuthe) [reply helix-term/src/ui/popup.rs:334]: Yeah same here. I k kw the Paddington isn't ideal with borders but for docs and similar stuff I actually think the Paddington is less bad considering that they have a bunch of Paddington already.

I just don't want to add menu based special cases. In my followup PR I will remove the extra üadding from all the popups but I want to keep it simple here

[the remark this answers is not in the document]
Comment (ath3) [reply helix-term/src/ui/popup.rs:334]: The problem is not just visual (having extra padding), but also that we cant scroll to the end of a popup if we do this for every popup

[the remark this answers is not in the document]
Comment (ath3) [reply helix-term/src/ui/popup.rs:334]: But if its not a big issue then i dont mind having it fixed in later PR, i will run helix with my changes until then

[the remark this answers is not in the document]
Comment (pascalkuthe) [reply helix-term/src/ui/popup.rs:326]: the scrolling was actually an unrelated bug where `area` instead of `inner` was used for computing scroll. I pushed a fix for that plus some fixes to the scrollbar rendering. For anything but menu the scrollbar now looks the way you want. The non-menu popup have a bit of extra padding with border but I think that's hardly noticeable. The main regression is the visual one affecting menu. Like I said that will be fixed in a larger followup pr

**Review by dead10ck — APPROVED** [review]
Nice, not only did you fix it, but you also refactored it and eliminated a bunch of repetition too. Thanks and nice work!

File: helix-term/src/ui/lsp.rs [hunk 6]
```diff
@@ -155,10 +155,7 @@ impl Component for SignatureHelp {
 
         let sig = &self.signatures[self.active_signature];
 
-        if PADDING >= viewport.1 || PADDING >= viewport.0 {
-            return None;
-        }
```
Comment (dead10ck) [inline helix-term/src/ui/lsp.rs:160]: Was this the bug? Returning `None` instead of a default size?

Comment (pascalkuthe) [reply helix-term/src/ui/lsp.rs:160]: Yeah this was an existing bug that caused crashes. required_size is only meant to always return None (for components that can't be embedded in a popup) or always meant to return Some. The API is a bit confusing and was very inconsistently used so this seems to have slipped trough at some point.

**Review by the-mikedavis — APPROVED** [review]
