### PR TITLE
Read symlink when writing files

### LINKED ISSUE #10326: Cannot recognize symbolic links on Windows
### Summary

File pickers and `:open` cannot recognize symbolic links. `:write` simply overwites them.

### Reproduction Steps

I tried this:

1. Create symbolic linked files:
    ```powershell
    New-Item a.txt
    New-Item -Type SymbolicLink -Target b.txt -Path .\a.txt
    ```
    This should create an empty `a.txt` and a symbolic link `b.txt` under the current working directory.

2. `hx`
3. `:open b.txt`
4. Type something, and then `:write`

I expected this to happen:

As `b.txt` is a symbolic link to `a.txt`, modifications should apply to both files.

Instead, this happened:

The original symbolic link is overwritten, and `b.txt` is now a normal file. `a.txt` remains unchanged. BTW, the file picker won't recognize `b.txt` at the beginning.

### Helix log

Nothing interesting in the logs.

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Installation Method

source

### Helix Version

24.03-121-g35d0ae7c

### PR DESCRIPTION
**Pull request by kirawi**
Resolves #10326

### CODE REVIEW

File: helix-view/src/document.rs [hunk 1]
```diff
@@ -900,8 +900,9 @@ impl Document {
                     "Path is read only"
                 ));
             }
+            let write_path = std::fs::read_link(&path).unwrap_or_else(|_| path.clone());
```
Comment (pascalkuthe) [inline helix-view/src/document.rs:903]:
```suggestion
            let write_path = tokio::fs::read_link(&path).await.unwrap_or_else(|_| path.clone());
```
use the tokio function insteadt

**Review by pascalkuthe — COMMENTED** [review]
could you try adding some intuegration tests for this so we catch if this ever regresses again? 


Basically create some symlinks and then make sure that writing trough them modifier the original file as expected.

you can take a look at the git symlik tests to see an example ow how to set up tests like that

**Review by pascalkuthe — APPROVED** [review]
Thanks for working on this! Tests are looking great too, gives me piece of mind to have those

**Review by the-mikedavis — APPROVED** [review]
