### PR TITLE
Override nested arrays when merging TOML

### LINKED ISSUE #1000: Incorrectly merging built-in and user config `languages.toml` files for typescript lsp
### Reproduction steps

You need to have [`deno`](https://deno.land/#installation) installed to be able to reproduce and consult wiki for helix config/log directories.

1. Create an empty `languages.toml` in the Helix config directory.
2. Copy in the text from [`helix/languages.toml`](https://github.com/helix-editor/helix/blob/master/languages.toml)
3. Navigate to the `language` entry that has a name of `typescript`
4. Change the `language-server` value to be of `{ command = "deno", args = ["lsp"] }` and save
5. Create a dummy file with a `ts` file extension
6. Insert the following code:

```ts
console.log("Hello, world!");
```

7. Close helix
8. Open the file in helix again with the `-v` flag
9. Open the helix log file and see the errors listed below.

### Environment

- Platform: Windows
- Helix version: 0.5

<details><summary><code>C:\Users\carte\AppData\Local\helix\helix.log</code></summary>

```
2021-11-06T21:20:10.786 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"snippetSupport":false},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]}},"window":{"workDoneProgress":true}},"processId":20380,"rootUri":null},"id":0}
2021-11-06T21:20:10.870 helix_lsp::transport [ERROR] err <- "\u{1b}[0m\u{1b}[1m\u{1b}[31merror\u{1b}[0m: Found argument '--stdio' which wasn't expected, or isn't valid in this context\n"
2021-11-06T21:20:10.870 helix_lsp::transport [ERROR] err <- "\n"
2021-11-06T21:20:10.870 helix_lsp::transport [ERROR] err <- "USAGE:\n"
2021-11-06T21:20:10.870 helix_lsp::transport [ERROR] err <- "    deno [OPTIONS] [SUBCOMMAND]\n"
2021-11-06T21:20:10.870 helix_lsp::transport [ERROR] err <- "\n"
2021-11-06T21:20:10.870 helix_lsp::transport [ERROR] err <- "For more information try --help\n"
2021-11-06T21:20:10.870 helix_lsp::transport [ERROR] err <- "\n"
2021-11-06T21:20:10.876 helix_lsp::transport [ERROR] err: <- StreamClosed
2021-11-06T21:20:10.876 helix_lsp::transport [ERROR] err: <- StreamClosed
```

</details>

### PR DESCRIPTION
**Pull request by the-mikedavis**
We merge the elements of arrays for the top-level array. For
`languages.toml`, this is the array of languages. For any nested
arrays, we simply take the `right` array as-is instead of using
the union of `left` and `right`.

closes #1000

### CODE REVIEW

**Comment by the-mikedavis** [comment]
I'm pretty sure this doesn't affect the merging behavior for `config.toml` but maybe we should use a separate function for the `languages.toml` just to be sure?

**Comment by sudormrfbin** [comment]
> I'm pretty sure this doesn't affect the merging behavior for `config.toml` but maybe we should use a separate function for the `languages.toml` just to be sure?

`editor.shell` for example is an array which defaults to `["sh", "-c"]`. Merging this with the user config value would be the wrong thing here, so I think merging should only be done for languages.toml.

File: helix-loader/src/config.rs [hunk 1]
```diff
@@ -19,7 +19,7 @@ pub fn user_lang_config() -> Result<toml::Value, toml::de::Error> {
         .into_iter()
         .chain([default_lang_config()].into_iter())
         .fold(toml::Value::Table(toml::value::Table::default()), |a, b| {
-            crate::merge_toml_values(b, a)
+            crate::merge_toml_values(b, a, false)
```
Comment (the-mikedavis) [inline helix-loader/src/config.rs:22]: Before #2129 we weren't merging `config.toml` anywhere. Now that #2129 has been merged we can disable the array merging by passing in that flag as `false`.

Comment (kirawi) [reply helix-loader/src/config.rs:22]: I think you linked the wrong PR.

Comment (the-mikedavis) [reply helix-loader/src/config.rs:22]: Whoops! 🤦 

I meant https://github.com/helix-editor/helix/pull/1249

**Review by archseer — APPROVED** [review]
