### PR TITLE
Use range positions to determine insert_newline motion

### LINKED ISSUE #9443: Odd behaviour with `append_mode` `collapse_selection`
### Summary

I use helix, and I map <kbd> a </kbd> to `append_mode` `collapse_selection`. There is an odd bug where the selection comes up again after pressing enter even though the last command collapsed the selection.

### Reproduction Steps

```toml
# ~/.config/helix/config.toml
keys.normal.a = ["append_mode", "collapse_selection"]
```

image

Write some text and then add a left parenthesis to generate a pair
image

Then press <kbd> esc </kbd> then <kbd> a </kbd> (which is mapped as above)
image

Now press <kbd> enter </kbd>
image

I expected this to happen:
image

Instead, this happened:
image

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Installation Method

Scoop

### Helix Version

helix 23.10 (f6021dd0)

### PR DESCRIPTION
**Pull request by wmstack**
Fixes #9443

Uses the relative postion of the anchor and the head of a selection to determine whether to shift the selection or to extend it.

### CODE REVIEW

File: helix-term/src/commands.rs [hunk 1]
```diff
@@ -3650,8 +3650,7 @@ pub mod insert {
 
                 (pos, pos, local_offs)
             };
-
-            let new_range = if doc.restore_cursor {
+            let new_range = if range.head > range.anchor {
```
Comment (the-mikedavis) [inline helix-term/src/commands.rs:3653]: This will also extend if you enter insert mode via `o` (`open_below`), `O` (`open_above`), or mouse click when in insert mode and then hit enter. Instead I believe we want to check `range.cursor(text) > range.anchor` to avoid cases where the range is a point (`Range::point`)

Comment (wmstack) [reply helix-term/src/commands.rs]: Done. However, I am not too familiar with `range.cursor(text)`

**Review by the-mikedavis — DISMISSED** [review]
I'm pretty sure that this is the correct condition. I will test this out locally for a while to see if I can find any cases where we extend unexpectedly

**Comment by pascalkuthe** [comment]
I agree this is correct and inline with how other commands work. I would actually go further: There is only one other place where we use `restore_cursor` (actually restoring the cursor) I think there we should check `range.head > range.anchor && self. restore.cursor` for each selection and only reduce those selections by one where that holds.

**Comment by the-mikedavis** [comment]
:+1: That would fix the other behavior mentioned in #9443

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Looks like this needs a run of `cargo fmt` to pass the lint CI
