### PR TITLE
Merge formatting options and `config.format` in range format request

### LINKED ISSUE #13710: Formatting options ignored on range format
### Summary

Extra formatting options get ignored on range formatting unless the document formatting is performed beforehand.

### Reproduction Steps

I tried this:

```toml
# languages.toml
[language-server.typescript-language-server]
config = { format = { "semicolons" = "insert" } }
```

```js
// main.js
function add( a, b) {
return a + b
}
```

1. `hx main.js`
2. Select lines
3. Press =

I expected this to happen:
Formatted and inserted semicolons

Instead, this happened:
Did not insert semicolons
Range formatting will start inserting semicolons only after running `:format` command after a startup.

[Demo](https://asciinema.org/a/NDa2ZkvJsKikNBMfhBjElZdjk)

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2025-06-08T02:08:26.883 helix_lsp::client [INFO] Using custom LSP config: {"format":{"semicolons":"insert"}}
2025-06-08T02:08:26.883 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"positionEncodings":["utf-8","utf-32","utf-16"]},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}},"dataSupport":true,"disabledSupport":true,"isPreferredSupport":true,"resolveSupport":{"properties":["edit","command"]}},"completion":{"completionItem":{"deprecatedSupport":true,"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":true,"tagSupport":{"valueSet":[1]}},"completionItemKind":{}},"formatting":{"dynamicRegistration":false},"hover":{"contentFormat":["markdown"]},"inlayHint":{"dynamicRegistration":false},"publishDiagnostics":{"tagSupport":{"valueSet":[1,2]},"versionSupport":true},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":true},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"didChangeWatchedFiles":{"dynamicRegistration":true,"relativePatternSupport":false},"executeCommand":{"dynamicRegistration":false},"fileOperations":{"didRename":true,"willRename":true},"inlayHint":{"refreshSupport":false},"symbol":{"dynamicRegistration":false},"workspaceEdit":{"documentChanges":true,"failureHandling":"abort","normalizesLineEndings":false,"resourceOperations":["create","rename","delete"]},"workspaceFolders":true}},"clientInfo":{"name":"helix","version":"25.01.1 (f4b488e3)"},"initializationOptions":{"format":{"semicolons":"insert"}},"processId":3828,"rootPath":"/home/meiram/Dev/javascript/playground/helix-format-selection","rootUri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection","workspaceFolders":[{"name":"helix-format-selection","uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection"}]},"id":0}
2025-06-08T02:08:27.106 helix_lsp::transport [INFO] typescript-language-server <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Using Typescript version (bundled) 5.7.2 from path \"/usr/local/lib/node_modules/typescript/lib/tsserver.js\""}}
2025-06-08T02:08:27.107 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "Using Typescript version (bundled) 5.7.2 from path \"/usr/local/lib/node_modules/typescript/lib/tsserver.js\"" }
2025-06-08T02:08:27.107 helix_lsp::transport [INFO] typescript-language-server <- {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"completionProvider":{"triggerCharacters":[".","\"","'","/","@","<"],"resolveProvider":true},"codeActionProvider":{"codeActionKinds":["source.fixAll.ts","source.removeUnused.ts","source.addMissingImports.ts","source.organizeImports.ts","source.removeUnusedImports.ts","source.sortImports.ts","quickfix","refactor"]},"codeLensProvider":{"resolveProvider":true},"definitionProvider":true,"documentFormattingProvider":true,"documentRangeFormattingProvider":true,"documentHighlightProvider":true,"documentSymbolProvider":true,"executeCommandProvider":{"commands":["_typescript.applyWorkspaceEdit","_typescript.applyCodeAction","_typescript.applyRefactoring","_typescript.configurePlugin","_typescript.organizeImports","_typescript.applyRenameFile","_typescript.goToSourceDefinition"]},"hoverProvider":true,"inlayHintProvider":true,"linkedEditingRangeProvider":false,"renameProvider":{"prepareProvider":true},"referencesProvider":true,"selectionRangeProvider":true,"signatureHelpProvider":{"triggerCharacters":["(",",","<"],"retriggerCharacters":[")"]},"workspaceSymbolProvider":true,"implementationProvider":true,"typeDefinitionProvider":true,"foldingRangeProvider":true,"semanticTokensProvider":{"documentSelector":null,"legend":{"tokenTypes":["class","enum","interface","namespace","typeParameter","type","parameter","variable","enumMember","property","function","member"],"tokenModifiers":["declaration","static","async","readonly","defaultLibrary","local"]},"full":true,"range":true},"workspace":{"fileOperations":{"willRename":{"filters":[{"scheme":"file","pattern":{"glob":"**/*.{ts,js,jsx,tsx,mjs,mts,cjs,cts}","matches":"file"}},{"scheme":"file","pattern":{"glob":"**","matches":"folder"}}]}}}}}}
2025-06-08T02:08:27.107 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"initialized","params":{}}
2025-06-08T02:08:27.107 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{"format":{"semicolons":"insert"}}}}
2025-06-08T02:08:27.107 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"javascript","text":"function add(a, b) {\nreturn a + b\n}\n","uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js","version":0}}}
2025-06-08T02:08:27.109 helix_lsp::transport [INFO] typescript-language-server <- {"jsonrpc":"2.0","method":"$/typescriptVersion","params":{"version":"5.7.2","source":"bundled"}}
2025-06-08T02:08:27.109 helix_term::application [INFO] Ignoring Unhandled notification from Language Server
2025-06-08T02:08:28.562 helix_lsp::transport [INFO] typescript-language-server <- {"jsonrpc":"2.0","method":"textDocument/publishDiagnostics","params":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js","diagnostics":[]}}
2025-06-08T02:08:29.214 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/rangeFormatting","params":{"options":{"insertSpaces":true,"tabSize":2},"range":{"end":{"character":0,"line":3},"start":{"character":0,"line":0}},"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js"}},"id":1}
2025-06-08T02:08:29.254 helix_lsp::transport [INFO] typescript-language-server <- {"jsonrpc":"2.0","id":1,"result":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"  "}]}
2025-06-08T02:08:29.254 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":0,"line":1},"start":{"character":0,"line":1}},"text":"  "}],"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js","version":1}}}
2025-06-08T02:08:31.143 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js"}}}
2025-06-08T02:08:33.245 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":2,"line":1},"start":{"character":0,"line":1}},"text":""}],"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js","version":2}}}
2025-06-08T02:08:34.783 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js"}}}
2025-06-08T02:08:36.193 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/formatting","params":{"options":{"insertSpaces":true,"semicolons":"insert","tabSize":2},"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js"}},"id":2}
2025-06-08T02:08:36.220 helix_lsp::transport [INFO] typescript-language-server <- {"jsonrpc":"2.0","id":2,"result":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"  "},{"range":{"start":{"line":1,"character":12},"end":{"line":1,"character":12}},"newText":";"}]}
2025-06-08T02:08:36.221 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":0,"line":1},"start":{"character":0,"line":1}},"text":"  "},{"range":{"end":{"character":14,"line":1},"start":{"character":14,"line":1}},"text":";"}],"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js","version":3}}}
2025-06-08T02:08:38.163 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":2,"line":1},"start":{"character":0,"line":1}},"text":""},{"range":{"end":{"character":13,"line":1},"start":{"character":12,"line":1}},"text":""}],"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js","version":4}}}
2025-06-08T02:08:38.674 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js"}}}
2025-06-08T02:08:39.989 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/rangeFormatting","params":{"options":{"insertSpaces":true,"tabSize":2},"range":{"end":{"character":0,"line":3},"start":{"character":0,"line":0}},"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js"}},"id":3}
2025-06-08T02:08:40.011 helix_lsp::transport [INFO] typescript-language-server <- {"jsonrpc":"2.0","id":3,"result":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"  "},{"range":{"start":{"line":1,"character":12},"end":{"line":1,"character":12}},"newText":";"}]}
2025-06-08T02:08:40.012 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didChange","params":{"contentChanges":[{"range":{"end":{"character":0,"line":1},"start":{"character":0,"line":1}},"text":"  "},{"range":{"end":{"character":14,"line":1},"start":{"character":14,"line":1}},"text":";"}],"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js","version":5}}}
2025-06-08T02:08:40.703 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"textDocument/didSave","params":{"textDocument":{"uri":"file:///home/meiram/Dev/javascript/playground/helix-format-selection/main.js"}}}
2025-06-08T02:08:41.335 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"shutdown","id":4}
2025-06-08T02:08:41.336 helix_lsp::transport [INFO] typescript-language-server <- {"jsonrpc":"2.0","id":4,"result":null}
2025-06-08T02:08:41.336 helix_lsp::transport [INFO] typescript-language-server -> {"jsonrpc":"2.0","method":"exit"}
```

</details>

### Platform

Linux

### Terminal Emulator

Alacritty

### Installation Method

source

### Helix Version

helix 25.01.1 (f4b488e3)

### PR DESCRIPTION
**Pull request by yohaneYuri**
Fix #13710

### CODE REVIEW

File: helix-lsp/src/client.rs [hunk 1]
```diff
@@ -1210,6 +1210,23 @@ impl Client {
             _ => return None,
         };
 
+        // Inject formatting config like above
```
Comment (DerSaidin) [inline helix-lsp/src/client.rs]: This code is the same as above. I suggest extracting the common code into a function.

Comment (yohaneYuri) [reply helix-lsp/src/client.rs]: I have solved it, please continue to review the code.
