### PR TITLE
don't manually grapheme align ts highlights

### LINKED ISSUE #6645: Helix crashes after inputing emojies.
### Summary

The editor crashes after adding emojies, I don't have much information so ill add a video and the full backtrace.

[Screencast from 2023-04-07 16-34-05.webm](https://user-images.githubusercontent.com/73954836/230636775-027e1f3a-a8ad-4188-b545-550b4e31affa.webm)

<details><summary>Rust Backtrace</summary>

```

thread 'main' panicked at 'byte index 46 is not a char boundary; it is inside '😆' (bytes 45..49) of `#include <stdio.h>

int main() {
    printf("😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆😆`[...]', /builddir/.cargo/registry/src/github.com-1ecc6299db9ec823/unicode-segmentation-1.10.1/src/grapheme.rs:553:22
stack backtrace:
   0:     0x55c0267dd42e - <unknown>
   1:     0x55c025e4aaee - <unknown>
   2:     0x55c0267d7605 - <unknown>
   3:     0x55c0267dd205 - <unknown>
   4:     0x55c0267df00f - <unknown>
   5:     0x55c0267ded84 - <unknown>
   6:     0x55c0267df6b1 - <unknown>
   7:     0x55c0267df446 - <unknown>
   8:     0x55c0267dd95c - <unknown>
   9:     0x55c0267df182 - <unknown>
  10:     0x55c025dadeb3 - <unknown>
  11:     0x55c025e4eff9 - <unknown>
  12:     0x55c025dae517 - <unknown>
  13:     0x55c025f8deb6 - <unknown>
  14:     0x55c025f96586 - <unknown>
  15:     0x55c0262e8586 - <unknown>
  16:     0x55c02640adb3 - <unknown>
  17:     0x55c0263308c3 - <unknown>
  18:     0x55c026331344 - <unknown>
  19:     0x55c026334113 - <unknown>
  20:     0x55c02633e951 - <unknown>
  21:     0x55c02662c9b3 - <unknown>
  22:     0x55c02664402d - <unknown>
  23:     0x55c026640578 - <unknown>
  24:     0x55c02665b30d - <unknown>
  25:     0x55c02666f0fc - <unknown>
  26:     0x55c026699bbf - <unknown>
  27:     0x55c026647d03 - <unknown>
  28:     0x55c026664d6d - <unknown>
  29:     0x55c0267d2028 - <unknown>
  30:     0x55c02669dd25 - <unknown>
  31:     0x7f6a38205510 - __libc_start_call_main
  32:     0x7f6a382055c9 - __libc_start_main@GLIBC_2.2.5
  33:     0x55c025df3305 - <unknown>
  34:                0x0 - <unknown>

```
</details>

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-04-07T16:40:58.821 helix_vcs [ERROR] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepositoryWithinFs {
            path: "/home/karim/Documents/Projects/code/c",
            limit: "/",
        },
    ),
}
2023-04-07T16:40:58.821 helix_vcs [ERROR] failed to open diff base for /home/karim/Documents/Projects/code/c/emoji.c
2023-04-07T16:40:58.822 helix_vcs [ERROR] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepositoryWithinFs {
            path: "/home/karim/Documents/Projects/code/c",
            limit: "/",
        },
    ),
}
2023-04-07T16:40:58.822 helix_vcs [ERROR] failed to obtain current head name for /home/karim/Documents/Projects/code/c/emoji.c
2023-04-07T16:40:58.822 helix_view::editor [ERROR] Failed to initialize the LSP for `source.c` { cannot find binary path }

```

</details>

### Platform

Linux

### Terminal Emulator

gnome-console

### Helix Version

helix 23.03

### PR DESCRIPTION
**Pull request by pascalkuthe**
Closes #6645

I have known the root cause of #6645 for a while: The c grammar has a bug where it sometimes creates non-grapheme aligned highlight spans when cealing with unicode characters like emojois.

This caused crashes because our grapheme alignment code couldn't deal with non-char aligned offsets. I think that is the right (potentially only valid) choice for doing grapheme alignment. 

In our case it was unfortunate as it leads to crashes. I also wanted to get rid of this grapheme alignment anyway because we already render the text one grapheme at a time, so it's really unnecessary to do this. However, in the past it wasn't possible to remove the alignment because the additional highlight iterators merged on top of the base iterator were using char indexing/grapheme aligned indexes. Just switching the TS iterator would have caused highlighting bugs.

However, recently the overlay and base highlights were decoupled so now the base highlights are seperate, and it was possible to convert the base iterator to using byte indexing instead

### CODE REVIEW

File: helix-term/src/ui/editor.rs [hunk 1]
```diff
@@ -315,26 +313,14 @@ impl EditorView {
                 let iter = syntax
                     // TODO: range doesn't actually restrict source, just highlight range
                     .highlight_iter(text.slice(..), Some(range), None)
-                    .map(|event| event.unwrap())
-                    .map(move |event| match event {
-                        // TODO: use byte slices directly
-                        // convert byte offsets to char offset
-                        HighlightEvent::Source { start, end } => {
-                            let start =
-                                text.byte_to_char(ensure_grapheme_boundary_next_byte(text, start));
```
[the remark this answers is not in the document]
Comment (pascalkuthe) [reply helix-term/src/ui/editor.rs:324]: Yeah exactly this is both an optimization and a bug fix

File: helix-term/src/ui/document.rs [hunk 2]
```diff
@@ -36,14 +37,23 @@ impl<F: FnMut(&mut TextRenderer, LinePos)> LineDecoration for F {
...
 /// and yields the active text style and the char_idx where the active
 /// style will have to be recomputed.
-struct StyleIter<'a, H: Iterator<Item = HighlightEvent>> {
+///
+/// IS_BYTE_ITER indicates wether the source iterator provides byte or char
+/// ranges
+///
+/// TODO(ropey2): hopefully onueday helix and ropey will operate entierly
+/// on byte ranges and we can remove this
+struct StyleIter<'a, H: Iterator<Item = HighlightEvent>, const IS_BYTE_ITER: bool> {
```
[the remark this answers is not in the document]
Comment (pascalkuthe) [reply helix-term/src/ui/document.rs]: I did this because sadly enums ca not be used as const parameters yet and I wanted to avoid this check in the hot loop. But its probably a better idea to just let the compiler figure this. Enum is definitely more readable

File: helix-stdx/src/rope.rs [hunk 3]
```diff
@@ -75,4 +93,48 @@ impl<'a> RopeSliceExt<'a> for RopeSlice<'a> {
...
+    fn byte_to_next_char(self, mut byte_idx: usize) -> usize {
+        let (chunk, chunk_byte_off, chunk_char_off, _) = self.chunk_at_byte(byte_idx);
+        byte_idx -= chunk_byte_off;
+        let is_char_boundary =
+            is_utf8_char_boundary(chunk.as_bytes().get(byte_idx).copied().unwrap_or(0));
+        chunk_char_off + byte_to_char_idx(chunk, byte_idx) + !is_char_boundary as usize
+    }
+}
+
+/// copiefd froom std
```
Comment (the-mikedavis) [inline helix-stdx/src/rope.rs:108]:
```suggestion
// copied from std
```

typos but also I think this can be a regular comment rather than doc since it's only interesting if you're looking at this block (rather than in an lsp hover for example)

File: helix-term/src/ui/document.rs [hunk 4]
```diff
@@ -32,14 +33,30 @@ impl<F: FnMut(&mut TextRenderer, LinePos)> LineDecoration for F {
     }
 }
 
+#[derive(Debug, PartialEq, Eq, Clone, Copy)]
+enum StyleIterKind {
+    /// base highlights (usually emitted by TS), byte indecies (potentially not codepoint aligned)
+    BaseHighlights,
+    /// overaly highlights (emitted by cumstom code from selections), char indecies
```
Comment (the-mikedavis) [inline helix-term/src/ui/document.rs:40]:
```suggestion
    /// base highlights (usually emitted by TS), byte indices (potentially not codepoint aligned)
    BaseHighlights,
    /// overlay highlights (emitted by custom code from selections), char indices
```

File: helix-term/src/ui/document.rs [hunk 5]
```diff
@@ -32,14 +33,30 @@ impl<F: FnMut(&mut TextRenderer, LinePos)> LineDecoration for F {
...
+    Overlay,
+}
+
 /// A wrapper around a HighlightIterator
 /// that merges the layered highlights to create the final text style
 /// and yields the active text style and the char_idx where the active
 /// style will have to be recomputed.
+///
+/// IS_BYTE_ITER indicates wether the source iterator provides byte or char
+/// ranges
```
Comment (the-mikedavis) [inline helix-term/src/ui/document.rs:50]: This can be updated to `StyleIterKind` now

**Review by the-mikedavis — APPROVED** [review]
