### PR TITLE
match pairs which don't form a standalone TS node

### LINKED ISSUE #3357: bracket matching works incrrectly sometimes
### Summary

For example in this example, with the cursor on either one of the parentheses in `Some(thing)`, the matching one is not highlighted and hitting `mm` doesn't take you to the matching one, instead it takes you to the bracket on line 6.
```rust
fn main() {
    let opt = None;
    match opt {
        Some(thing) => {},
        None
    }
}
```

### Reproduction Steps

 
[asciinema](https://asciinema.org/a/513464)

I tried this:

1. `hx`
2. open the rust file with the example code from above, make sure the language is set to rust
3. put the cursor on either one of the parentheses in `Some(thing)`
4. hit `mm`
I expected this to happen:
The matching parenthesis is highlighted in step 3, and moved to in step 4

Instead, this happened:
Nothing is highlighted in step 3, and the bracket on line 6 is gone to in step 4

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

22.05-376-g6b84344e

### LINKED ISSUE #5177: Incorrect bracket matching and broken syntax highlighting with this chunk of C text
### Summary

Typing `mm` to go to matching bracket on the top bracket goes to the wrong one, and fiddeling with the file changing the grammar of things (e.g `transform_scope` => `transform_scope()`) fixes it. So does removing any line inside of the `pipeline_scope`.

When the highlighting on the outermost scope is colored blue as in the first screenshot:
image

That means it's broken as seen in the incorrectly highlighted bracket, and when it's green that means it's working as shown below:

### Reproduction Steps

Open helix and paste this buffer of C code into the file, saving it as `tmp.c` or something so it recognizes it as C:

```c
{
  transform_scope
  {
    pipeline_scope(goodpixel_pipeline)
    {
      sgp_set_image(0, image_rightclick);
      cpVect draw_at = cpvadd(entity_pos(b), cpv(BOX_SIZE, 0));
      rotate_at(-entity_rotation(b) - rotangle(b->compass_rotation), draw_at.x, draw_at.y);
      draw_texture_centered(draw_at, BOX_SIZE + sin(exec_time * 5.0) * BOX_SIZE * 0.1);
      sgp_reset_image(0);
    }
  }
}

```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-12-15T14:05:58.168 helix_lsp::transport [ERROR] err <- "I[14:05:58.168] --> reply:textDocument/signatureHelp(25) 18 ms\r\n"
2022-12-15T14:05:58.205 helix_lsp::transport [ERROR] err <- "I[14:05:58.205] ASTWorker building file C:\\Users\\Cameron\\Documents\\flight\\tmp.c version 75 with command inferred from C:/Users/Cameron/Documents/flight/thirdparty/enet/callbacks.c\r\n"
2022-12-15T14:05:58.205 helix_lsp::transport [ERROR] err <- "[C:/Users/Cameron/Documents/flight/]\r\n"
2022-12-15T14:05:58.205 helix_lsp::transport [ERROR] err <- "\"C:\\\\Users\\\\Cameron\\\\AppData\\\\Roaming\\\\ClangPowerTools\\\\LLVM_Lite\\\\Bin\\\\clang++.exe\" --driver-mode=g++ -Wall -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-value -fsyntax-only -DUNICODE -D_UNICODE -D_MT -D_DEBUG -DDEBUG -D_CONSOLE -D_DEBUG_FUNCTIONAL_MACHINERY \"-isystemC:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/include\" \"-isystemC:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/atlmfc/include\" \"-isystemC:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/VS/include\" \"-isystemC:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt\" \"-isystemC:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/um\" \"-isystemC:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/shared\" \"-isystemC:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/winrt\" \"-isystemC:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/cppwinrt\" -Ithirdparty/enet/include -Ithirdparty/Chipmunk2D/include/chipmunk -Ithirdparty -Ithirdparty/Chipmunk2D/include -Ithirdparty/minilzo -Ithirdparty/opus/include \"-resource-dir=C:\\\\Users\\\\Cameron\\\\Documents\\\\lib\\\\clang\\\\15.0.3\" -- \"C:\\\\Users\\\\Cameron\\\\Documents\\\\flight\\\\tmp.c\"\r\n"
2022-12-15T14:05:58.227 helix_lsp::transport [ERROR] err <- "I[14:05:58.227] --> textDocument/publishDiagnostics\r\n"
2022-12-15T14:06:51.146 helix_lsp::transport [ERROR] err <- "I[14:06:51.146] <-- textDocument/signatureHelp(26)\r\n"
2022-12-15T14:06:51.162 helix_lsp::transport [ERROR] err <- "I[14:06:51.162] --> reply:textDocument/signatureHelp(26) 16 ms\r\n"
2022-12-15T14:06:51.296 helix_lsp::transport [ERROR] err <- "I[14:06:51.296] <-- textDocument/didChange\r\n"
2022-12-15T14:06:51.298 helix_lsp::transport [ERROR] err <- "I[14:06:51.298] <-- textDocument/signatureHelp(27)\r\n"
2022-12-15T14:06:51.314 helix_lsp::transport [ERROR] err <- "I[14:06:51.314] --> reply:textDocument/signatureHelp(27) 15 ms\r\n"
2022-12-15T14:06:51.351 helix_lsp::transport [ERROR] err <- "I[14:06:51.351] ASTWorker building file C:\\Users\\Cameron\\Documents\\flight\\tmp.c version 76 with command inferred from C:/Users/Cameron/Documents/flight/thirdparty/enet/callbacks.c\r\n"
2022-12-15T14:06:51.351 helix_lsp::transport [ERROR] err <- "[C:/Users/Cameron/Documents/flight/]\r\n"
2022-12-15T14:06:51.351 helix_lsp::transport [ERROR] err <- "\"C:\\\\Users\\\\Cameron\\\\AppData\\\\Roaming\\\\ClangPowerTools\\\\LLVM_Lite\\\\Bin\\\\clang++.exe\" --driver-mode=g++ -Wall -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-value -fsyntax-only -DUNICODE -D_UNICODE -D_MT -D_DEBUG -DDEBUG -D_CONSOLE -D_DEBUG_FUNCTIONAL_MACHINERY \"-isystemC:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/include\" \"-isystemC:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/atlmfc/include\" \"-isystemC:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/VS/include\" \"-isystemC:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/ucrt\" \"-isystemC:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/um\" \"-isystemC:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/shared\" \"-isystemC:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/winrt\" \"-isystemC:/Program Files (x86)/Windows Kits/10/Include/10.0.22000.0/cppwinrt\" -Ithirdparty/enet/include -Ithirdparty/Chipmunk2D/include/chipmunk -Ithirdparty -Ithirdparty/Chipmunk2D/include -Ithirdparty/minilzo -Ithirdparty/opus/include \"-resource-dir=C:\\\\Users\\\\Cameron\\\\Documents\\\\lib\\\\clang\\\\15.0.3\" -- \"C:\\\\Users\\\\Cameron\\\\Documents\\\\flight\\\\tmp.c\"\r\n"
2022-12-15T14:06:51.354 helix_lsp::transport [ERROR] err <- "I[14:06:51.354] <-- textDocument/signatureHelp(28)\r\n"

```

</details>

### Platform

Windows

### Terminal Emulator

Windows Terminal

### Helix Version

22.12-47-g4acdc03b

### PR DESCRIPTION
**Pull request by pascalkuthe**
Closes #3357
Closes #5177

These issues where caused by us requiring pairs to form a standalone TS node. This change looks at the sibling nodes (so still within the same node) to also find pairs formed by siblings. Syntax trees are usually much wider than deep, so I introduced a fairy aggressive limit on the number of examined nodes. Usually pairs form immediate siblings and looking at additional siblings is just done to handle weird grammars (and comments). The limit does lead to missing some matches but those cases are so rare that it's worth the improved performance IMO.

### CODE REVIEW

File: helix-core/src/match_brackets.rs [hunk 1]
```diff
@@ -42,35 +46,73 @@ pub fn find_matching_bracket(syntax: &Syntax, doc: &Rope, pos: usize) -> Option<
...
 
     loop {
-        let (start_byte, end_byte) = surrounding_bytes(doc, &node)?;
-        let (start_char, end_char) = (doc.byte_to_char(start_byte), doc.byte_to_char(end_byte));
+        if node.is_named() {
+            let (start_byte, end_byte) = surrounding_bytes(doc, &node)?;
+            let (start_char, end_char) = (doc.byte_to_char(start_byte), doc.byte_to_char(end_byte));
+
+            if is_valid_pair(doc, start_char, end_char) {
+                if end_byte == pos {
```
Comment (dead10ck) [inline helix-core/src/match_brackets.rs:70]: Should this be `end_char`?

File: helix-core/src/match_brackets.rs [hunk 2]
```diff
@@ -42,35 +46,77 @@ pub fn find_matching_bracket(syntax: &Syntax, doc: &Rope, pos: usize) -> Option<
...
+                    return Some(start_char);
```
Comment (dead10ck) [inline helix-core/src/match_brackets.rs:71]: `start_char`?

**Comment by pascalkuthe** [comment]
also addresses https://github.com/helix-editor/helix/issues/3357#issuecomment-1411230516 (which is an unrelated bug but a small fix that makes sense to include here)

I also did wind up including a (very limited) plaintext fallback to handle text-only nodes (c preprocessor nodes for example https://github.com/helix-editor/helix/issues/3357#issuecomment-1503837732) but to not break existing workflows this only works when absolutely no other TS match it found (and only on the brackets, and within the first named parent TS node ). I am still not sure if that's really worth having since it will case brackets inside literals to be highlighted and that feels weird to me.

File: helix-core/src/match_brackets.rs [hunk 3]
```diff
@@ -161,14 +203,68 @@ fn surrounding_bytes(doc: &Rope, node: &Node) -> Option<(usize, usize)> {
...
+
+/// Tests if this node is a pair opening and returns the expected close char
+fn as_char(doc: RopeSlice, node: &Node) -> Option<(usize, char)> {
+    // TODO: multi char/non ASCII pairs
+    if node.byte_range().len() != 1 {
+        return None;
+    }
+    let pos = doc.try_byte_to_char(node.start_byte()).ok()?;
+    Some((pos, doc.char(pos)))
+}
```
[the remark this answers is not in the document]
Comment (pascalkuthe) [reply helix-core/src/match_brackets.rs:259]: sorry forgot to update the doc comment. This checks if a TS node just contains a single char (and returns that char in that case).

File: helix-core/src/match_brackets.rs (hunk 1 above)
Comment (pascalkuthe) [reply helix-core/src/match_brackets.rs:70]: no pos is a byte pos (see above). This is existing code btw. the diff looks larger because of the new surrounding condition

File: helix-core/src/match_brackets.rs (hunk 2 above)
Comment (pascalkuthe) [reply helix-core/src/match_brackets.rs:71]: same here this code is unchanged

File: helix-core/src/match_brackets.rs (hunk 1 above)
Comment (dead10ck) [reply helix-core/src/match_brackets.rs:70]: Ah ok 👍

File: helix-core/src/match_brackets.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (pascalkuthe) [reply helix-core/src/match_brackets.rs]: updated the docs hope its clear now

**Review by dead10ck — APPROVED** [review]
Ok this looks good to me, thanks!

File: helix-core/src/match_brackets.rs [hunk 4]
```diff
@@ -161,18 +207,72 @@ fn surrounding_bytes(doc: &Rope, node: &Node) -> Option<(usize, usize)> {
...
+        })
+}
+
+/// Tests if this node is a pair close char and returns the expected open char
+fn as_open_pair(doc: RopeSlice, node: &Node) -> Option<char> {
+    let close = as_char(doc, node)?.1;
+    PAIRS
+        .iter()
+        .find_map(|&(open, close_)| (close_ == close).then_some(open))
+}
```
Comment (alevinval) [inline helix-core/src/match_brackets.rs:252]: I think you have implemented the exact same logic twice, but just gave it a different name. Was this on purpose? If not I would suggest finding a better name, and re-use the same implementation

File: helix-core/src/match_brackets.rs [hunk 5]
```diff
@@ -161,18 +207,72 @@ fn surrounding_bytes(doc: &Rope, node: &Node) -> Option<(usize, usize)> {
...
+///
+/// The position of the found node or `None` otherwise
+fn find_close_pair(doc: RopeSlice, node: Option<Node>, close: char) -> Option<usize> {
+    iter::successors(node, |node| node.next_sibling())
+        .take(MATCH_LIMIT)
+        .find_map(|node| {
+            let (pos, c) = as_char(doc, &node)?;
+            (c == close).then_some(pos)
+        })
+}
```
Comment (alevinval) [inline helix-core/src/match_brackets.rs:244]: On a similar line, this implementation is very similar to `find_open_pair` except for the closure going to the previous/next sibling. Maybe we can write it once and accept the closure instead.

File: helix-core/src/match_brackets.rs [hunk 6]
```diff
@@ -42,35 +46,80 @@ pub fn find_matching_bracket(syntax: &Syntax, doc: &Rope, pos: usize) -> Option<
...
+            let (start_char, end_char) = (doc.byte_to_char(start_byte), doc.byte_to_char(end_byte));
+
+            if is_valid_pair(doc, start_char, end_char) {
+                if end_byte == pos {
+                    return Some(start_char);
+                }
+
+                // We return the end char if the cursor is either on the start char
+                // or at some arbitrary position between start and end char.
+                if traverse_parents || start_byte == pos {
```
Comment (alevinval) [inline helix-core/src/match_brackets.rs:76]: I might be missing something, how is checking `traverse_parents` relevant here? We are inside a named node, we found a valid pair. Unless I'm wrong, we don't care about the value of `traverse_parents` here.

Comment (alevinval) [reply helix-core/src/match_brackets.rs:76]: In fact maybe we should simply always return `Some(end_char)` regardless of anything, like:
```
if end_byte == pos { return Some(start_char) } else { Some(end_char) }
```

Comment (pascalkuthe) [reply helix-core/src/match_brackets.rs:76]: The check was introduced in 59e7dce33caaa57d1d16da0242accbabec7a3fef

to address https://github.com/helix-editor/helix/issues/3357#issuecomment-1411230516. When transverse_parents is false we only want to consider matches exactly on the cursor (which this check enforces)

File: helix-core/src/match_brackets.rs (hunk 4 above)
Comment (pascalkuthe) [reply helix-core/src/match_brackets.rs]: ah right I copied that function and then wanted to change it but forgot. I pushed a fix

Comment (alevinval) [reply helix-core/src/match_brackets.rs]: Ok I don't see this issue anymore with recent push :)

**Review by alevinval — APPROVED** [review]

File: helix-core/src/match_brackets.rs (hunk 5 above)
Comment (pascalkuthe) [reply helix-core/src/match_brackets.rs]: I found a nice way to abstract their after all that doesn't require a closure

Comment (alevinval) [reply helix-core/src/match_brackets.rs]: Less code to worry about :)
