### PR TITLE
fix lsp config reload

### LINKED ISSUE #9398: Language server config is not updated for `:lsp-restart` after `:config-reload`
### Summary

This behavior seems to stem from how`syn_loader` is replaced rather than the interior value being replaced:

https://github.com/helix-editor/helix/blob/9c56afeff36489ff73a9b160fe7d57360a3f9952/helix-term/src/application.rs#L383-L388

combined with us not updating the value for `Registry` as well. I think we could use `ArcSwap` here like we do for the config.

### Reproduction Steps

1. Open the helix repo in Helix and open a document.
2. Add a custom language config for rust-analyzer.
3. `:config-reload` and `:lsp-restart`

### Helix Version

9c56afeff36489ff73a9b160fe7d57360a3f9952

### PR DESCRIPTION
**Pull request by kyfanc**
This PR attempts to fix #9398 

`syn_loader` was replaced rather than interior value being replace, 
old value was still being referenced and not updated after `:config-refresh`. 

By using `ArcSwap` similarly to `config`, each `.load()` call will return the most updated value.

## Testing Steps

1. Open the helix repo in Helix and open a document.
1. Add a custom language config for `rust-analyzer` in `languages.toml`.
    ```
      [language-server.rust-analyzer.config]
      cargo.features = "all" 
      rust-analyzer.check.command = "clippy"
    + rust-analyzer.inlayHints.typeHints.enable= false
    + rust-analyzer.inlayHints.parameterHints.enable= false
    + rust-analyzer.inlayHints.chainingHints.enable= false
    ```
1. `:config-reload` and `:lsp-restart`
1. page-up/down to trigger re-rendering
1. inlay hints should now be disabled, lsp config is reloaded

PS. This is my first PR, please let me know if there is anything I missed/ overlooked.

### CODE REVIEW

File: helix-term/src/application.rs [hunk 1]
```diff
@@ -398,7 +398,8 @@ impl Application {
         let syntax_config = helix_core::config::user_syntax_loader()
             .map_err(|err| anyhow::anyhow!("Failed to load language config: {}", err))?;
 
-        self.syn_loader = std::sync::Arc::new(syntax::Loader::new(syntax_config));
+        self.syn_loader
+            .store(Arc::new(syntax::Loader::new(syntax_config)));
         self.editor.syn_loader = self.syn_loader.clone();
```
Comment (kirawi) [inline helix-term/src/application.rs:403]:
```suggestion
```

**Review by kirawi — APPROVED** [review]
I don't see anything obviously incorrect here; it's pretty straightforward.

**Review by the-mikedavis — APPROVED** [review]

**Review by pascalkuthe — APPROVED** [review]

**Comment by pascalkuthe** [comment]
There are some small conflicts with some other PRs that were merged once those are resolved this lgtm.

**Review by the-mikedavis — APPROVED** [review]

**Review by pascalkuthe — APPROVED** [review]
