### PR TITLE
Show "Invalid regex" message on enter (Validate)

### LINKED ISSUE #3034: "Invalid regex" message not shown on enter
### Summary

When selecting/searching with an invalid regex pattern, the "Invalid regex" prompt is only shown once you hit `n` (next), and not on enter.

### Reproduction Steps

 

I tried this:

1. type some text
2. select the text
3. use regex select command with `s`
4. type an invalid regex pattern (ie `[`)
5. hit enter

I expected this to happen:
I see the message `Invalid regex: [` at the bottom

Instead, this happened:
I don't see the message until I hit `n` to go to next selection

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

helix 22.05

### PR DESCRIPTION
**Pull request by A-Walrus**
Fixes #3034

### CODE REVIEW

File: helix-term/src/ui/mod.rs [hunk 1]
```diff
@@ -95,7 +95,15 @@ pub fn regex_prompt(
 
                             view.ensure_cursor_in_view(doc, config.scrolloff);
                         }
-                        Err(_err) => (), // TODO: mark command line as error
+                        Err(_err) => {
+                            if event == PromptEvent::Validate {
+                                let error = format!("Invalid regex: {}", input);
+                                cx.editor.set_error(error);
```
Comment (sudormrfbin) [inline helix-term/src/ui/mod.rs:101]: If it errors out we should also restore the initial cursor position, identical to what happens in the `PrompEvent::Abort` block a few lines up.

File: helix-term/src/ui/mod.rs [hunk 2]
```diff
@@ -95,7 +95,15 @@ pub fn regex_prompt(
 
                             view.ensure_cursor_in_view(doc, config.scrolloff);
                         }
-                        Err(_err) => (), // TODO: mark command line as error
+                        Err(_err) => {
+                            if event == PromptEvent::Validate {
+                                let error = format!("Invalid regex: {}", input);
```
Comment (sudormrfbin) [inline helix-term/src/ui/mod.rs:100]: We should show the exact error returned by the regex library (formatting with `err` should work) since "Invalid input" isn't very useful for fixing the invalid regex.

Comment (A-Walrus) [reply helix-term/src/ui/mod.rs:104]: The regex errors are multiple lines, for example:
```
regex parse error:
    q(?!u)
     ^^^
error: look-around, including look-ahead and look-behind, is not supported
```
How should they be displayed? Through some pop up window? Or maybe shortened to fit on the one line of the status message?

Comment (kirawi) [reply helix-term/src/ui/mod.rs:104]: You could try creating a popup above the regex input and see how it looks.

Comment (A-Walrus) [reply helix-term/src/ui/mod.rs]: Added the popup, this is how it looks:
image

Comment (archseer) [reply helix-term/src/ui/mod.rs]: Popups are going to be annoying to clear, what about only taking the last line of the error for now? It contains a description

Comment (sudormrfbin) [reply helix-term/src/ui/mod.rs]: How about making them auto close? That way they get cleared on the next keypress.
