### PR TITLE
LSP: Send replies for malformed and unhandled RPC requests

### LINKED ISSUE #5958: Issues with pyright-langserver
### Summary

Using the pyright-langserver for my linter results in async timeout error whenever I do anything.

### Reproduction Steps

Install the pyright langsever as described on the wiki page.

This is my global config.
```toml
[[language]]
name = "python"
roots = ["pyproject.toml"]
language-server = { command = "/usr/local/bin/pyright-langserver", args = ["--stdio"] }
config = {} # <- this is the important line

formatter = { command = "black", args = ["--quiet", "-"]}
auto-format = true
```

### Helix log

Not sure where the exact error was so I put everything.

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-02-10T20:12:43.970 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["[scratch]"]
2023-02-10T20:13:24.302 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
2023-02-10T20:13:48.899 helix_view::editor [ERROR] editor error: Could not load theme: No such file or directory (os error 2)
2023-02-10T20:14:48.424 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:14:55.819 helix_term::application [WARN] failed to load theme `monokai` - No such file or directory (os error 2)
2023-02-10T20:14:55.820 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:15:17.382 helix_term::application [WARN] failed to load theme `monokai` - No such file or directory (os error 2)
2023-02-10T20:15:19.984 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
2023-02-10T20:19:31.972 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
2023-02-10T20:19:48.649 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:20:44.265 helix_view::editor [ERROR] editor error: no last accessed buffer
2023-02-10T20:21:43.280 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:29:19.745 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
2023-02-10T20:29:25.183 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
2023-02-10T20:33:09.364 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
2023-02-10T20:35:24.915 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:39:24.922 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:39:41.844 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:39:51.057 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:40:24.361 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:40:54.960 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:43:41.260 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
2023-02-10T20:44:24.100 helix_lsp::transport [ERROR] err <- "Ignoring notification for unknown method \"workspace/didChangeConfiguration\"\n"
2023-02-10T20:45:17.068 helix_lsp::client [INFO] Using custom LSP config: {}
2023-02-10T20:45:17.068 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":false},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]},"publishDiagnostics":{},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":false},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"executeCommand":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":false},"workspaceFolders":true}},"clientInfo":{"name":"helix","version":"22.12 (6929a12f)"},"initializationOptions":{},"processId":116113,"rootPath":"/home/lunar/Documents/Projects/Python/code-runner","rootUri":"file:///home/lunar/Documents/Projects/Python/code-runner","workspaceFolders":[{"name":"code-runner","uri":"file:///home/lunar/Documents/Projects/Python/code-runner"}]},"id":0}
2023-02-10T20:45:17.419 helix_lsp::transport [INFO] <- {"id": 0, "jsonrpc": "2.0", "result": {"capabilities": {"textDocumentSync": {"openClose": true, "change": 2, "save": true}, "hoverProvider": true, "codeActionProvider": {"codeActionKinds": ["quickfix", "source.fixAll", "source.organizeImports", "CodeActionKind.SourceFixAll.ruff", "CodeActionKind.SourceOrganizeImports.ruff"], "resolveProvider": true}, "executeCommandProvider": {"commands": ["ruff.applyAutofix", "ruff.applyOrganizeImports"]}, "workspace": {"workspaceFolders": {"supported": true, "changeNotifications": true}, "fileOperations": {}}}, "serverInfo": {"name": "Ruff", "version": "0.0.17"}}}
2023-02-10T20:45:17.419 helix_lsp::transport [INFO] <- {"capabilities":{"codeActionProvider":{"codeActionKinds":["quickfix","source.fixAll","source.organizeImports","CodeActionKind.SourceFixAll.ruff","CodeActionKind.SourceOrganizeImports.ruff"],"resolveProvider":true},"executeCommandProvider":{"commands":["ruff.applyAutofix","ruff.applyOrganizeImports"]},"hoverProvider":true,"textDocumentSync":{"change":2,"openClose":true,"save":true},"workspace":{"fileOperations":{},"workspaceFolders":{"changeNotifications":true,"supported":true}}},"serverInfo":{"name":"Ruff","version":"0.0.17"}}
2023-02-10T20:45:17.419 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialized","params":{}}
2023-02-10T20:45:17.419 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{}}}
2023-02-10T20:45:17.419 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"python","text":"TOKEN=\"REDACTED LOL\"\nPISTON=\"https://emkc.org/api/v2/piston/\"\n\n\n\"MTA3Mzc3MTY1ODkwNjcwMTk1NA.GbYAok.6WkybZrDzwgHL1JWLJeR2FMvtrX2gslhNNm5dk\"\n","uri":"file:///home/lunar/Documents/Projects/Python/code-runner/config.py","version":0}}}
2023-02-10T20:45:17.422 helix_lsp::transport [ERROR] err <- "Ignoring notification for unknown method \"workspace/didChangeConfiguration\"\n"
2023-02-10T20:45:17.424 helix_lsp::transport [INFO] <- {"params": {"type": 4, "message": "Using interpreter executable: /home/lunar/.pyenv/versions/3.11.1/bin/ruff"}, "method": "window/logMessage", "jsonrpc": "2.0"}
2023-02-10T20:45:17.424 helix_lsp::transport [INFO] <- {"params": {"type": 4, "message": "Running Ruff with: ['/home/lunar/.pyenv/versions/3.11.1/bin/ruff', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--stdin-filename', '/home/lunar/Documents/Projects/Python/code-runner/config.py']"}, "method": "window/logMessage", "jsonrpc": "2.0"}
2023-02-10T20:45:17.425 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "Using interpreter executable: /home/lunar/.pyenv/versions/3.11.1/bin/ruff" }
2023-02-10T20:45:17.425 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Log, message: "Running Ruff with: ['/home/lunar/.pyenv/versions/3.11.1/bin/ruff', '--no-cache', '--no-fix', '--quiet', '--format', 'json', '-', '--stdin-filename', '/home/lunar/Documents/Projects/Python/code-runner/config.py']" }
2023-02-10T20:45:17.431 helix_lsp::transport [INFO] <- {"params": {"uri": "file:///home/lunar/Documents/Projects/Python/code-runner/config.py", "diagnostics": []}, "method": "textDocument/publishDiagnostics", "jsonrpc": "2.0"}
2023-02-10T20:45:18.644 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"shutdown","id":1}
2023-02-10T20:45:18.647 helix_lsp::transport [INFO] <- {"id": 1, "jsonrpc": "2.0", "result": null}
2023-02-10T20:45:18.648 helix_lsp::transport [INFO] <- null
2023-02-10T20:45:18.648 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"exit"}
2023-02-10T20:46:28.804 helix_lsp::transport [ERROR] err <- "Ignoring notification for unknown method \"workspace/didChangeConfiguration\"\n"
2023-02-10T20:50:18.503 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:50:23.068 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T20:52:14.228 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { IO Error: No such file or directory (os error 2) }
2023-02-10T20:53:56.293 helix_view::editor [ERROR] editor error: Could not load theme: No such file or directory (os error 2)
2023-02-10T20:56:58.749 helix_view::document [ERROR] Formatter error: error: cannot format -: Cannot parse: 21:9:         )i

2023-02-10T21:00:49.711 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { IO Error: No such file or directory (os error 2) }
2023-02-10T21:01:12.589 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { IO Error: No such file or directory (os error 2) }
2023-02-10T21:03:40.184 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T21:03:56.407 helix_view::editor [ERROR] editor error: can't save file, parent directory does not exist
2023-02-10T21:03:58.385 helix_view::editor [ERROR] editor error: can't save file, parent directory does not exist
2023-02-10T21:03:58.385 helix_view::editor [ERROR] editor error: can't save file, parent directory does not exist
2023-02-10T21:04:01.347 helix_view::editor [ERROR] editor error: no such command: 'fW'
2023-02-10T21:04:03.076 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: [".helix/languages.toml"]
2023-02-10T21:04:05.426 helix_view::editor [ERROR] editor error: can't save file, parent directory does not exist
2023-02-10T21:04:14.931 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T21:04:28.125 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { IO Error: No such file or directory (os error 2) }
2023-02-10T21:05:19.411 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T21:06:09.231 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { IO Error: No such file or directory (os error 2) }
2023-02-10T21:07:09.749 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T21:07:49.129 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { IO Error: No such file or directory (os error 2) }
2023-02-10T21:08:28.809 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T21:08:31.005 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T21:08:35.142 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T21:09:30.506 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-10T21:09:30.508 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:09:51.975 helix_view::editor [ERROR] editor error: 1 unsaved buffer(s) remaining: ["bot/model.py"]
2023-02-10T21:09:53.433 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:09:54.235 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:09:54.587 helix_view::editor [ERROR] editor error: no such command: 'qw!'
2023-02-10T21:09:56.451 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(1)), original request likely timed out
2023-02-10T21:09:56.452 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(2)), original request likely timed out
2023-02-10T21:11:45.704 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-10T21:11:45.706 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:12:11.559 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:12:11.812 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:12:12.721 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:12:20.254 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(1)), original request likely timed out
2023-02-10T21:12:20.255 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(2)), original request likely timed out
2023-02-10T21:12:20.255 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(3)), original request likely timed out
2023-02-10T21:12:24.604 helix_view::editor [ERROR] editor error: Register [@] empty
2023-02-10T21:13:08.939 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-10T21:13:08.940 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:13:11.072 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:13:11.080 helix_lsp::transport [ERROR] err: <- StreamClosed
2023-02-10T21:13:12.351 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-10T21:13:12.352 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:13:16.820 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:13:16.827 helix_lsp::transport [ERROR] err: <- StreamClosed
2023-02-10T21:13:18.105 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-10T21:13:18.107 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:14:18.572 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-10T21:14:56.831 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-10T21:14:56.832 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:15:06.405 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:15:06.416 helix_lsp::transport [ERROR] err: <- StreamClosed
2023-02-10T21:15:07.567 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-10T21:15:07.568 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:16:11.356 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:16:14.026 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:16:46.080 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:16:47.065 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:16:47.693 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:16:48.338 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:16:54.096 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:16:55.360 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:17:05.568 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:17:30.246 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:17:33.462 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:17:34.730 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:17:53.735 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:17:54.983 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:17:56.555 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:17:59.156 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(1)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(2)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(3)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(4)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(5)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(6)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(7)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(8)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(9)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(10)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(11)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(12)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(13)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(14)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(15)), original request likely timed out
2023-02-10T21:18:29.364 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(16)), original request likely timed out
2023-02-10T21:18:32.297 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-10T21:18:32.300 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:19:37.505 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-10T21:19:37.505 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:19:55.264 helix_view::theme [WARN] Theme: malformed hexcode: light-black
2023-02-10T21:19:55.264 helix_view::theme [WARN] Theme: malformed hexcode: light-black
2023-02-10T21:19:55.264 helix_view::theme [WARN] Theme: malformed hexcode: purple
2023-02-10T21:22:11.022 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-10T21:22:11.023 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-10T21:22:32.851 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:35.721 helix_view::document [ERROR] Formatter error: error: cannot format -: Cannot parse: 17:4:     return cls(

2023-02-10T21:22:35.778 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:37.131 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:37.423 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:37.547 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:37.669 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:37.786 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:37.935 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:38.069 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:38.269 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:38.278 helix_view::document [ERROR] Formatter error: error: cannot format -: Cannot parse: 17:4:     return cls(

2023-02-10T21:22:40.037 helix_view::document [ERROR] Formatter error: error: cannot format -: Cannot parse: 17:4:     return cls(

2023-02-10T21:22:40.083 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:53.948 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:22:54.165 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:23:04.396 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:23:06.271 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:23:06.876 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:23:09.429 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:23:10.573 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:23:12.040 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:23:27.304 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-10T21:26:03.064 helix_view::editor [ERROR] editor error: Register [@] empty
2023-02-10T21:26:05.020 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(1)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(2)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(3)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(4)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(5)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(6)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(7)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(8)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(9)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(10)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(11)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(12)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(13)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(15)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(16)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(17)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(18)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(19)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(14)), original request likely timed out
2023-02-10T21:26:05.021 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(20)), original request likely timed out
2023-02-12T12:36:28.103 helix_view::editor [ERROR] Failed to initialize the LSP for `source.bash` { cannot find binary path }
2023-02-12T16:48:10.044 helix_view::editor [ERROR] Failed to initialize the LSP for `text.html.basic` { cannot find binary path }
2023-02-12T16:48:19.739 helix_view::editor [ERROR] Failed to initialize the LSP for `source.java` { cannot find binary path }
2023-02-12T16:55:29.824 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { IO Error: No such file or directory (os error 2) }
2023-02-12T16:55:35.695 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { IO Error: No such file or directory (os error 2) }
2023-02-12T16:55:48.564 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-12T16:55:55.642 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { IO Error: No such file or directory (os error 2) }
2023-02-12T16:57:27.243 helix_view::editor [ERROR] Failed to initialize the LSP for `source.js` { cannot find binary path }
2023-02-12T16:57:34.371 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { IO Error: No such file or directory (os error 2) }
2023-02-12T16:58:14.722 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-12T16:58:14.722 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-12T16:58:42.849 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T16:58:45.643 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T16:58:47.853 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:01:12.613 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:01:16.183 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:01:17.050 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:01:17.141 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:01:20.146 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:03:41.981 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:10:19.028 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-12T17:10:56.039 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-12T17:10:56.040 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-12T17:10:58.945 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-12T17:10:58.946 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-12T17:11:20.128 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:11:31.704 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
2023-02-12T17:11:46.167 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:12:55.116 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(2)), original request likely timed out
2023-02-12T17:12:55.116 helix_lsp::transport [ERROR] Tried sending response into a closed channel (id=Num(1)), original request likely timed out
2023-02-12T17:12:55.913 helix_term::application [ERROR] Language Server: Method not found client/registerCapability
2023-02-12T17:12:55.914 helix_term::application [ERROR] received malformed method call from Language Server: workspace/configuration: protocol error: InvalidParams: Invalid params: invalid value: string "", expected relative URL without a base.
2023-02-12T17:13:27.746 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:13:28.147 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:13:29.246 helix_view::editor [ERROR] editor error: Async job failed: request timed out
2023-02-12T17:14:27.081 helix_view::editor [ERROR] Failed to initialize the LSP for `source.toml` { cannot find binary path }
```

</details>

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 22.12 (6929a12f)

### PR DESCRIPTION
**Pull request by the-mikedavis**
Previously we did not respond to malformed or unhandled LSP requests. The JSONRPC spec says that all non-notification requests must have responses:

> When a rpc call is made, the Server MUST reply with a Response,
> except for in the case of Notifications

(Note that Helix is the "Server" in this case. Also from the spec: "The Server is defined as the origin of Response objects and the handler of Request objects.")

So this change sends error replies for requests which can't be parsed or handled. Request IDs are also now added to the log messages for unhandled requests.

Fixes #5958

### CODE REVIEW

File: helix-term/src/application.rs [hunk 1]
```diff
@@ -951,24 +951,32 @@ impl Application {
...
-                        return;
+                        error!(
+                            "Language Server: Method {} not found in request {}",
+                            method, id
+                        );
+                        Err(helix_lsp::jsonrpc::Error {
+                            code: helix_lsp::jsonrpc::ErrorCode::MethodNotFound,
+                            message: format!("Method not found: {}", method),
+                            data: None,
+                        })
```
Comment (the-mikedavis) [inline helix-term/src/application.rs:964]: Pyright exits if we send a JSONRPC error for its registerClient request. I'm pretty sure this is a bug in pyright or one of its dependencies.

<details><summary>Log...</summary>

```
2023-02-19T15:46:40.289 helix_lsp::client [INFO] Using custom LSP config: {}
2023-02-19T15:46:40.290 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialize","params":{"capabilities":{"general":{"positionEncodings":["utf-32","utf-8","utf-16"]},"textDocument":{"codeAction":{"codeActionLiteralSupport":{"codeActionKind":{"valueSet":["","quickfix","refactor","refactor.extract","refactor.inline","refactor.rewrite","source","source.organizeImports"]}}},"completion":{"completionItem":{"deprecatedSupport":true,"insertReplaceSupport":true,"resolveSupport":{"properties":["documentation","detail","additionalTextEdits"]},"snippetSupport":false,"tagSupport":{"valueSet":[1]}},"completionItemKind":{}},"hover":{"contentFormat":["markdown"]},"publishDiagnostics":{},"rename":{"dynamicRegistration":false,"honorsChangeAnnotations":false,"prepareSupport":false},"signatureHelp":{"signatureInformation":{"activeParameterSupport":true,"documentationFormat":["markdown"],"parameterInformation":{"labelOffsetSupport":true}}}},"window":{"workDoneProgress":true},"workspace":{"applyEdit":true,"configuration":true,"didChangeConfiguration":{"dynamicRegistration":false},"executeCommand":{"dynamicRegistration":false},"symbol":{"dynamicRegistration":false},"workspaceFolders":true}},"clientInfo":{"name":"helix","version":"22.12 (31b0c758)"},"initializationOptions":{},"processId":102760,"rootPath":"/home/michael/tmp","rootUri":"file:///home/michael/tmp","workspaceFolders":[{"name":"tmp","uri":"file:///home/michael/tmp"}]},"id":0}
2023-02-19T15:46:40.409 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Pyright language server 1.1.294 starting"}}
2023-02-19T15:46:40.409 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Server root directory: /home/michael/tmp/node_modules/pyright/dist/"}}
2023-02-19T15:46:40.409 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "Pyright language server 1.1.294 starting" }
2023-02-19T15:46:40.413 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","method":"window/logMessage","params":{"type":3,"message":"Starting service instance \"tmp\""}}
2023-02-19T15:46:40.413 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":0,"result":{"capabilities":{"textDocumentSync":2,"definitionProvider":{"workDoneProgress":true},"declarationProvider":{"workDoneProgress":true},"typeDefinitionProvider":{"workDoneProgress":true},"referencesProvider":{"workDoneProgress":true},"documentSymbolProvider":{"workDoneProgress":true},"workspaceSymbolProvider":{"workDoneProgress":true},"hoverProvider":{"workDoneProgress":true},"documentHighlightProvider":{"workDoneProgress":true},"renameProvider":{"prepareProvider":true,"workDoneProgress":true},"completionProvider":{"triggerCharacters":[".","["],"resolveProvider":true,"workDoneProgress":true,"completionItem":{"labelDetailsSupport":true}},"signatureHelpProvider":{"triggerCharacters":["(",",",")"],"workDoneProgress":true},"codeActionProvider":{"codeActionKinds":["quickfix","source.organizeImports"],"workDoneProgress":true},"executeCommandProvider":{"commands":[],"workDoneProgress":true},"callHierarchyProvider":true}}}
2023-02-19T15:46:40.413 helix_lsp::transport [INFO] <- {"capabilities":{"callHierarchyProvider":true,"codeActionProvider":{"codeActionKinds":["quickfix","source.organizeImports"],"workDoneProgress":true},"completionProvider":{"completionItem":{"labelDetailsSupport":true},"resolveProvider":true,"triggerCharacters":[".","["],"workDoneProgress":true},"declarationProvider":{"workDoneProgress":true},"definitionProvider":{"workDoneProgress":true},"documentHighlightProvider":{"workDoneProgress":true},"documentSymbolProvider":{"workDoneProgress":true},"executeCommandProvider":{"commands":[],"workDoneProgress":true},"hoverProvider":{"workDoneProgress":true},"referencesProvider":{"workDoneProgress":true},"renameProvider":{"prepareProvider":true,"workDoneProgress":true},"signatureHelpProvider":{"triggerCharacters":["(",",",")"],"workDoneProgress":true},"textDocumentSync":2,"typeDefinitionProvider":{"workDoneProgress":true},"workspaceSymbolProvider":{"workDoneProgress":true}}}
2023-02-19T15:46:40.414 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"initialized","params":{}}
2023-02-19T15:46:40.415 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":0,"method":"client/registerCapability","params":{"registrations":[{"id":"19a6c6b9-cbac-4619-bb83-3fbf546bb213","method":"workspace/didChangeWorkspaceFolders","registerOptions":{}}]}}
2023-02-19T15:46:40.418 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "Server root directory: /home/michael/tmp/node_modules/pyright/dist/" }
2023-02-19T15:46:40.418 helix_term::application [INFO] window/logMessage: LogMessageParams { typ: Info, message: "Starting service instance \"tmp\"" }
2023-02-19T15:46:40.418 helix_term::application [ERROR] Language Server: Method client/registerCapability not found in request 0
2023-02-19T15:46:40.418 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"workspace/didChangeConfiguration","params":{"settings":{}}}
2023-02-19T15:46:40.418 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found: client/registerCapability"},"id":0}
2023-02-19T15:46:40.418 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/didOpen","params":{"textDocument":{"languageId":"python","text":"import json\n\ndef func(a):\n    print(a)\n","uri":"file:///home/michael/tmp/f.py","version":0}}}
2023-02-19T15:46:40.419 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","id":1,"method":"workspace/configuration","params":{"items":[{"scopeUri":"file:///home/michael/tmp","section":"python"}]}}
2023-02-19T15:46:40.419 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","result":[null],"id":1}
2023-02-19T15:46:40.562 helix_lsp::transport [ERROR] err <- "Error: Method not found: client/registerCapability\n"
2023-02-19T15:46:40.562 helix_lsp::transport [ERROR] err <- "    at handleResponse (/home/michael/tmp/node_modules/pyright/dist/pyright-internal/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n"
2023-02-19T15:46:40.562 helix_lsp::transport [ERROR] err <- "    at handleMessage (/home/michael/tmp/node_modules/pyright/dist/pyright-internal/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n"
2023-02-19T15:46:40.562 helix_lsp::transport [ERROR] err <- "    at processMessageQueue (/home/michael/tmp/node_modules/pyright/dist/pyright-internal/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n"
2023-02-19T15:46:40.562 helix_lsp::transport [ERROR] err <- "    at Immediate.<anonymous> (/home/michael/tmp/node_modules/pyright/dist/pyright-internal/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n"
2023-02-19T15:46:40.562 helix_lsp::transport [ERROR] err <- "    at processImmediate (node:internal/timers:476:21)\n"
2023-02-19T15:46:40.568 helix_lsp::transport [ERROR] err: <- StreamClosed
```
</details>

Comment (the-mikedavis) [reply helix-term/src/application.rs:964]: This is actually a big rat's nest in the LSP landscape. There is a bunch of prior discussion about this: https://github.com/microsoft/vscode-languageserver-node/issues/713, https://github.com/microsoft/pyright/issues/1302, https://github.com/neovim/neovim/issues/13448, https://github.com/sublimelsp/LSP/pull/911, https://github.com/neovim/nvim-lspconfig/pull/471

LSP clients either ended up either fully implementing dynamic callback registration or sending dummy responses for registerClient.

The problem is in the https://github.com/microsoft/vscode-languageserver-node dependency which is used by quite a few popular servers. If a server sets up an `onDidChangeWorkspaceFolders` callback, it will try to register `workspace/didChangeWorkspaceFolders`. A change in the way failed Promises are handled in nodejs v15 makes that registration Promise fatal for the server if we send an error.

That dependency sends a registration request for that case because of an ambiguity in the LSP spec: their reasoning is that if workspaceFolders is enabled in the initialization params then that means that the client supports dynamic registration of the workspace folder change notification. workspaceFolders doesn't have a dynamicRegistration setting so you can't explicitly say that you don't support dynamic registration for that capability. I disagree with their interpretation (and it looks like some nvim and sublime folks do too) but it looks unlikely that they will accept a change upstream. This will all be moot if we implement dynamic capability registration anyways so I will add a hack for now like neovim does.

Comment (pascalkuthe) [reply helix-term/src/application.rs:964]: Maybe I am missing something but it sounds Luke this is actually solved if the server send the static capabilities correctly https://github.com/microsoft/vscode-languageserver-node/issues/713#issuecomment-754551117

Comment (pascalkuthe) [reply helix-term/src/application.rs:964]: I am not sure we even want dynamic capability registration it seems like a pretty large effort with loads of edgecases that provides little advatanges over static registration. Especially since we can opt out of dynamic registration (except in this edgecase). Maybe I am missing some feature this provides but I can't think of any

**Comment by senevr** [comment]
My issue (https://github.com/helix-editor/helix/issues/6043) got closed as a duplicate to https://github.com/helix-editor/helix/issues/5958 and couldn't find any solution, then saw that you this PR is the supposed fix, so I hope it gets approved and thank you for taking the time for fixing this.

File: helix-term/src/application.rs (hunk 1 above)
Comment (the-mikedavis) [reply helix-term/src/application.rs:964]: Yeah I think I remember some prior discussion about dynamic capability registration and it not really being desired. Neovim is able to ignore it so I don't think we necessarily need it. I'll remove the TODO for adding it 👍

Comment (the-mikedavis) [reply helix-term/src/application.rs:964]: > Maybe I am missing something but it sounds like this is actually solved if the server send the static capabilities correctly [microsoft/vscode-languageserver-node#713 (comment)](https://github.com/microsoft/vscode-languageserver-node/issues/713#issuecomment-754551117)

I believe pyright could fix this by adding a block to https://github.com/microsoft/pyright/blob/d22850b041edbc747ec043553a23bdbff55696d6/packages/pyright-internal/src/languageServerBase.ts#L726-L760

```js
workspace: {
    workspaceFolders: {
        supported: true,
        changeNotifications: false,
    }
}
```

(I'll try it out to confirm.) But they are actually interested in workspace folder change notifications so I think it makes sense for them to set that to `true`. They could gate it on whether the client says that it supports dynamic capability registration but at that point this should be solved in vscode-languageserver-node instead because all other language servers based on vscode-languageserver-node would need to do the same.

Sending `Ok(Null)` for registerClient is still a hack but I'm comfortable with the tradeoff for the sake of compatibility. I think this should definitely be fixed upstream though ultimately.

Comment (pascalkuthe) [reply helix-term/src/application.rs:964]: > ```js
> workspace: {
>     workspaceFolders: {
>         supported: true,
>         changeNotifications: false,
>     }
> }
> ```

I actually think the fix would be:

```
workspace: {
    workspaceFolders: {
        supported: true,
        changeNotifications: true,
    }
}
```

If I read https://github.com/microsoft/vscode-languageserver-node/commit/5bc82ac3c1c656aa70615c9e3e065fa04e41506e right it looks like `vscode-languageserver-node` only attemps dynamic registration if static registration has not already occured. So if  `changeNotifications` is `true` they should not send the problematic request

Comment (the-mikedavis) [reply helix-term/src/application.rs:964]: Oh good catch I think you're right. Let me give that a try 👍

Comment (the-mikedavis) [reply helix-term/src/application.rs:964]: Yep that does it! I'll submit that upstream

**Review by pascalkuthe — APPROVED** [review]
Even tough this turned out to be solvable upstream after all it's still good to adhere to the spec here and avoid accidently locking up servers 👍 LGTM

**Comment by the-mikedavis** [comment]
This change is still needed separately from the change upstream: pyright will lock up if we don't respond to the `workspace/configuration` request and this change will respond with an error (second `Err` branch), preventing the lock-up.

The first `Err` branch for sending an error for unhandled methods causes a separate problem with pyright where it will exit instead of locking up. That part will be fixed with the upstream PR. So if you're looking to use Helix with pyright 1.1.293 or above, you will need to wait on this PR and the one upstream in pyright. Pyright 1.1.292 should work with the current Helix master.

**Comment by pascalkuthe** [comment]
> This change is still needed separately from the change upstream: pyright will lock up if we don't respond to the `workspace/configuration` request and this change will respond with an error (second `Err` branch), preventing the lock-up.
> 
> The first `Err` branch for sending an error for unhandled methods causes a separate problem with pyright where it will exit instead of locking up. That part will be fixed with the upstream PR. So if you're looking to use Helix with pyright 1.1.293 or above, you will need to wait on this PR and the one upstream in pyright. Pyright 1.1.292 should work with the current Helix master.

Ah right I rember pyright was sending two separate invalid requests. Sorry I mixed that up!
