### PR TITLE
Show an error when formatter is not available

### LINKED ISSUE #6736: There should be an error when formating fails
### Summary

If I format a document that does not have a LSP installed for its language nothing happens

### Reproduction Steps

**I tried this:**
1. `:format`

**I expected this to happen:**
The editor tells me that their is no language server installed for this language and possibly shows me a guide to install a language server

**Instead, this happened:**
Nothing happend

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-04-13T10:38:25.338 helix_view::editor [ERROR] Failed to initialize the LSP for `source.python` { cannot find binary path }
```

</details>

### Platform

Linux

### Terminal Emulator

alacritty

### Helix Version

helix 23.03

### PR DESCRIPTION
**Pull request by doriath**
Fixes #6736.

Before when user run :fmt command, but no formatter was available, there was no feedback which was confusing to the users.

### CODE REVIEW

File: helix-term/src/commands/typed.rs [hunk 1]
```diff
@@ -459,10 +459,14 @@ fn format(
     if let Some(format) = doc.format() {
         let callback = make_format_callback(doc.id(), doc.version(), view.id, format, None);
         cx.jobs.callback(callback);
+    } else {
+        cx.editor
+            .set_error("Formater not available and no LSP has formatting capabilities");
```
Comment (the-mikedavis) [inline helix-term/src/commands/typed.rs:464]: For typable commands you can return an `Err` for the same effect as `cx.editor.set_error`:

```suggestion
        bail!("Formatter not available and no language server has formatting capabilities");
```

File: helix-term/tests/test/commands/write.rs
Comment (the-mikedavis) [inline helix-term/tests/test/commands/write.rs:1]: This file is only meant for tests against `:write` (and similar like `:x`). I would probably prefer just to drop the test for this PR since the functionality is so straightforward. (i.e. I would be very surprised to see a regression in this behavior in the future.)

File: helix-term/src/commands/typed.rs (hunk 1 above)
Comment (David-Else) [inline helix-term/src/commands/typed.rs:464]:
```suggestion
            .set_error("The formatter is not available, and no language server offers formatting capabilities");
```
Formatter is the correct spelling, and LSP is an acronym for Language Server Protocol, this refers to the language server itself. I see these terms seem to be used interchangeably in the documentation at the moment, so @the-mikedavis what do you think?

Comment (the-mikedavis) [reply helix-term/src/commands/typed.rs:464]: Yeah good point, using "LSP" to mean "language server" is a minor nit of mine. I'll push a change to eliminate the improper "LSP" usage.

Comment (doriath) [reply helix-term/src/commands/typed.rs]: I didn't know that I can also just return the error, thank you for this suggestion!

File: helix-term/tests/test/commands/write.rs
Comment (doriath) [reply helix-term/tests/test/commands/write.rs:1]: Ah, that makes sense, thank you. Dropping the test as suggested. I also tested the behavior locally to verify that indeed we show the error message.

Writing the test was a good excersice for me to learn a little bit more about the codebase

File: helix-term/src/commands/typed.rs (hunk 1 above)
Comment (doriath) [reply helix-term/src/commands/typed.rs]: I actually like `language server` (I think avoiding acronyms where possible is a good rule of thumb for users), so updated the PR to include the new wording of the error.

Thank you for the fixes in the general wording of the error.
