### PR TITLE
autoresize terminal in compositor render

### LINKED ISSUE #22: index out of bounds on Windows
when I run the command `hx` (v0.0.6 binary from the release page) on Windows 10 it panics immediately with

```txt
thread 'main' panicked at 'index out of bounds: the len is 3451 but the index is 3451', helix-tui\src\buffer.rs:185:14
```

I'm using Windows Terminal, and the len changes depending on the terminal size.

### PR DESCRIPTION
**Pull request by janhrastnik**
fixes #22

### CODE REVIEW

File: helix-term/src/compositor.rs [hunk 1]
```diff
@@ -122,7 +122,9 @@ impl Compositor {
     }
 
     pub fn render(&mut self, cx: &mut Context) {
+        self.terminal.autoresize().unwrap();
```
Comment (pickfire) [inline helix-term/src/compositor.rs:125]: Shouldn't it `expect` rather than unwrap if it fails to get size?

File: helix-tui/src/terminal.rs [hunk 2]
```diff
@@ -138,11 +138,9 @@ where
...
-        if self.viewport.resize_behavior == ResizeBehavior::Auto {
-            let size = self.size()?;
-            if size != self.viewport.area {
-                self.resize(size)?;
-            }
+        let size = self.size()?;
+        if size != self.viewport.area {
+            self.resize(size)?;
         };
         Ok(())
```
Comment (pickfire) [inline helix-tui/src/terminal.rs:145]: Why not return `size` here so we don't need to `self.size()` again in compositor?
