### PR TITLE
Launch with defaults upon invalid config/theme

### LINKED ISSUE #670: Launch with defaults instead of not launching upon invalid config/theme
If the user tries to start the editor and there is a problem with their config, I think the editor should start with the default config instead of failing to launch. That way, they don't have to use a different editor to fix the problematic config. Likewise, launch with the default theme if their configured theme is problematic. Of course, the editor should issue a warning on startup if either of these situations occur. Also, if the user tries to switch to a problematic theme with `:theme`, inform them and continue with the current theme instead of panicking.

### PR DESCRIPTION
**Pull request by Omnikar**
Resolves #670.

* Startup message if there is a problematic config, then launch with default config.
* Statusline error if trying to switch to an invalid theme, and reject the switch. This results in using the default theme if an invalid theme is set in `config.toml`.

### CODE REVIEW

File: helix-term/src/main.rs [hunk 1]
```diff
@@ -91,7 +91,16 @@ FLAGS:
     }
 
     let config = match std::fs::read_to_string(conf_dir.join("config.toml")) {
-        Ok(config) => merge_keys(toml::from_str(&config)?),
+        Ok(config) => toml::from_str(&config)
```
Comment (sudormrfbin) [inline helix-term/src/main.rs:94]: Right now unknown fields are deserialized into the config, which can allow misspelled config keys to fail silently (eg. `line-numbet = "relative"`). Serde's [`deny_unknown_fields`](https://serde.rs/container-attrs.html#deny_unknown_fields) can come handy here.

**Review by sudormrfbin — APPROVED** [review]

File: helix-term/src/config.rs [hunk 2]
```diff
@@ -3,6 +3,7 @@ use serde::Deserialize;
 use crate::keymap::Keymaps;
 
 #[derive(Debug, Default, Clone, PartialEq, Deserialize)]
+#[serde(deny_unknown_fields)]
```
Comment (archseer) [inline helix-term/src/config.rs:6]: You probably want this on the editor config too: https://github.com/helix-editor/helix/blob/2c1313c0648977540c395de584b4293c1909cbf7/helix-view/src/editor.rs#L38

**Review by archseer — APPROVED** [review]
