### PR TITLE
Fix writing hardlinks

### LINKED ISSUE #11279: Editing file breaks hard link
### Summary

After saving the file, the hard link would be broken.
If it is working as intended, is there an option to disable this feature?

### Reproduction Steps

 

I tried this:

1. `touch a`
2. `ln a b`
3. `hx b` and insert `test`, and save by `:x`
4. `cat a`

I expected this to happen:
`cat a` outputs `test`.
Instead, this happened:
File `a` remains empty, and the hard link between `a` and `b` was broken.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2024-07-23T02:10:03.063 globset [DEBUG] glob converted to regex: Glob { glob: "*/Dockerfile.*", re: "(?-u)^.*/Dockerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('D'), Literal('o'), Literal('c'), Literal('k'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-07-23T02:10:03.064 globset [DEBUG] glob converted to regex: Glob { glob: "*/dockerfile.*", re: "(?-u)^.*/dockerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('d'), Literal('o'), Literal('c'), Literal('k'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-07-23T02:10:03.064 globset [DEBUG] glob converted to regex: Glob { glob: "*/Containerfile.*", re: "(?-u)^.*/Containerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('C'), Literal('o'), Literal('n'), Literal('t'), Literal('a'), Literal('i'), Literal('n'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-07-23T02:10:03.064 globset [DEBUG] glob converted to regex: Glob { glob: "*/containerfile.*", re: "(?-u)^.*/containerfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('c'), Literal('o'), Literal('n'), Literal('t'), Literal('a'), Literal('i'), Literal('n'), Literal('e'), Literal('r'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-07-23T02:10:03.064 globset [DEBUG] glob converted to regex: Glob { glob: "*/.*ignore", re: "(?-u)^.*/\\..*ignore$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('.'), ZeroOrMore, Literal('i'), Literal('g'), Literal('n'), Literal('o'), Literal('r'), Literal('e')]) }
2024-07-23T02:10:03.064 globset [DEBUG] glob converted to regex: Glob { glob: "*/BUILD.*", re: "(?-u)^.*/BUILD\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('B'), Literal('U'), Literal('I'), Literal('L'), Literal('D'), Literal('.'), ZeroOrMore]) }
2024-07-23T02:10:03.064 globset [DEBUG] glob converted to regex: Glob { glob: "*/.env.*", re: "(?-u)^.*/\\.env\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('.'), Literal('e'), Literal('n'), Literal('v'), Literal('.'), ZeroOrMore]) }
2024-07-23T02:10:03.064 globset [DEBUG] glob converted to regex: Glob { glob: "*/.envrc.*", re: "(?-u)^.*/\\.envrc\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('.'), Literal('e'), Literal('n'), Literal('v'), Literal('r'), Literal('c'), Literal('.'), ZeroOrMore]) }
2024-07-23T02:10:03.064 globset [DEBUG] glob converted to regex: Glob { glob: "*/conf/*/*.{inc,conf}", re: "(?-u)^.*/conf/.*/.*\\.(?:conf|inc)$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('c'), Literal('o'), Literal('n'), Literal('f'), Literal('/'), ZeroOrMore, Literal('/'), ZeroOrMore, Literal('.'), Alternates([Tokens([Literal('c'), Literal('o'), Literal('n'), Literal('f')]), Tokens([Literal('i'), Literal('n'), Literal('c')])])]) }
2024-07-23T02:10:03.064 globset [DEBUG] glob converted to regex: Glob { glob: "*/Jenkinsfile.*", re: "(?-u)^.*/Jenkinsfile\\..*$", opts: GlobOptions { case_insensitive: false, literal_separator: false, backslash_escape: true, empty_alternates: false }, tokens: Tokens([ZeroOrMore, Literal('/'), Literal('J'), Literal('e'), Literal('n'), Literal('k'), Literal('i'), Literal('n'), Literal('s'), Literal('f'), Literal('i'), Literal('l'), Literal('e'), Literal('.'), ZeroOrMore]) }
2024-07-23T02:10:03.064 globset [DEBUG] built glob set; 1 literals, 0 basenames, 0 extensions, 0 prefixes, 127 suffixes, 9 required extensions, 10 regexes
2024-07-23T02:10:03.077 helix_view::clipboard [DEBUG] Using pbcopy+pbpaste to interact with the system clipboard
2024-07-23T02:10:03.085 helix_vcs [DEBUG] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/tmp",
        },
    ),
}
2024-07-23T02:10:03.085 helix_vcs [DEBUG] failed to open diff base for /tmp/b
2024-07-23T02:10:03.085 helix_vcs [DEBUG] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepository {
            path: "/tmp",
        },
    ),
}
2024-07-23T02:10:03.085 helix_vcs [DEBUG] failed to obtain current head name for /tmp/b
2024-07-23T02:10:03.086 helix_view::editor [DEBUG] editor status: Loaded 1 file.
2024-07-23T02:10:03.090 helix_tui::backend::crossterm [DEBUG] The keyboard enhancement protocol is supported in this terminal (checked in 1.891292ms)
2024-07-23T02:10:03.091 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:03.329 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T02:10:03.757 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:03.882 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:04.007 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T02:10:04.009 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:04.518 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:04.640 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:04.705 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:04.828 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:04.875 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:04.998 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:05.088 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:05.211 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:05.340 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2024-07-23T02:10:05.341 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T02:10:05.380 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 1
2024-07-23T02:10:05.631 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T02:10:05.915 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 1
2024-07-23T02:10:06.168 helix_term::application [DEBUG] received editor event: IdleTimer
2024-07-23T02:10:06.174 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 1
2024-07-23T02:10:07.651 helix_view::document [DEBUG] submitting save of doc 'Some("/tmp/b")'
2024-07-23T02:10:07.651 helix_term::job [DEBUG] waiting on jobs...
2024-07-23T02:10:07.660 helix_lsp::file_event [DEBUG] Received file event for "/tmp/b"
2024-07-23T02:10:07.660 helix_view::document [DEBUG] doc 1 revision updated 0 -> 2
2024-07-23T02:10:07.660 helix_term::commands::typed [DEBUG] quitting...
2024-07-23T02:10:07.660 helix_view::document [DEBUG] id 1 modified - last saved: 2, current: 2
2024-07-23T02:10:07.660 helix_term::job [DEBUG] waiting on jobs...
2024-07-23T02:10:07.661 helix_term::job [DEBUG] waiting on jobs...

```

</details>

### Platform

macOS

### Terminal Emulator

iterm2 3.5.3

### Installation Method

brew

### Helix Version

helix 24.7 (079f5442)

### PR DESCRIPTION
**Pull request by kirawi**
Resolves #11279

### CODE REVIEW

File: helix-view/src/document.rs [hunk 1]
```diff
@@ -933,7 +933,10 @@ impl Document {
                     "Path is read only"
                 ));
             }
-            let backup = if path.exists() {
+
+            // Effectively ignores hardlink check if the metadata cant be read (e.g. on certain Windows configurations)
+            let is_hardlink = helix_stdx::get_hardlink_count(&write_path).unwrap_or(1) > 1;
+            let backup = if path.exists() && !is_hardlink {
```
Comment (pascalkuthe) [inline helix-view/src/document.rs:939]: We should still be making a backup for handlinks (to prevent file loss) but it should be done by copying the file instead of moving (equivalent of bufcopy)

File: helix-stdx/src/lib.rs [hunk 2]
```diff
@@ -1,4 +1,31 @@
+use std::path::Path;
+
 pub mod env;
 pub mod faccess;
 pub mod path;
 pub mod rope;
+
+#[cfg(unix)]
+pub fn get_hardlink_count(p: &Path) -> std::io::Result<u64> {
```
Comment (pascalkuthe) [inline helix-stdx/src/lib.rs:9]: I think this fits in with the faccess module

File: helix-stdx/src/lib.rs [hunk 3]
```diff
@@ -1,4 +1,31 @@
...
+
+#[cfg(windows)]
+pub fn get_hardlink_count(p: &Path) -> std::io::Result<u64> {
+    use std::os::windows::io::IntoRawHandle;
+    use windows_sys::Win32::Storage::FileSystem::{
+        GetFileInformationByHandle, BY_HANDLE_FILE_INFORMATION,
+    };
+
+    let file = std::fs::File::open(p)?;
+    let handle = file.into_raw_handle() as isize;
```
Comment (pascalkuthe) [inline helix-stdx/src/lib.rs:23]: Thus leaks the file handle as it never gets closed.

You need to use as_raw_handle instead:

 https://doc.rust-lang.org/std/os/windows/io/trait.AsRawHandle.html#tymethod.as_raw_handle

**Comment by pascalkuthe** [comment]
implementation looks good now, there are some build failures in the integration tests tough. Once the tests are ready and passing this should be good to go. Thanks for implementing this. It's good to be more robust here!

**Review by pascalkuthe — APPROVED** [review]
thanks!

**Review by the-mikedavis — APPROVED** [review]
