### PR TITLE
Panics when resizing

### LINKED ISSUE #1403: Rust panics when terminal is too small
When the terminal gets too small to fit some widget, helix crashes.

### Reproduction steps

* Open helix in a resizable terminal. 
* Open the file picker (`<space> f`)
* Resize the window to about 4 rows or 4 cols
* => crash

Stumbled upon this bug when using hx in a drop-down terminal, which apparently resizes the window when hidden.

### Environment

- Platform: Linux (tested on `gnome-terminal`)
- Helix version: current master branch

### PR DESCRIPTION
**Pull request by k2d222**
FIxes #1403

The editor crashes when the window is very small. Two reasons:
 - some widgets have a minimum size (e.g. boxes) -> integer calculations may overflow.  
 - buffer panics when accessed out-of-range

* Changed `Buffer::get` and `Buffer::get_mut` to return an Option, like `std::Vec`
* Implemented traits `Index` and `IndexMut` for Buffer with a pair of coordinates, i.e. `buf[(x, y)]`
* Replaced calls to `Buffer::get` and `Buffer.get_mut` with the Index, which is known to panic. Makes code clearer with the intent not to perform bounds checks.
* Fixed a few divisions by zero and integer substraction underflows.

### CODE REVIEW

File: helix-term/src/ui/picker.rs [hunk 1]
```diff
@@ -505,15 +505,15 @@ impl<T: 'static> Component for Picker<T> {
         let selected = cx.editor.theme.get("ui.text.focus");
 
         let rows = inner.height;
-        let offset = self.cursor / (rows as usize) * (rows as usize);
+        let offset = self.cursor / std::cmp::max(1, rows as usize) * (rows as usize);
```
Comment (archseer) [inline helix-term/src/ui/picker.rs:508]:
```suggestion
        let offset = self.cursor / std::cmp::max((1, rows as usize) * (rows as usize));
```

If rows is zero, `1 * 0` would still end up being a division by zero.

File: helix-tui/src/buffer.rs [hunk 2]
```diff
@@ -162,15 +162,13 @@ impl Buffer {
...
+        self.index_of_opt(x, y).map(|i| &self.content[i])
     }
 
     /// Returns a mutable reference to Cell at the given coordinates
-    pub fn get_mut(&mut self, x: u16, y: u16) -> &mut Cell {
-        let i = self.index_of(x, y);
-        &mut self.content[i]
+    pub fn get_mut(&mut self, x: u16, y: u16) -> Option<&mut Cell> {
+        self.index_of_opt(x, y).map(|i| &mut self.content[i])
     }
```
Comment (archseer) [inline helix-tui/src/buffer.rs:172]: I'd rather see you use the original method and then use `self.content.get(i)`. That way you're not doing bounds checks twice (once in index_of_opt, once internally in `self.content[]`).

File: helix-tui/src/buffer.rs [hunk 3]
```diff
@@ -278,6 +290,11 @@ impl Buffer {
     where
         S: AsRef<str>,
     {
+        // prevent panic if out of range
+        if self.index_of_opt(x, y).is_none() || width == 0 {
+            return (x, y);
+        }
```
Comment (archseer) [inline helix-tui/src/buffer.rs:296]: This is now doing the math twice, once in `index_of_opt` -> `index_of`, then once on L298.

Let's extract an `in_bounds(x, y) -> bool` method and use that here.

**Review by archseer — CHANGES_REQUESTED** [review]

File: helix-term/src/ui/picker.rs (hunk 1 above)
Comment (kirawi) [reply helix-term/src/ui/picker.rs:508]: I think that suggestion is wrong, it should be `std::cmp::max(1, (rows as usize) * (rows as usize))`

File: helix-tui/src/buffer.rs (hunk 2 above)
Comment (k2d222) [reply helix-tui/src/buffer.rs:172]: I don't think that would work. There is no way to avoid bounds checks on a `Vec` (to my knowledge) and the check performed by `index_of` is actually different: 
Say the buffer is of size (2, 2), then asking for out-of-bounds cell at (2, 0) will compute index=2, which is in bounds of vec but correspond to incorrect cell at (0,1).

(We could accept that and tolerate that buffer can return bad cells when out of bounds, but I don't think optimizing performance for this kind of double checks is worth it)

Comment (archseer) [reply helix-tui/src/buffer.rs]: Well there's `unsafe get_unchecked()` if you previously validate the index.

We inherited the `Buffer` implementation from https://github.com/fdehau/tui-rs/ and I think this explains why it panics and only uses a `debug_assert!` rather than `Option`: `Buffer::get_mut` is a hot path that gets called _a lot_ on every render.  On frequent re-renders the slowdown will be noticeable.

Comment (k2d222) [reply helix-tui/src/buffer.rs]: Do you want me to use `get_unchecked` or do you overall disagree with the proposed solution?

I think it's best to have safe functions in `Buffer` at the cost of (what I think to be) unnoticeable performance gains. I could be wrong, but I think the terminal emulator is more responsible of refresh latency than the editor.

Also, *'premature optimization is the root of all evil'* :) Helix is in alpha state, it should be stable and feature-full before being optimized for speed / latency.

Comment (archseer) [reply helix-tui/src/buffer.rs]: Looking at this again, I think the change is OK since now in most cases we use `[]` instead of `get_mut` anyway (like `set_stringn`).
