### PR TITLE
Use terminfo to reset terminal cursor style

### LINKED ISSUE #2684: Helix changes terminal cursor style
### Summary

After quitting helix my terminal cursor changes from `Beam` (my default) to `Block` (helix default). I had the same issue of vim but i fixed it by adding `set guicursor=` to my `.vimrc`. However, i could not find a way to do that in helix.

### Reproduction Steps

1. Open helix
2. Exit
3. Cursor style has changed

### Helix log

_No response_

### Platform

Linux

### Terminal Emulator

Alacritty

### Helix Version

helix 22.05

### PR DESCRIPTION
**Pull request by rmehri01**
Uses the `cnorm` capability from `terminfo` if available to reset the terminal cursor style. I tested this with `xterm` and it seems to fix the issue with making the cursor blink like in #3741.

Closes #2684

### CODE REVIEW

File: helix-tui/src/backend/crossterm.rs [hunk 1]
```diff
@@ -154,7 +159,12 @@ where
 
     fn restore(&mut self, config: Config) -> io::Result<()> {
         // reset cursor shape
-        write!(self.buffer, "\x1B[0 q")?;
+        let cursor_normal = self
+            .capabilities
+            .cursor_normal
+            .as_deref()
+            .unwrap_or("\x1B[0 q");
+        write!(self.buffer, "{cursor_normal}")?;
```
Comment (the-mikedavis) [inline helix-tui/src/backend/crossterm.rs:167]:
```suggestion
        self.buffer.write_all(cursor_normal.as_bytes())?;
```

here the formatting is just overhead, we could convert to a byte slice instead directly and avoid all that

File: helix-tui/src/backend/crossterm.rs [hunk 2]
```diff
@@ -32,10 +32,12 @@ fn vte_version() -> Option<usize> {
 }
 
 /// Describes terminal capabilities like extended underline, truecolor, etc.
-#[derive(Copy, Clone, Debug, Default)]
+#[derive(Clone, Debug, Default)]
 struct Capabilities {
     /// Support for undercurled, underdashed, etc.
     has_extended_underlines: bool,
+    /// Support for resetting the cursor style back to normal.
+    cursor_normal: Option<String>,
```
Comment (the-mikedavis) [inline helix-tui/src/backend/crossterm.rs:40]:
```suggestion
    reset_cursor_command: Option<String>,
```

Comment (the-mikedavis) [reply helix-tui/src/backend/crossterm.rs:40]: This could just be a `String` and we would default to `\x1B[0 q` in `from_env_or_default`

**Review by the-mikedavis — COMMENTED** [review]
Just some minor style nits

**Review by the-mikedavis — APPROVED** [review]

File: helix-tui/src/backend/crossterm.rs [hunk 3]
```diff
@@ -54,6 +56,10 @@ impl Capabilities {
                     || t.extended_cap("Su").is_some()
                     || vte_version() >= Some(5102)
                     || matches!(term_program().as_deref(), Some("WezTerm")),
+                reset_cursor_command: t
+                    .utf8_string_cap(termini::StringCapability::CursorNormal)
+                    .unwrap_or("\x1B[0 q")
+                    .to_string(),
```
Comment (pascalkuthe) [inline helix-tui/src/backend/crossterm.rs:62]: On unic thus seems fine but does this work on windows?

Comment (rmehri01) [reply helix-tui/src/backend/crossterm.rs]: Ah good catch, I just tried it out and it doesn't work on windows since the capability will be set to an empty string instead.

File: helix-tui/src/backend/crossterm.rs [hunk 4]
```diff
@@ -31,11 +31,22 @@ fn vte_version() -> Option<usize> {
     std::env::var("VTE_VERSION").ok()?.parse().ok()
 }
 
+#[derive(Clone, Debug)]
+struct ResetCursorCommand(String);
```
Comment (the-mikedavis) [inline helix-tui/src/backend/crossterm.rs:35]: The newtype wrapper for the string here seems unnecessary to me. It's fine just to default with `unwrap_or`/`unwrap_or_else` rather than `unwrap_or_default`

Comment (rmehri01) [reply helix-tui/src/backend/crossterm.rs:35]: I added this since we also want the default `"\x1B[0 q"` to be used when `terminfo` isn't available, for example on Windows, or else it just defaults to an empty string. Or should I just explicitly make the struct in the other case instead of keeping the `Capabilities::default()`?

Comment (the-mikedavis) [reply helix-tui/src/backend/crossterm.rs:35]: Ah I see. Let's define `impl Default for Capabilities` instead so Windows can keep calling `Capabilities::default`

**Review by the-mikedavis — DISMISSED** [review]

File: helix-tui/src/backend/crossterm.rs [hunk 5]
```diff
@@ -32,10 +32,21 @@ fn vte_version() -> Option<usize> {
...
     /// Support for undercurled, underdashed, etc.
     has_extended_underlines: bool,
+    /// Support for resetting the cursor style back to normal.
+    reset_cursor_command: String,
+}
+
+impl Default for Capabilities {
+    fn default() -> Self {
+        Self {
+            has_extended_underlines: bool::default(),
```
Comment (pascalkuthe) [inline helix-tui/src/backend/crossterm.rs:46]:
```suggestion
            has_extended_underlines: false,
```

**Review by pascalkuthe — CHANGES_REQUESTED** [review]
Small style nit: I dislike using default instead of false. Apart from that this LGTM

**Review by pascalkuthe — APPROVED** [review]

**Review by the-mikedavis — APPROVED** [review]

**Comment by kladd** [comment]
The terminfos of the terminals on my machine have `cnorm` as `\E[?12l\E25h`, "Stop blinking cursor (AT&T 610)" and "Show cursor (DECTCEM), VT220", which has been my experience since this change.

It seems like there's some adoption of `DECSCUSR 0`/ `\E[0 q` resetting the user default cursor though. Alacritty and the default terminal on macOS seem to—and Windows I guess https://github.com/microsoft/terminal/pull/7379 (haven't tried).
