### PR TITLE
Handle BrokenPipe when piping hx --health through head

### LINKED ISSUE #1841: panic when piping `hx --health` through `head`
### Summary

Piping `hx --health` through `head` gives a panic. I'm not sure if it's something to do with my terminal (kitty). Piping through `less` works perfectly, even with colors.

### Reproduction Steps

[asciicast](https://asciinema.org/a/sZaajKhddtmyh5EEBsIxUxmFU)

```
$ hx --health | head -n 10
```

### Helix log

N/A: no log lines were produced.

<details><summary>But here's the backtrace...</summary>

```
thread 'main' panicked at 'failed printing to stdout: Broken pipe (os error 32)', library/std/src/io/stdio.rs:1187:9
stack backtrace:
   0:     0x560d47de313c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3e2b509ce2ce6007
   1:     0x560d4773a1ac - core::fmt::write::h753c7571fa063ecb
   2:     0x560d47ddb565 - std::io::Write::write_fmt::h2815c0519c99ba09
   3:     0x560d47de62e5 - std::panicking::default_hook::{{closure}}::h78d3e6cf97fc623d
   4:     0x560d47de5f63 - std::panicking::default_hook::hda898f8d3ad1a5ae
   5:     0x560d47de696c - std::panicking::rust_panic_with_hook::h1a5ea2d6c23051aa
   6:     0x560d47de665a - std::panicking::begin_panic_handler::{{closure}}::h07f549390938b73f
   7:     0x560d47de3664 - std::sys_common::backtrace::__rust_end_short_backtrace::h5ec3758a92cfb00d
   8:     0x560d47de63bd - rust_begin_unwind
   9:     0x560d476c1d01 - core::panicking::panic_fmt::h3a79a6a99affe1d5
  10:     0x560d47dda7d1 - std::io::stdio::_print::h4dabb72d0b79d2de
  11:     0x560d47bba8d5 - helix_term::health::languages_all::h64ed386eb51c8a24
  12:     0x560d47c84923 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h45a31bbdd9e955af
  13:     0x560d47c543ce - tokio::park::thread::CachedParkThread::block_on::h8bfc4daa5e5d5900
  14:     0x560d47cbc559 - tokio::runtime::thread_pool::ThreadPool::block_on::hfbbc83b50318e9de
  15:     0x560d47c81e83 - tokio::runtime::Runtime::block_on::hdab0bdfd50a45238
  16:     0x560d47c52eaa - hx::main::h7b50b857af503774
  17:     0x560d47c55fe3 - std::sys_common::backtrace::__rust_begin_short_backtrace::ha19c1e7ad046c834
  18:     0x560d47c68c8d - std::rt::lang_start::{{closure}}::ha7afa477cb4d71de
  19:     0x560d47de279e - std::rt::lang_start_internal::h52e73755f77c7dd9
  20:     0x560d47c562e2 - main
  21:     0x7fb18ef68790 - __libc_start_main
  22:     0x560d476f041a - _start
  23:                0x0 - <unknown>
```

</details>

### Platform

Linux (NixOS 21.11)

### Terminal Emulator

kitty 0.23.1

### Helix Version

master at 533cca7195b5ab36e0a1fa4863d00f6c11cb41b9

### PR DESCRIPTION
**Pull request by npate012**
Functions in health.rs now return std:io::Result<()>. All instances of println!
and eprintln! have been replaced with writeln!. This allows detection of errors
while printing messages and errors. BrokenPipe errors are ignored. All other
errors are returned.

Fixes #1841

Signed-off-by: Nirmal Patel <npate012@gmail.com>

### CODE REVIEW

**Review by dead10ck — APPROVED** [review]
Looks good to me, thanks!

File: helix-term/src/health.rs [hunk 1]
```diff
@@ -168,9 +204,13 @@ pub fn language(lang_str: String) {
...
                 let suggestions = suggestions.join(", ");
-                println!("Did you mean one of these: {} ?", suggestions.yellow());
+                writeln!(
+                    stdout,
+                    "Did you mean one of these: {} ?",
+                    suggestions.yellow()
+                )?;
             }
-            return;
+            return Err(std::io::Error::new(std::io::ErrorKind::Other, msg));
```
Comment (sudormrfbin) [inline helix-term/src/health.rs:213]: We already print `msg` in red, having it return as the error string prints it twice

File: helix-term/src/main.rs [hunk 2]
```diff
@@ -89,14 +90,26 @@ FLAGS:
...
+            let io_result = helix_term::health::general()
+                .and_then(|_| writeln!(std::io::stdout().lock()))
+                .and_then(|_| helix_term::health::languages_all());
+
+            if let Err(err) = io_result {
+                if err.kind() != std::io::ErrorKind::BrokenPipe {
+                    return Err(err.into());
+                }
+            }
         }
```
Comment (sudormrfbin) [inline helix-term/src/main.rs:113]: I think this can be extracted to a function like `print_health(lang: Option<String>) -> io::Result<()>` where we can use `?` abundantly and then handle `BrokenPipe` once in the calling code.

File: helix-term/src/health.rs (hunk 1 above)
Comment (npate012) [reply helix-term/src/health.rs]: Thank you. I have removed the line that returns the error. I am returning Ok now. The error is not printing twice anymore.

File: helix-term/src/main.rs (hunk 2 above)
Comment (npate012) [reply helix-term/src/main.rs]: I have created print_health function in health.rs. Now BrokenPipe is only handled once in main.rs

**Review by sudormrfbin — APPROVED** [review]
There was a conflict, fixed it; thanks @npate012 !
