### PR TITLE
mouse operations respect scrolloff

### LINKED ISSUE #5254: Mouse actions does not trigger scrolloff.
### Summary

mouse clicking or dragging on the edge of the text editor does not move the cursor base on the scrolloff value. 

### Reproduction Steps

 

I tried this:

> click on the edge of line where there is text off screen.

I expected this to happen:

> Move the cursor base on the scrolloff value to reveal more text.

Instead, this happened:

> The cursor stay at the edge of editor.

### Helix log

_No response_

### Platform

macOS

### Terminal Emulator

wezterm 20221119-145034-49b9839f

### Helix Version

helix 22.12

### PR DESCRIPTION
**Pull request by hunterliao29**
close #5254

### CODE REVIEW

File: helix-term/src/ui/editor.rs [hunk 1]
```diff
@@ -1180,19 +1181,21 @@ impl EditorView {
...
 
             MouseEventKind::Drag(MouseButton::Left) => {
-                let (view, doc) = current!(cxt.editor);
+                let editor = &mut cxt.editor;
 
-                let pos = match view.pos_at_screen_coords(doc, row, column) {
-                    Some(pos) => pos,
-                    None => return EventResult::Ignored(None),
-                };
+                if let Some((pos, view_id)) = pos_and_view(editor, row, column) {
```
Comment (the-mikedavis) [inline helix-term/src/ui/editor.rs:1186]: Why the change from `pos_at_screen_coords` on the current view to `pos_and_view` here? Dragging should only affect the currently focused view: with this change, if you start a drag on a focused view and then drag across an unfocused view, you modify the selection on the unfocused view but you can't see the selection because selections are hidden on unfocused views.

File: helix-term/src/ui/editor.rs [hunk 2]
```diff
@@ -1213,6 +1216,7 @@ impl EditorView {
                 commands::scroll(cxt, offset, direction);
 
                 cxt.editor.tree.focus = current_view;
+                cxt.editor.ensure_cursor_in_view(current_view);
```
Comment (the-mikedavis) [inline helix-term/src/ui/editor.rs:1219]: Is this change necessary? `commands::scroll` already respects scrolloff

Comment (hunterliao29) [reply helix-term/src/ui/editor.rs:1219]: Currently the `commands::scroll` does respects scrolloff. However, if the file like this:

```
----------------------------------------------------------------| cursor here
longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglong[]onglonglonglong
longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong
longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong
longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong
short or empty
short or empty
short or empty
short or empty
short or empty
```

after scroll down

```

longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglong[]onglonglonglong
longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong
longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong
longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong
short or empty
short or empty
--------------| cursor here
short or empt[]
short or empty
short or empty
```

the cursor will not be visible

File: helix-term/src/ui/editor.rs (hunk 1 above)
Comment (hunterliao29) [reply helix-term/src/ui/editor.rs:1186]: I did not realize that there are different between `pos_at_screen_coords`  and  `pos_and_view` beside beside `pos_and_view` also return view.id. I will change it.

**Review by the-mikedavis — APPROVED** [review]
