### PR TITLE
Use gix pipeline filter instead of manual crlf implementation

### LINKED ISSUE #8145: Git gutter shows everything changed with automatic end-of-line conversion (.gitattributes contains * text=auto)
### Summary

[Git has a feature to check out text files with native line endings](https://www.git-scm.com/docs/gitattributes#_end_of_line_conversion), something that is often used for crossplatform development.
When viewing a file on windows which has been converted to crlf this way, the git gutter shows everything changed:

image

However, when setting `:line-ending lf` it doesn't anymore:

image

This is no workaround, because this actually changed the line endings of the file to lf, where crlf is desired.
Note that `git diff` works correctly, and does not report any changes.

### Reproduction Steps

_No response_

### Helix log

_No response_

### Platform

Windows

### Terminal Emulator

wezterm 20230828-220414-99c96139

### Helix Version

helix 23.05 (19b73bc7)

### PR DESCRIPTION
**Pull request by ShoyuVanilla**
Fixes #8145

### CODE REVIEW

File: helix-vcs/src/git.rs [hunk 1]
```diff
@@ -76,29 +78,20 @@ impl DiffProvider for Git {
...
-            }
-            data = normalized_file
+        let data = file_object.detach().data;
+        // Get the actual data that git would make out of the git object.
+        // This will apply the user's git config or attributes like crlf conversions.
+        if let Some(work_dir) = repo.work_dir() {
+            let rela_path = file.strip_prefix(work_dir)?.to_string_lossy();
+            let (mut pipeline, _) = repo.filter_pipeline(None)?;
+            let mut worktree_outcome =
+                pipeline.convert_to_worktree(&data, rela_path.as_ref().into(), Delay::Forbid)?;
```
Comment (pascalkuthe) [inline helix-vcs/src/git.rs:88]: @Byron how does this handle encoding? Git stores everything as utf-8 internally IIRC and only converts back on checkout.

I guess that this function would do that? Could we instead checkout utf-8 somehow. (My memory is very cloudy here so I may be missremebering)

File: Cargo.lock [hunk 2]
```diff
@@ -448,6 +448,18 @@ dependencies = [
  "winapi",
 ]
 
+[[package]]
+name = "filetime"
```
Comment (archseer) [inline Cargo.lock:452]: A lot of new dependencies :/

Comment (ShoyuVanilla) [reply Cargo.lock:452]: It comes from new feature flag `gix = { features = ["attributes"], .. }`, which is needed for https://docs.rs/gix/0.58.0/gix/struct.Repository.html#method.filter_pipeline 😢

File: helix-vcs/src/git.rs [hunk 3]
```diff
@@ -76,29 +78,21 @@ impl DiffProvider for Git {
...
-                normalized_file.push(byte)
-            }
-            data = normalized_file
+        let data = file_object.detach().data;
+        // Get the actual data that git would make out of the git object.
+        // This will apply the user's git config or attributes like crlf conversions.
+        if let Some(work_dir) = repo.work_dir() {
+            let rela_path = file.strip_prefix(work_dir)?;
+            let rela_path = gix::path::try_into_bstr(rela_path)?;
+            let (mut pipeline, _) = repo.filter_pipeline(None)?;
```
Comment (Byron) [inline helix-vcs/src/git.rs:87]: Just as a note: It's a bit sad that the filter pipeline can't be reused under the circumstances. if this should ever be an issue that can be achieved by dropping down to the [internal plumbing types](https://github.com/Byron/gitoxide/blob/17638628586900d43d730e6ed2a0862d8e408f29/gix/src/filter.rs#L70-L72).

However, I wouldn't go there as this will seriously complicate the code - I just wanted you to know that you can to shave off some cycles.

File: helix-vcs/src/git.rs (hunk 1 above)
Comment (Byron) [reply helix-vcs/src/git.rs]: That's not the case, but it's true that Git has an 'internal' form that it wants to store in the object database. This is merely a form that passed through the filter pipeline though, which on Unix is most often a no-op.

It's true though that this method takes care of transforming `data` which is supposed to be directly from the object database and turn it into what would be checked out, applying all necessary transformations.

**Review by Byron — APPROVED** [review]
I took my time to study the PR and believe that't the way to do it! Good work :)!

Additionally I was thinking that using the worktree-version as base for a diff is also exactly would should be done given how the user opens and edits files in the worktree.

For posterity, let me mention that by now there is also the [`repo.diff_recource_cache()`](https://github.com/Byron/gitoxide/blob/17638628586900d43d730e6ed2a0862d8e408f29/gix/src/filter.rs#L70-L72) method which allows to perform diffs just like diff does which, you guessed it, may apply even more transformations 😁. Doing so would be wrong here, but if there ever is a 'show me the git diff' function in `helix`, that would be the way to do it (*and that's particularly interesting if the user configured diff-filters to turn binary files into something diffable*).

File: Cargo.lock (hunk 2 above)
Comment (Byron) [reply Cargo.lock:452]: I reviewed how this dependency is used and it seems 'convenience' is the answer. No feature is used that wouldn't be covered by the doing what the crate does.

I added a task to [the `helix` tracking issue](https://github.com/Byron/gitoxide/issues/637) to represent that possibility, and help would definitely be welcome.

**Review by pascalkuthe — APPROVED** [review]

**Review by the-mikedavis — APPROVED** [review]
Thanks!

This fixes the diff gutter for me in a repo where I use [`git-crypt`](https://github.com/AGWA/git-crypt) :rocket:
