### PR TITLE
Make shell_impl concurrent

### LINKED ISSUE #3127: :pipe hangs when piping a large file through sed
### Summary

Helix freezes and becomes unresponsive when piping a large (~7600 lines) file into `sed`. Piping the same file into `sed` outside of helix doesn't produce the same behavior, and helix seems to handle piping smaller files just fine. Piping into other commands also doesn't seem to cause the same issue though I didn't try very many. 

### Reproduction Steps

 

I tried this:

1. `hx frankenstein.txt` (from [here](https://raw.githubusercontent.com/asweigart/codebreaker/master/frankenstein.txt))
2. `%`
3. `|sed s/l/w/g`

I expected this to happen:
The command to execute and all of the 'l' characters in Frankenstein to be replaced with 'w'

Instead, this happened:
Helix became unresponsive

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-07-21T01:21:42.642 helix_view::theme [WARN] Theme: invalid style attribute: modifier
2022-07-21T01:21:42.642 helix_loader [DEBUG] Located configuration folders: []
2022-07-21T01:21:42.648 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2022-07-21T01:21:42.648 mio::poll [TRACE] registering event source with poller: token=Token(2), interests=READABLE | WRITABLE
2022-07-21T01:21:42.648 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE
2022-07-21T01:21:42.648 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE

```

</details>

### Platform

Linux (Pop!_Os)

### Terminal Emulator

Alactritty v0.10.0-rc1

### Helix Version

helix 22.05 (5ed62239)

### LINKED ISSUE #3133: Piping large amounts of text into head causes Broken pipe (os error 32)
### Summary

Might be related to #3127 
Piping large amounts of text into `head` causes a broken pipe, 
Smaller amounts of text work.

(I don't think piping into `head` within a text editor is particularly useful, but this might be a problem when piping other commands as well...)

### Reproduction Steps

 

I tried this:

1. `hx`
2. open a large text file, ie [frankenstein](https://raw.githubusercontent.com/asweigart/codebreaker/master/frankenstein.txt)
3. select a lot of text, (doesn't have to be the entire file)
4. use the pipe command `|` and pipe it into head

I expected this to happen:
Only the first ten lines remain

Instead, this happened:
File doesn't change, error message `Broken pipe (os error 32)`

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
please provide a copy of `~/.cache/helix/helix.log` here if possible, you may need to redact some of the lines
```

</details>

### Platform

Linux

### Terminal Emulator

Kitty

### Helix Version

helix 22.05

### PR DESCRIPTION
**Pull request by MDeiml**
Based on #3136. Fixes #3127 and might fix #3133.

This changes `shell_impl` to concurrently write to `stdin` while reading from `stdout` and `stderr`. This way processes will not block, if their input buffer is full, which is the current behavior.

I renamed `shell_impl` to `shell_impl_async` and added a new `shell_impl` as a blocking wrapper.

## Performance considerations

~Since `shell_impl_async` needs to take ownership of the input, I changed the input type to `Rope`. This can be constructed from the `RopeSlice` with `RopeSlice::into` in O(log n). We might want to copy the whole rope and give the current selection as an extra parameter which would be O(1), but a bit more ugly.~
This is not true. It's O(log n) either way. And obviously O(n) to pipe everything into the process. Don't know what I thought.

### CODE REVIEW

**Review by AceofSpades5757 — COMMENTED** [review]
I'm, personally, unsure on the changes to using Rope over Cow, but otherwise everything looks good. I was also able to verify that this resolves the issue from #3133 on Windows 10 and Ubuntu (WSL).

**Comment by MDeiml** [comment]
Those changes are because I based this PR on another PR of mine. I guess the other one should be merged first. But I'm not quite sure how else to do something like this.

File: helix-term/src/commands.rs [hunk 1]
```diff
@@ -4449,11 +4462,23 @@ fn shell_impl(
...
-        let mut stdin = process.stdin.take().unwrap();
-        stdin.write_all(input)?;
-    }
-    let output = process.wait_with_output()?;
+    let mut stdin = process.stdin.take().unwrap();
+    let input_task = tokio::spawn(async move {
+        if let Some(input) = input {
+            helix_view::document::to_writer(
+                &mut stdin,
+                Encoding::for_label(b"utf-8").unwrap(),
```
Comment (archseer) [inline helix-term/src/commands.rs:4470]: Just use `encoding::UTF_8`

**Comment by archseer** [comment]
Can you rebase this PR now since https://github.com/helix-editor/helix/pull/3136 was merged?

File: helix-term/src/commands.rs [hunk 2]
```diff
@@ -4543,13 +4543,20 @@ fn shell_keep_pipe(cx: &mut Context) {
     );
 }
 
-fn shell_impl(
+fn shell_impl(shell: &[String], cmd: &str, input: Option<Rope>) -> anyhow::Result<(Tendril, bool)> {
+    tokio::task::block_in_place(|| {
+        let runtime = tokio::runtime::Handle::current();
+        runtime.block_on(shell_impl_async(shell, cmd, input))
+    })
```
Comment (the-mikedavis) [inline helix-term/src/commands.rs:4550]:
```suggestion
    tokio::task::block_in_place(|| helix_lsp::block_on(shell_impl_async(shell, cmd, input)))
```

This will become more colloquial in the code-base once #2267 is in

File: helix-term/src/commands.rs [hunk 3]
```diff
@@ -4570,13 +4574,18 @@ fn shell_impl(
             return Err(e.into());
         }
     };
-    if let Some(input) = input {
-        let mut stdin = process.stdin.take().unwrap();
-        for chunk in input.chunks() {
-            stdin.write_all(chunk.as_bytes())?;
+    let mut stdin = process.stdin.take().unwrap();
```
Comment (the-mikedavis) [inline helix-term/src/commands.rs:4577]: This can panic when `input.is_none()`, for example `:sh sleep 1`

Comment (MDeiml) [reply helix-term/src/commands.rs:4577]: Oh, I took this straight from the rust docs, I'll change it

**Review by the-mikedavis — APPROVED** [review]

**Comment by the-mikedavis** [comment]
Thanks!
