### PR TITLE
Line ending detection

### LINKED ISSUE #68: Windows 10 build has malfunctioning view
It seems that the first line is not rendered, and the status bar is rendered at the wrong place too.  

image

### LINKED ISSUE #118: Support CRLF
It seems like it currently only supports LF. This leads to incorrect rendering and handling of CRLF text. I will be too busy to implement this functionality, sadly.

### PR DESCRIPTION
**Pull request by janhrastnik**
…\n', as this fixes CRLF files not rendering properly. Code that inserts line endings still needs to be changed and a platform default line ending could be added. 
@archseer may I ask why slice [here](https://github.com/helix-editor/helix/blob/master/helix-core/src/graphemes.rs#L175) isn't a borrow like in the [original code](https://github.com/cessen/led/blob/master/src/graphemes.rs#L162)?

Fixes #118 
Fixes #68

### CODE REVIEW

File: helix-view/src/document.rs [hunk 1]
```diff
@@ -20,6 +21,21 @@ pub enum Mode {
...
+    Crlf = 1, // CarriageReturn followed by LineFeed
+    LF = 2,   // U+000A -- LineFeed
+    VT = 3,   // U+000B -- VerticalTab
+    FF = 4,   // U+000C -- FormFeed
+    CR = 5,   // U+000D -- CarriageReturn
+    Nel = 6,  // U+0085 -- NextLine
+    LS = 7,   // U+2028 -- Line Separator
+    PS = 8,   // U+2029 -- ParagraphSeparator
+}
+
```
Comment (cessen) [inline helix-view/src/document.rs:38]: The second line of the doc comment here doesn't make sense here, since you didn't bring over the `LINE_ENDINGS` array (and I don't think you need to).  Probably best to delete that.

Also, in retrospect I don't know why I had a `None` variant in there.  That would probably be better represented by just wrapping `LineEnding` in an `Option` where needed.

Comment (archseer) [reply helix-view/src/document.rs:38]: We can also omit the explicit numbering, it's not necessary since there's no more `LINE_ENDINGS` array

File: helix-view/src/document.rs [hunk 2]
```diff
@@ -50,6 +66,7 @@ pub struct Document {
 
     diagnostics: Vec<Diagnostic>,
     language_server: Option<Arc<helix_lsp::Client>>,
+    _line_ending: LineEnding,
```
Comment (archseer) [inline helix-view/src/document.rs:69]: Just call it `line_ending`

File: helix-view/src/document.rs [hunk 3]
```diff
@@ -112,11 +129,59 @@ pub fn canonicalize_path(path: &Path) -> std::io::Result<PathBuf> {
...
+        _ => LineEnding::None,
+    }
+}
+
 use helix_lsp::lsp;
 use url::Url;
 
 impl Document {
-    pub fn new(text: Rope) -> Self {
+    pub fn new(text: Rope, _line_ending: LineEnding) -> Self {
```
Comment (archseer) [inline helix-view/src/document.rs:184]: Remove `line_ending` from `new`, make `Document::new` default to the system default (declare a  `const DEFAULT_LINE_ENDING` that uses `cfg` attrs to be set to `\r\n` if `target_os` is `windows`, else `\n`).

`Document::load` should detect the line ending, then change `doc.line_ending`.

File: helix-view/src/document.rs [hunk 4]
```diff
@@ -112,11 +129,59 @@ pub fn canonicalize_path(path: &Path) -> std::io::Result<PathBuf> {
     std::env::current_dir().map(|current_dir| normalize_path(&current_dir.join(path)))
 }
 
+pub fn auto_detect_line_ending(doc: &Rope) -> LineEnding {
```
Comment (archseer) [inline helix-view/src/document.rs:132]: We can probably move some of these issues into `helix_core::line_ending` (make a new module)

**Review by archseer — CHANGES_REQUESTED** [review]

File: helix-core/src/line_ending.rs [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+                    .unwrap();
+                rope_slice_to_line_ending(&g)
+            }
+            _ => None,
+        }
+    }
+    ending
+}
+
+pub fn default_line_ending() -> Option<LineEnding> {
```
Comment (archseer) [inline helix-core/src/line_ending.rs:68]:
```rust
#[cfg(target_os = "windows")]
const DEFAULT_LINE_ENDING: LineEnding = LineEnding::CrLf;
#[cfg(not(target_os = "windows"))]
const DEFAULT_LINE_ENDING: LineEnding = LineEnding::Lf;
```

File: helix-view/src/document.rs [hunk 6]
```diff
@@ -136,6 +139,7 @@ impl Document {
             history: Cell::new(History::default()),
             last_saved_revision: 0,
             language_server: None,
+            line_ending,
```
Comment (archseer) [inline helix-view/src/document.rs:142]:
```
line_ending: DEFAULT_LINE_ENDING
```

File: helix-view/src/editor.rs [hunk 7]
```diff
@@ -7,7 +7,7 @@ use slotmap::SlotMap;
 
 use anyhow::Error;
 
-pub use helix_core::diagnostic::Severity;
+pub use helix_core::{diagnostic::Severity, LineEnding};
```
Comment (archseer) [inline helix-view/src/editor.rs:10]: Is this import necessary here?

File: helix-view/src/document.rs [hunk 8]
```diff
@@ -285,6 +293,10 @@ impl Document {
         self.selections.insert(view_id, selection);
     }
 
+    pub fn set_line_ending(&mut self, line_ending: Option<LineEnding>) {
```
Comment (archseer) [inline helix-view/src/document.rs:296]: This can just take `LineEnding`, no option.

File: helix-view/src/document.rs [hunk 9]
```diff
@@ -50,6 +51,7 @@ pub struct Document {
 
     diagnostics: Vec<Diagnostic>,
     language_server: Option<Arc<helix_lsp::Client>>,
+    line_ending: Option<LineEnding>,
```
Comment (archseer) [inline helix-view/src/document.rs:54]: Doesn't have to be an option because we always expect to have a line ending.

File: helix-view/src/document.rs [hunk 10]
```diff
@@ -150,9 +154,13 @@ impl Document {
             Rope::from_reader(BufReader::new(file))?
         };
 
+        // search for line endings
+        let line_ending = auto_detect_line_ending(&doc);
```
Comment (archseer) [inline helix-view/src/document.rs:158]: `.unwrap_or(DEFAULT_LINE_ENDING)`

**Review by archseer — CHANGES_REQUESTED** [review]

File: helix-core/src/line_ending.rs [hunk 11]
```diff
@@ -0,0 +1,74 @@
...
+        // Not a line ending
+        _ => None,
+    }
+}
+
+pub fn auto_detect_line_ending(doc: &Rope) -> Option<LineEnding> {
+    // based on https://github.com/cessen/led/blob/27572c8838a1c664ee378a19358604063881cc1d/src/editor/mod.rs#L88-L162
+
+    let mut ending = None;
+    for line in doc.lines().take(1) {
```
Comment (cessen) [inline helix-core/src/line_ending.rs:47]: I remembered now why I had it checking the first 100 lines rather than just the first line.  Some line endings (e.g. FormFeed and ParagraphSeparator) are actually intended for mixed use with things like LF.

In practice it probably doesn't matter, since pretty much no one uses those anymore.  But it doesn't hurt to check, say, the first 10 lines or something just in case.

In fact, it might be worth excluding these three from the allowed auto-detect set:
* VT
* FF
* PS

Because I believe they're all special-use.  They should still be treated as line breaks, for correct text rendering, so they still need to be handled elsewhere in the code,  But they probably(?) never makes sense as a default line break.  I can investigate that more (I don't think it should block the PR).

File: helix-view/src/document.rs (hunk 9 above)
Comment (janhrastnik) [reply helix-view/src/document.rs:54]: auto_detect_line_ending can return None in some instances.

Comment (janhrastnik) [reply helix-view/src/document.rs:54]: Ah I see, we just set the default one then.

File: helix-core/src/line_ending.rs [hunk 12]
```diff
@@ -0,0 +1,65 @@
+use crate::{Rope, RopeGraphemes, RopeSlice};
+
+/// Represents one of the valid Unicode line endings.
+/// VT, FF and PS are excluded here, as we don't expect them to show up as a default line break
```
Comment (cessen) [inline helix-core/src/line_ending.rs:4]: Sorry, my fault for not being clear.  I still think VT, FF, and PS belong in the LineEnding enum.  Specifically, it may be useful in other parts of the code.  For example, maybe when rendering we'll want to re-use this code determining line endings, and render certain line endings differently.  Or something like that.  It also just helps serve to document for other devs what line endings are possible in Unicode, since a lot of people aren't aware of that.

I just meant that VT, FF, and PS probably shouldn't ever be returned by the auto-detect code.

File: helix-core/src/line_ending.rs (hunk 11 above)
Comment (cessen) [reply helix-core/src/line_ending.rs:41]: If we are indeed ignoring VT, FF, and PS, then it probably makes sense to keep iterating through the lines until we find a line ending that's not one of those.  And if we don't find one after some maximum number of lines (just to put a bounds on the extremely unlikely worst-case), then return None.

File: helix-core/src/line_ending.rs [hunk 13]
```diff
@@ -0,0 +1,121 @@
...
+        str_to_line_ending(text)
+    } else if g == "\u{000D}\u{000A}" {
+        Some(LineEnding::Crlf)
+    } else {
+        // Not a line ending
+        None
+    }
+}
+
+pub fn str_to_line_ending(g: &str) -> Option<LineEnding> {
```
Comment (cessen) [inline helix-core/src/line_ending.rs:27]: I think you can just include all the line endings here as well.  We will probably want to use this function in other parts of Helix as well, where we'll want to detect all possible line endings.  (In fact, I'm working on another PR where I'll want exactly that.)

Let's reject VT, FF, and PS in the auto-detect code itself, so that this can remain a more general utility function.

File: helix-term/src/ui/editor.rs [hunk 14]
```diff
@@ -175,7 +175,7 @@ impl EditorView {
 
                     // iterate over range char by char
                     for grapheme in RopeGraphemes::new(text) {
-                        if grapheme == "\n" {
+                        if grapheme == "\n" || grapheme == "\r\n" {
```
Comment (cessen) [inline helix-term/src/ui/editor.rs:178]: Actually, this is a great place to use the `str_to_line_ending()` function I commented on above.  The drawing code should handle all line endings, including VT etc.  So here we could do something like:

```if str_to_line_ending(grapheme).is_some() {```

File: helix-core/src/line_ending.rs [hunk 15]
```diff
@@ -0,0 +1,121 @@
...
+                rope_slice_to_line_ending(&g)
+            }
+            n if n > 1 => {
+                let g = RopeGraphemes::new(line.slice((line.len_chars() - 2)..))
+                    .last()
+                    .unwrap();
+                rope_slice_to_line_ending(&g)
+            }
+            _ => None,
+        };
```
Comment (cessen) [inline helix-core/src/line_ending.rs:59]: This is originally my code, so I'm really just commenting on my past self here, ha ha.  I'm looking at it now and I'm realizing this is wrong.  We need to handle the 1 vs 2-character grapheme cases in a different way.

I think what we actually need can be accomplished pretty nicely by taking advantage of some of `Option`s chaining methods:
```rust
// Last character as str.
let g1 = line.slice(line.len_chars().saturating_sub(1)..).as_str().unwrap();

// Last two characters as str, or empty str if they're not contiguous.
// It's fine to punt on the non-contiguous case, because Ropey guarantees
// that CRLF is always contiguous.
let g2 = line.slice(line.len_chars().saturating_sub(2)..).as_str().unwrap_or("");

// First check the two-character case for CRLF, then check the single-character case.
ending = str_to_line_ending(g2).or_else(|_| str_to_line_ending(g1));
```

You can in-line `g1` and `g2` if you want.

I think this is also a valid implementation for `rope_slice_to_line_ending()` (which I'm not totally sure is currently correct), so you put this code in there instead, and just call that here.

File: helix-term/src/ui/editor.rs (hunk 14 above)
Comment (janhrastnik) [reply helix-term/src/ui/editor.rs:178]: Right, will do. Do all the line endings have the same meaning though? FF and VT for example seem to move to a new line, but also indent it. Wouldn't we have to match specific line endings then in places like this?

Comment (cessen) [reply helix-term/src/ui/editor.rs:178]: That's a good point.  For now, I think we can get away with the simple solution I gave above just to make sure we're handling all the same line breaks as Ropey.  But we'll probably want to revisit it for special handling like that.

So for now, I'd say use `str_to_line_ending()` and add a TODO comment.

Comment (janhrastnik) [reply helix-term/src/ui/editor.rs:178]: Is rope_slice_to_line_ending needed? What if we just called str_to_line_ending(rope_slice.as_str().unwrap()) where rope_slice_to_line_ending is being used?

Comment (archseer) [reply helix-term/src/ui/editor.rs:178]: That unwrap could panic if the line ending spans through two chunks. Though ropey ensures that doesn't happen I think.

Comment (janhrastnik) [reply helix-term/src/ui/editor.rs:178]: > 
> 
> That unwrap could panic if the line ending spans through two chunks. Though ropey ensures that doesn't happen I think.

I already deleted the comment lol. I still don't get why we are matching Crlf in both functions though.

Comment (janhrastnik) [reply helix-term/src/ui/editor.rs:178]: And in this case I think I want to use rope_slice_to_line_ending(&grapheme).is_some() right?

File: helix-core/src/line_ending.rs [hunk 16]
```diff
@@ -0,0 +1,121 @@
...
+    LS,   // U+2028 -- Line Separator
+    VT,   // U+000B -- VerticalTab
+    FF,   // U+000C -- FormFeed
+    PS,   // U+2029 -- ParagraphSeparator
+}
+
+pub fn rope_slice_to_line_ending(g: &RopeSlice) -> Option<LineEnding> {
+    if let Some(text) = g.as_str() {
+        str_to_line_ending(text)
+    } else if g == "\u{000D}\u{000A}" {
```
Comment (archseer) [inline helix-core/src/line_ending.rs:19]: @cessen Given that ropey ensures \r\n is never split through two chunks, I think this case isn't necessary?

**Comment by janhrastnik** [comment]
@archseer I started replacing some occurances of '\n' in commands.rs. I noticed that a lot of places take in '\n' as a char, not a &str. But doc.line_ending() returns a &str, because (as much as I understand) "\r\n" is 2 characters long. Any ideas what to do here? Also I can't call doc.line_ending() at some points because doc can't be instantiated there yet because of lifetime errors.

File: helix-core/src/line_ending.rs (hunk 16 above)
Comment (cessen) [reply helix-core/src/line_ending.rs:19]: Correct.  That was the simplification I was alluding to in one of my other comments here.  If `as_str()` returns `None`, then there's no way it can be a well-formed line-ending grapheme.

File: helix-term/src/ui/editor.rs (hunk 14 above)
Comment (cessen) [reply helix-term/src/ui/editor.rs]: > Do we need rope_slice_to_line_ending? Could we just use str_to_line_ending(rope_slice.as_str().unwrap()) instead where rope_slice_to_line_ending is being used?

That's a great point.  However, the thing I'd be a little concerned about is the potential to confuse people reading the code later: the invariant that Ropey never splits line break graphemes across chunks isn't obvious unless you already know about it.  Putting this in a separate function gives us the opportunity to document that we're taking advantage of that, so that it's obvious to everyone, and we hopefully avoid mistakes in the future.  For example, maybe someone looks at that code and thinks they can use the same pattern for other things.

Comment (cessen) [reply helix-term/src/ui/editor.rs]: (But in general, I agree with you.  Getting rid of unneeded separate functions is generally a win IMO.)

**Comment by cessen** [comment]
> @archseer I started replacing some occurances of '\n' in commands.rs. I noticed that a lot of places take in '\n' as a char, not a &str. But doc.line_ending() returns a &str, because (as much as I understand) "\r\n" is 2 characters long.

Any place that needs a line ending as a literal should take a `&str` for sure, due to the CRLF case as you noted.  I think the lifetime issues can be dealt with by ensuring that all cases are `&'static str`, which shouldn't be hard for line endings: we have a limited set of known possible strings.

Something else that occurred to me is we could have the `LineEnding` implement a `to_str()`method as well, that just returns a `&'static str` representation.  I'm not sure if that would *actually* be useful enough in Helix's code base to justify the impl, so maybe no a good idea.  But just a thought.

File: helix-view/src/document.rs [hunk 17]
```diff
@@ -566,6 +578,20 @@ impl Document {
     pub fn set_diagnostics(&mut self, diagnostics: Vec<Diagnostic>) {
         self.diagnostics = diagnostics;
     }
+
+    pub fn line_ending(&self) -> &str {
```
Comment (archseer) [inline helix-view/src/document.rs:582]: Use `&'static str` here

File: helix-term/src/commands.rs [hunk 18]
```diff
@@ -184,8 +184,14 @@ pub fn move_line_end(cx: &mut Context) {
         let line = text.char_to_line(range.head);
 
         // Line end is pos at the start of next line - 1
-        // subtract another 1 because the line ends with \n
-        let pos = text.line_to_char(line + 1).saturating_sub(2);
+        // subtract 3 if the line ending is \r\n, otherwise subtract 2 as I assume all others are just 1 char length
+        let pos =
+            text.line_to_char(line + 1)
+                .saturating_sub(if doc.line_ending == LineEnding::Crlf {
+                    3
```
[the remark this answers is not in the document]
Comment (archseer) [reply helix-term/src/commands.rs:191]: @cessen I guess we could also have some sort of function for this (pos right before line end). We already ensure that the document is terminated by a new line so there's no need for a special case there

**Review by archseer — CHANGES_REQUESTED** [review]

File: helix-term/src/commands.rs [hunk 19]
```diff
@@ -1523,7 +1535,7 @@ fn open(cx: &mut Context, open: Open) {
             );
             let indent = doc.indent_unit().repeat(indent_level);
             let mut text = String::with_capacity(1 + indent.len());
-            text.push('\n');
+            text.push_str(doc.line_ending());
```
[the remark this answers is not in the document]
Comment (janhrastnik) [reply helix-term/src/commands.rs:1538]: this causes the following error: no method named `as_str` found for reference `&'static str` in the current scope

File: helix-term/src/commands.rs [hunk 20]
```diff
@@ -896,7 +908,7 @@ pub fn append_mode(cx: &mut Context) {
     if selection.iter().any(|range| range.head == end) {
         let transaction = Transaction::change(
             doc.text(),
-            std::array::IntoIter::new([(end, end, Some(Tendril::from_char('\n')))]),
+            std::array::IntoIter::new([(end, end, Some(Tendril::from_char('\n')))]), // TODO: change \n to doc.line_ending()
```
[the remark this answers is not in the document]
Comment (janhrastnik) [reply helix-term/src/commands.rs:911]: this returns the following error: the trait `From<&str>` is not implemented for `char`

File: helix-term/src/commands.rs (hunk 19 above)
[the remark this answers is not in the document]
Comment (archseer) [reply helix-term/src/commands.rs:1538]: Both of these comments are after you make this change: https://github.com/helix-editor/helix/pull/224#discussion_r653145199

[the remark this answers is not in the document]
Comment (archseer) [reply helix-term/src/commands.rs:1538]: line_ending should be private, line_ending() should return `LineEnding`, and `LineEnding` should have `as_str` implemented. You can also implement `AsRef<str>` for it by using `as_str`.

File: helix-term/src/commands.rs (hunk 20 above)
[the remark this answers is not in the document]
Comment (archseer) [reply helix-term/src/commands.rs:911]: After the changes mentioned above, `Some(doc.line_ending().into()` (or possibly `Some(doc.line_ending().as_str().into())` will work

File: helix-term/src/commands.rs (hunk 18 above)
[the remark this answers is not in the document]
Comment (janhrastnik) [reply helix-term/src/commands.rs:191]: But if .line_ending is private, then I can't call line_ending.len()

[the remark this answers is not in the document]
Comment (janhrastnik) [reply helix-term/src/commands.rs:191]: Nevermind, I now see that line_ending() is supposed to return LineEnding from now on.

File: helix-core/src/line_ending.rs [hunk 21]
```diff
@@ -13,6 +13,29 @@ pub enum LineEnding {
...
+            Self::LF => "\u{000A}",
+            Self::Nel => "\u{0085}",
+            Self::LS => "\u{2028}",
+            Self::CR => "\u{000D}",
+            _ => panic!(
+                "Unexpected line ending: {:?}, expected Crlf, LF, CR, Nel, or LS.",
+                self
+            ),
+        }
+    }
```
Comment (cessen) [inline helix-core/src/line_ending.rs:36]: Is there a reason for this to not handle all of the variants?  This seems like a generally useful function, and I wouldn't expect it to panic just because those variants aren't output by the line ending detector.

File: helix-core/src/line_ending.rs [hunk 22]
```diff
@@ -13,6 +13,29 @@ pub enum LineEnding {
     PS,   // U+2029 -- ParagraphSeparator
 }
 
+impl LineEnding {
+    pub fn len(&self) -> usize {
+        match self {
+            Self::Crlf => 2,
+            _ => 1,
+        }
+    }
```
Comment (cessen) [inline helix-core/src/line_ending.rs:22]: This looks like it's giving the line-ending size in chars.  Probably re-name to `len_chars()` to be clear.

(Or if you meant it to be bytes, then this isn't correct.  For example, [`LS` is 3 bytes in utf8](https://unicode-table.com/en/2028/), among others.)

File: helix-core/src/line_ending.rs (hunk 21 above)
Comment (cessen) [reply helix-core/src/line_ending.rs:36]: Whoops, sorry for the double-comment.  The other one wasn't showing up in the diff view for some reason.

File: helix-term/src/commands.rs [hunk 23]
```diff
@@ -185,7 +185,9 @@ pub fn move_line_end(cx: &mut Context) {
 
         // Line end is pos at the start of next line - 1
         // subtract another 1 because the line ends with \n
-        let pos = text.line_to_char(line + 1).saturating_sub(2);
+        let pos = text
+            .line_to_char(line + 1)
+            .saturating_sub(doc.line_ending().len() + 1);
```
Comment (cessen) [inline helix-term/src/commands.rs:190]: I don't think this correct (although not your fault--the previous version wasn't correct either).

1. We don't need the final `+ 1` inside the saturating sub, since that's now accounted for in the line ending length itself.
2. This code assumes that all line endings in the document match the document's line ending setting, which is not guaranteed.  We need to check the actual line ending of the line.
3. The last line in a `Rope` or `RopeSlice` doesn't have a line ending at all, so in that case there should be no subtraction.

I think what we want to do here is create a new function that just detects the line ending of a single line, and then use that here.  I think the function would look like this (untested):

```rust
/// Returns the passed line's line ending, if any.
fn get_line_ending(line: &RopeSlice) -> Option<LineEnding> {
    // Last character as str.
    let g1 = line.slice(line.len_chars().saturating_sub(1)..).as_str().unwrap();

    // Last two characters as str, or empty str if they're not contiguous.
    // It's fine to punt on the non-contiguous case, because Ropey guarantees
    // that CRLF is always contiguous.
    let g2 = line.slice(line.len_chars().saturating_sub(2)..).as_str().unwrap_or("");

    // First check the two-character case for CRLF, then check the single-character case.
    str_to_line_ending(g2).or_else(|_| str_to_line_ending(g1))
}
```

(This function could also be re-used in the document line detecting code.)

Then the code here would look like this (also untested):

```rust
let pos = text
    .line_to_char(line + 1)
    .saturating_sub(get_line_ending(text.line(line)).map(|le| le.len_chars()).unwrap_or(0));
```

File: helix-core/src/line_ending.rs (hunk 21 above)
Comment (janhrastnik) [reply helix-core/src/line_ending.rs:36]: Uhh, no idea why I excluded some. Something to do with only matching standard line endings in some previous iteration of the PR. You are right, we should be just handling everything here.

File: helix-term/src/commands.rs (hunk 23 above)
Comment (archseer) [reply helix-term/src/commands.rs:190]: This requires us to query `doc.line()` first, would `doc.line_end(line_num)` be a better API maybe?

Comment (archseer) [reply helix-term/src/commands.rs:190]: Thinking about it, your version can be used in contexts without doc so it's probably better: https://github.com/helix-editor/helix/blob/1c2585202145467f0fde7ad9c571e462081c3656/helix-core/src/movement.rs#L41

Comment (cessen) [reply helix-term/src/commands.rs]: > would doc.line_end(line_num) be a better API maybe?

I thought about that too.  Having a `Document::line_end(line_num)` would certainly be more efficient.  But I think for the time being something a little more general-purpose makes more sense.  It's an easy case to special-case and optimize later if we want to.

**Comment by cessen** [comment]
To anyone watching: I got permission to take this PR over, so I'll be finishing this up.

**Review by archseer — APPROVED** [review]
