### PR TITLE
Expand tilde for selected paths in `goto_file`

### LINKED ISSUE #10948: `gf` can't open directories that start with `~`
### Summary

I'm able to `gf` `/home/user/.config/helix` and get a file picker prompt, as well as `~/.config/helix/config.toml`, but when I try it on `~/.config/helix/`, I get an error: `Open file failed: Is a directory (os error 21)`. This bug seems to apply to all directories starting with a ~.

### Reproduction Steps

 

I tried this:

1. `hx`
2. `i`
3. `~/.config/helix`
4. `gf`

I expected the directory to open in a file picker.

Instead, I get the error `Open file failed: Is a directory (os error 21)`.

### Helix log

_No response_

### Platform

Linux

### Terminal Emulator

Alacritty

### Installation Method

`dnf`

### Helix Version

helix 24.3 (2cadec0b)

### PR DESCRIPTION
**Pull request by the-mikedavis**
Previously `gf` on `~/.config/helix` for example would error if the entire path was selected but succeed and open a picker for the directory contents if the selection was one one-width cursor. We need to expand tildes for all paths instead of just the auto-detected paths.

This also refactors the `goto_file` blocks a little so that we construct `paths` once instead of creating the Vec and immediately clearing it when the selection is one single-width cursor.

Fixes #10948

### CODE REVIEW

File: helix-term/src/commands.rs [hunk 1]
```diff
@@ -1202,19 +1202,15 @@ fn goto_file_impl(cx: &mut Context, action: Action) {
...
-        .map(|r| text.slice(r.from()..r.to()).to_string())
-        .collect();
-    let primary = selections.primary();
-    // Checks whether there is only one selection with a width of 1
-    if selections.len() == 1 && primary.len() == 1 {
-        paths.clear();
 
+    let paths: Vec<_> = if selections.len() == 1 && primary.len() == 1 {
+        // Secial case: if there is only one one-width selection, try to detect the
+        // path under the cursor.
```
Comment (matta) [inline helix-term/src/commands.rs:1213]: Might it be clearer if this block were pulled out into a function named something like `goto_file_detect_path`?

**Review by matta — COMMENTED** [review]
Just a drive by comment, take it or leave it. ;-)
