### PR TITLE
Center the picker preview selection using visual lines

### LINKED ISSUE #7836: global search preview doesn't correctly display the found line
### Summary

i believe this is an issue with soft wrapping - the line that the preview window puts at the top would be correct to center the selected line if lines were not wrapped, but if lines were wrapped, it pushes the selection down, eventually past the bottom of the preview window.

### Reproduction Steps

if i do a global search for `preview` in the helix repository, a file that doesn't require line wrapping displays the found line properly centered:
preview1
but if the file has longer lines, the found line gets pushed downward:
preview2
sometimes off the visible area entirely:
preview3

### Helix log

_No response_

### Platform

linux

### Terminal Emulator

alacritty 0.12.2

### Helix Version

helix 23.05

### PR DESCRIPTION
**Pull request by doy**
this way the preview always shows the selection even if lines were wrapped

fixes #7836

### CODE REVIEW

File: helix-term/src/ui/picker.rs [hunk 1]
```diff
@@ -690,20 +690,19 @@ impl<T: Item + 'static> Picker<T> {
...
-
-            let offset = ViewPosition {
-                anchor: doc.text().line_to_char(first_line),
-                horizontal_offset: 0,
-                vertical_offset: 0,
-            };
+            let text_fmt = doc.text_format(inner.width, None);
+            let annotations = TextAnnotations::default();
+            let mut offset = ViewPosition::default();
+            (offset.anchor, offset.vertical_offset) = char_idx_at_visual_offset(
```
Comment (pascalkuthe) [inline helix-term/src/ui/picker.rs:696]: If `range` is `None` we don't need need this. Since scrolling upwards from 0 is not possible anyway so I would siimoly change this to 

``` rust
if let Some(range) = range {
 (offset.anchor, offset.vertical_offset) = ...
}
```

**Review by pascalkuthe — DISMISSED** [review]
One small not, otherwise thus liims good. This was a good catch and something I missed in #5420

**Comment by doy** [comment]
fixed

**Review by pascalkuthe — APPROVED** [review]

**Review by the-mikedavis — APPROVED** [review]
