### PR TITLE
Apply transactions to all views

### LINKED ISSUE #4600: Panic when yank and past from right to left window of the same file
My Helix version is compiled from commit: 
```
commit 38149872989477f62222ce68dc32d2d6018ae165 (HEAD -> master, origin/master, origin/HEAD)
Author: Michael Davis <mcarsondavis@gmail.com>
Date:   Fri Nov 4 11:04:16 2022 -0500

    Fix panic on paste from blackhole register (#4497)
```

Panic when yank and past from right to left window of the same file

```
thread 'main' panicked at 'Position 21270 is out of range for changeset len 20356!', helix-core/src/transaction.rs:397:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### LINKED ISSUE #4732: Jumplist entries are not updated on all views when applying transactions
### Summary

Each view has a jumplist which contains selections that live on a document. Since #4186, whenever a transaction (any sort of change) is applied to a document, we apply the transaction to the view as well and use it to update the jumplist selections. This keeps the selections up-to-date as a document changes and prevents panics that can happen when jumplist selections point out-of-bounds of the document (https://github.com/helix-editor/helix/issues/2489).

#4186 only applies transactions to the currently focused view, though. If another view exists with jumplist entries for the same document, it is not updated by `helix_view::apply_transaction`. This can cause an incorrect jumplist entries or panics when multiple splits work with the same document.

### Reproduction Steps

Save a selection to the Jumplist and delete that part of the text from another split:

```
<C-w>v10[<space><C-s><C-w>wvggd
```

Then switch to the window with the jumplist entry: `<C-w>w`. And then trigger the panic through either `<C-o>` or any change to the document, like `d`.

### Helix log

_No response_

### Platform

Linux

### Terminal Emulator

Kitty 0.26.2

### Helix Version

22.08.1 (fd585c1e)

### LINKED ISSUE #4841: Position out of range for changeset
### Summary

I got an error saying `thread 'main' panicked at 'Position 23374 is out of range for changeset len 23317!', helix-core/src/transaction.rs:397:13` while navigating in Helix.

### Reproduction Steps

 

Helix suddenly stopped while navigating in code.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-11-21T19:01:35.384 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 166.191677ms" }
2022-11-21T19:03:44.156 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 146.466293ms" }
2022-11-21T19:05:04.030 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 122.840763ms" }
2022-11-21T19:11:44.549 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 439.784075ms" }
2022-11-21T19:12:24.009 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 247.880529ms" }
2022-11-21T19:18:35.406 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 199.625805ms" }
2022-11-21T19:27:25.534 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 423.679246ms" }
2022-11-21T19:27:25.941 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 222.533239ms" }

```

</details>

### Platform

macOS

### Terminal Emulator

iTerm2

### Helix Version

helix 22.08.1 (8bebd6dd)

### PR DESCRIPTION
**Pull request by the-mikedavis**
Previously, transactions were only applied to the currently focused view. This could lead to jumplist selections not being updated or panics if a jumplist selection pointed past the end of the document.

Closes #4732
Closes #4600
Closes #4841

### CODE REVIEW

File: helix-term/src/commands.rs [hunk 1]
```diff
@@ -1,3 +1,8 @@
+// TODO: remove this when the MSRV is 1.62.0.
+// This warning is benign and is removed in 1.62.0.
+// See https://github.com/rust-lang/rust/pull/96268
+#![allow(mutable_borrow_reservation_conflict)]
```
Comment (the-mikedavis) [inline helix-term/src/commands.rs:4]: The linked PR has some context on why this warning is removed and why it's ok to ignore.

It allows us to write in a style like so:

```rs
let (view, doc) = current_ref!(cx.editor);
// make some immutable borrows of `view` and `doc`
let transaction = // ...
cx.editor.apply_transaction(&transaction, doc.id(), view.id)
```

The immutable borrow of `Document::id` within the mutable borrow of `Editor::apply_transaction` is flagged as problematic by this warning. We could have a separate line for `let doc_id = doc.id()` but since this warning is going away in 1.62.0 I think we should just ignore it

**Review by the-mikedavis — COMMENTED** [review]
This change looks large but it's mostly borrowing fixes that are necessary because we need to mutably borrow Editor after immutably borrowing Document and/or View.

The upshot is that after this change, we use immutable borrows for Document and View much more often. Plus Document doesn't depend on View anymore.

The real changes in this PR come from moving `apply_transaction`, `undo`, `redo`, `earlier`, `later`, `restore` and `reload` into `Editor`

File: helix-view/src/macros.rs [hunk 2]
```diff
@@ -28,6 +28,16 @@ macro_rules! current_ref {
     }};
 }
 
+/// Get the IDs of the current View and Document immutably.
+/// Returns `(ViewId, DocumentId)`
+#[macro_export]
+macro_rules! current_ids {
+    ($editor:expr) => {{
+        let (view, doc) = $crate::current_ref!($editor);
```
Comment (archseer) [inline helix-view/src/macros.rs:36]: It's enough to only fetch the view and use view.id, view.doc

**Comment by the-mikedavis** [comment]
This is much cleaner 👍. We could revert https://github.com/helix-editor/helix/pull/4186 and #4227 but I left that as a TODO since it would be very noisy in the diff.

File: helix-core/src/history.rs [hunk 3]
```diff
@@ -119,6 +119,24 @@ impl History {
...
+
+        let mut transaction = self.revisions[revision].transaction.clone();
+
+        // The bounds are checked in the if condition above:
+        // `revision + 1` is known to be `<= self.current`.
+        for revision in &self.revisions[revision + 1..self.current] {
+            transaction = transaction.compose(revision.transaction.clone());
+        }
+
+        Some(transaction)
```
Comment (archseer) [inline helix-core/src/history.rs:137]: Functional one liner:

```suggestion
        // The bounds are checked in the if condition above:
        // `revision + 1` is known to be `<= self.current`.
        self.revisions[revision..self.current].iter().cloned().reduce(|acc, transaction| acc.compose(transaction))
```

File: helix-term/src/ui/editor.rs [hunk 4]
```diff
@@ -1413,13 +1415,31 @@ impl Component for EditorView {
...
-                    view.ensure_cursor_in_view(doc, config.scrolloff);
-
                     // Store a history state if not in insert mode. This also takes care of
                     // committing changes when leaving insert mode.
                     if mode != Mode::Insert {
                         doc.append_changes_to_history(view.id);
                     }
+
+                    // If the current document has been changed, apply the changes to all views.
+                    // This ensures that selections in jumplists follow changes.
```
Comment (archseer) [inline helix-term/src/ui/editor.rs:1425]: Note: mouse clicks can also change view focus and are handled separately further below

File: helix-term/tests/test/splits.rs [hunk 5]
```diff
@@ -127,3 +127,29 @@ async fn test_split_write_quit_same_file() -> anyhow::Result<()> {
...
+    //                The cursor is now at line 2 in window 2.
+    // * <C-s>        Save that selection to the jumplist in window 2.
+    // * <C-w>w       Switch to window 1.
+    // * kd           Delete line 1 in window 1.
+    // * <C-w>q       Close window 1, focusing window 2.
+    // * d            Delete line 1 in window 2.
+    //
+    // This panicked in the past because the jumplist entry on line 2 of window 2
+    // was not updated and after the `kd` step, pointed outside of the document.
+    test(("#[|]#", "<C-w>v[<space><C-s><C-w>wkd<C-w>qd", "#[|]#")).await?;
```
Comment (archseer) [inline helix-term/tests/test/splits.rs:152]: ❤️

File: helix-term/src/ui/editor.rs (hunk 4 above)
Comment (archseer) [reply helix-term/src/ui/editor.rs:1425]: Ah ok, this will apply as soon as changes are added to history, I thought it was when focus is changed 👍🏻
