### PR TITLE
fix: Never create automatic doc popups outside of Insert mode

### LINKED ISSUE #3112: Signature help gets stuck
### Summary

Occasionally signature help gets stuck without (at least I couldn't find it) ability to to hide it.
I am yet to come up with minimal reproduction example but once I find it I'll update this.

(this all not to say that signature help in general makes experience incredibly frustrating inside things as iterator::map or , say, tokio::spawn)

### Reproduction Steps

pending

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
I am unable to share full log and could not find anything relevant there
```

</details>

### Platform

Linux

### Terminal Emulator

kitty

### Helix Version

helix 22.05 (791bf7e5)

### LINKED ISSUE #4360: A docs panel open and never closes.
### Summary

I think we should have a force close command for any open document pop-up.

image

### Reproduction Steps

 

I tried this:

1. `hx`

I expected this to happen: Close open docs when I open any other docs by <SPACE> + k.

Instead, this happened: As you can see on my screen it always opens I even close the buffer but it is still there. Now to solve this I have to close and reopen the helix.

### Helix log

```
 
2022-10-17T14:00:52.751 helix_lsp::transport [ERROR] err <- "  51: proc_macro::bridge::client::run_client::{{closure}}::{{closure}}::
2022-10-18T12:40:51.357 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1711, character: 0 }, end: Position { line: 1711, character: 0 } }, severity: Some(Error), code: Some(String("syntax-error")), code_description: Some(CodeDescription { href: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("rust-analyzer.github.io")), port: None, path: "/manual.html", query: None, fragment: Some("syntax-error") } }), source: Some("rust-analyzer"), message: "Syntax Error: unmatched `}`", related_information: None, tags: None, data: None }
2022-10-18T12:40:51.964 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1710, character: 6 }, end: Position { line: 1710, character: 6 } }, severity: Some(Error), code: Some(String("syntax-error")), code_description: Some(CodeDescription { href: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("rust-analyzer.github.io")), port: None, path: "/manual.html", query: None, fragment: Some("syntax-error") } }), source: Some("rust-analyzer"), message: "Syntax Error: expected BANG", related_information: None, tags: None, data: None }
2022-10-18T12:40:51.964 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1710, character: 12 }, end: Position { line: 1710, character: 12 } }, severity: Some(Error), code: Some(String("syntax-error")), code_description: Some(CodeDescription { href: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("rust-analyzer.github.io")), port: None, path: "/manual.html", query: None, fragment: Some("syntax-error") } }), source: Some("rust-analyzer"), message: "Syntax Error: expected SEMICOLON", related_information: None, tags: None, data: None }
2022-10-18T12:40:51.964 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1711, character: 0 }, end: Position { line: 1711, character: 0 } }, severity: Some(Error), code: Some(String("syntax-error")), code_description: Some(CodeDescription { href: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("rust-analyzer.github.io")), port: None, path: "/manual.html", query: None, fragment: Some("syntax-error") } }), source: Some("rust-analyzer"), message: "Syntax Error: unmatched `}`", related_information: None, tags: None, data: None }
2022-10-18T12:41:12.416 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 141.290271ms" }
2022-10-18T12:48:08.069 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 143.542743ms" }
2022-10-18T12:48:36.148 helix_term::application [WARN] unhandled window/showMessage: ShowMessageParams { typ: Error, message: "overly long loop turn: 172.39674ms" }
2022-10-18T12:50:09.860 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1670, character: 6 }, end: Position { line: 1670, character: 6 } }, severity: Some(Error), code: Some(String("syntax-error")), code_description: Some(CodeDescription { href: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("rust-analyzer.github.io")), port: None, path: "/manual.html", query: None, fragment: Some("syntax-error") } }), source: Some("rust-analyzer"), message: "Syntax Error: expected BANG", related_information: None, tags: None, data: None }
2022-10-18T12:50:09.860 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1670, character: 12 }, end: Position { line: 1670, character: 12 } }, severity: Some(Error), code: Some(String("syntax-error")), code_description: Some(CodeDescription { href: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("rust-analyzer.github.io")), port: None, path: "/manual.html", query: None, fragment: Some("syntax-error") } }), source: Some("rust-analyzer"), message: "Syntax Error: expected SEMICOLON", related_information: None, tags: None, data: None }
2022-10-18T12:50:09.860 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1671, character: 0 }, end: Position { line: 1671, character: 0 } }, severity: Some(Error), code: Some(String("syntax-error")), code_description: Some(CodeDescription { href: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("rust-analyzer.github.io")), port: None, path: "/manual.html", query: None, fragment: Some("syntax-error") } }), source: Some("rust-analyzer"), message: "Syntax Error: unmatched `}`", related_information: None, tags: None, data: None }
2022-10-18T12:50:31.612 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1666, character: 6 }, end: Position { line: 1666, character: 6 } }, severity: Some(Error), code: Some(String("syntax-error")), code_description: Some(CodeDescription { href: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("rust-analyzer.github.io")), port: None, path: "/manual.html", query: None, fragment: Some("syntax-error") } }), source: Some("rust-analyzer"), message: "Syntax Error: expected BANG", related_information: None, tags: None, data: None }
2022-10-18T12:50:31.612 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1666, character: 12 }, end: Position { line: 1666, character: 12 } }, severity: Some(Error), code: Some(String("syntax-error")), code_description: Some(CodeDescription { href: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("rust-analyzer.github.io")), port: None, path: "/manual.html", query: None, fragment: Some("syntax-error") } }), source: Some("rust-analyzer"), message: "Syntax Error: expected SEMICOLON", related_information: None, tags: None, data: None }
2022-10-18T12:50:31.612 helix_term::application [WARN] lsp position out of bounds - Diagnostic { range: Range { start: Position { line: 1667, character: 0 }, end: Position { line: 1667, character: 0 } }, severity: Some(Error), code: Some(String("syntax-error")), code_description: Some(CodeDescription { href: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("rust-analyzer.github.io")), port: None, path: "/manual.html", query: None, fragment: Some("syntax-error") } }), source: Some("rust-analyzer"), message: "Syntax Error: unmatched `}`", related_information: None, tags: None, data: None }
2022-10-18T17:03:13.835 helix_view::editor [ERROR] Failed to initialize the LSP for `source.yaml` { cannot find binary path }
```

### Platform

Linux

### Terminal Emulator

zellij

### Helix Version

master

### PR DESCRIPTION
**Pull request by poliorcetics**
Testing strategy:

- Go on a function parameter with a language server that has doc popups, like rust-analyzer
- Create a macro that enters Insert mode and exits it (`Qi<Esc>Q`)
- Hit `q`
- **Old behaviour**: a doc popup appears and gets stuck
- **New behaviour**: no doc popup appears

Fixes #3112
Fixes #4360

### CODE REVIEW

File: helix-term/src/commands/lsp.rs [hunk 1]
```diff
@@ -957,6 +957,14 @@ pub fn signature_help_impl(cx: &mut Context, invoked: SignatureHelpInvoked) {
                 return;
             }
 
+            // If the signature help invocation is automatic, don't show it outside of Insert Mode:
+            // it very probably means the server was a little slow to respond and the user has
+            // already moved on to something else, making a signature help popup will just be an
+            // annoyance, see https://github.com/helix-editor/helix/issues/3112
+            if !was_manually_invoked && editor.mode != Mode::Insert {
```
Comment (dead10ck) [inline helix-term/src/commands/lsp.rs:964]: I think even if it's manually invoked, the same thing could happen right? Should we remove the first condition?

Comment (poliorcetics) [reply helix-term/src/commands/lsp.rs:964]: Yes it can but that's expected, there is "space+k" to get documentation, that command only works outside of insert mode.

**Comment by pathwave** [comment]
Could we check if the cursor is on the same line as the doc popup? If not then close it.
I also think the doc popup should be above the line and move with the view (so it stays above that line when one scrolls but dont move cursor). As long as there is space above.

Simularly for auto-complete being below the line and following cursor.

**Comment by the-mikedavis** [comment]
> Could we check if the cursor is on the same line as the doc popup

This sounds like a hack to support navigation in insert mode

> inside the function part of the line

What do you mean? Sounds like https://github.com/helix-editor/helix/issues/3385

In any case, this change is very well-contained and I think it will solve the bulk of the issues with signature help appearing when it shouldn't so I don't think we should bundle in other changes - further refinements should be separate PRs.

**Review by the-mikedavis — APPROVED** [review]
I've been testing this for a bit and it works great. I haven't seen any rogue signature help poppups in a few days 🎉

**Comment by pathwave** [comment]
Sorry I am tired, I ment "check if the cursor is on the same line as the function that the doc popup represents"
