### PR TITLE
make sure to sync views when applying edits to unfocused views

### LINKED ISSUE #6752: 'Position ... is out of range for changeset len ....!' panic on ~23.03 when saving a file
### Summary

Helix panicked on a recent build while saving a file, with error:

```
thread 'main' panicked at 'Position 6234 is out of range for changeset len 5108!', helix-core/src/transaction.rs:399:13
```

I was saving some combination of Go + Vue 2 files at the time

### Reproduction Steps

Unfortunately I don't have a reproducible use case, this is the first panic I've had since updating to something around 23.03

### Helix log

The `helix.log` didn't have anything useful, just LSP-related errors that aren't actually problems.

### Platform

Linux

### Terminal Emulator

alacritty / tmux

### Helix Version

helix 23.03 (3cf03723)

### PR DESCRIPTION
**Pull request by gabydd**
this fixes bugs when applying workspace edits with lsp to a view where the most recent selection range is outside the current document or when adding a newline/formatting during write all in the same situation

fixes https://github.com/helix-editor/helix/discussions/9157 and fixes #6752

I decided to sync the view when getting the id instead of calling sync when applying the transaction. I am not sure if I put the utility function in the correct place, I did have to take the tree instead of the editor because rust was giving me error for passing the editor within the closure in write-all, which I wasnt able to figure out

(I think we might be able to use this function in reload-all as well, though it already properly handles this)

### CODE REVIEW

**Comment by gabydd** [comment]
I can also confirm it fixes a bug similar to the one in the discussion but with renaming.where you open a document (a) then create a split and go to near the end of the file there, then change to a different document(b) that has a function you can rename that is referenced in file (a), then go to file (a) in the other split find the reference to the function you are going to rename and delete from the line after there to the end of the file, switch back to the other split with file (b) and rename the function, before this pr helix crashes there

File: helix-view/src/document.rs [hunk 1]
```diff
@@ -1141,6 +1142,29 @@ impl Document {
         self.inlay_hints.remove(&view_id);
     }
 
+    /// Returns the id of a view that this doc contains a selection for,
+    /// making sure it is synced with the current changes
+    /// if possible or there are no selections returns current_view
+    /// otherwise uses an arbitrary view
+    pub fn get_synced_view_id(&mut self, current_view: ViewId, tree: &mut Tree) -> ViewId {
```
Comment (pascalkuthe) [inline helix-view/src/document.rs:1149]: I think this should be a function on editor that takes a `DocumentId` as argument.

File: helix-view/src/document.rs [hunk 2]
```diff
@@ -1141,6 +1142,29 @@ impl Document {
...
+        if self.selections.contains_key(&current_view) {
+            let view = tree.get_mut(current_view);
+            // only need to sync current view if this is not the current doc
+            if view.doc != self.id {
```
Comment (pascalkuthe) [inline helix-view/src/document.rs:1153]: This is not necessary.  The current view is always sycned. We don't sync when switching buffer either, only when switching Views.

Comment (gabydd) [reply helix-view/src/document.rs:1153]: The reason for this being here is the document you might be fetching a view id for might not be the document but might contain the current view in its selection, maybe we should only take this path if we are getting for the current document I'll see when I move it too Editor

Comment (pascalkuthe) [reply helix-view/src/document.rs:1153]: Hmm I am not sure I understand. The currently selected view (whoch should be current_view) never needs to be synchronized. You only need to synchronize views that are not visible. This applys to all documwnts no matter whether they are currently shown in the view.

Comment (gabydd) [reply helix-view/src/document.rs]: coming back to this the reason why this is needed is if 
1. you have two views ``a`` and ``b``
2. you open the same document (``z``) in them
3. then in ``b`` open a different document (``x``) (this will be view.doc)
4. then go to ``a`` and make a change to ``z`` that won't be synced with b
5. so if you change to ``b`` and write-all, when looking for a view for ''z'' , ``b`` the current_view will work and need to be synced because the change was done in another view and we never synced that change when switching to this view
I hope that makes sense

**Comment by gabydd** [comment]
I moved it to editor, needed to change some things to appease the borrow checker stuff

File: helix-view/src/document.rs (hunk 2 above)
Comment (pascalkuthe) [reply helix-view/src/document.rs]: indeed you are right I was misremembering the details

**Review by pascalkuthe — APPROVED** [review]
