### PR TITLE
Determine whether to use a margin of 0 or 1 when uncommenting

### LINKED ISSUE #474: Uncommenting lines that are commented without a space deletes an extra character
### Reproduction steps
1. Comment a line of code without a space after the comment token, e.g., `//comment`.
2. Use the `C-c` shortcut to uncomment the line.
3. An extra character is deleted, causing the line to become `omment`.

### PR DESCRIPTION
**Pull request by Omnikar**
Fix #474. This change will cause uncommenting to use a margin of `0` when any of the uncommented lines does not have a space after the comment token, rather than unconditionally using a margin of `1`. I apologise if I might have overlooked something, I've never actually contributed to an open source project before.

### CODE REVIEW

**Comment by cessen** [comment]
This looks mostly good to me.  But a couple of things:

1. It would probably be better to roll the check into `find_line_comment()`, and have it returned as another element in the tuple.
2. There appears to be another bug (that was already there, not in your code) where lines that have multiple selections on them get multi-commented.  For example, if a line has two selections, then it will be prefixed with `// //` instead of `//`.  I don't know if you want to tackle that as well, but if you're up for it then we might as well roll it into the same PR.  Totally up to you.

File: helix-core/src/comment.rs [hunk 1]
```diff
@@ -53,6 +53,26 @@ pub fn toggle_line_comments(doc: &Rope, selection: &Selection, token: Option<&st
 
         changes.reserve((end - start).saturating_sub(skipped.len()));
 
+        // determine margin of 0 or 1 for uncommenting; if any comment token is not followed by a space,
+        // a margin of 0 is used for all lines.
+        let mut margin = 1;
+        if commented {
+            for line in lines.clone() {
```
Comment (pickfire) [inline helix-core/src/comment.rs:60]: Is it possible to not iterate over this twice?

Comment (Omnikar) [reply helix-core/src/comment.rs:60]: Merging with the bottom loop would cause a margin of `1` to be used until a line that should use a margin of `0`.

Comment (Omnikar) [reply helix-core/src/comment.rs:60]: However, as @cessen suggested, I'm going to change the margin calculation to occur in `find_line_comment`.

**Comment by Omnikar** [comment]
> 1. It would probably be better to roll the check into `find_line_comment()`, and have it returned as another element in the tuple.
@cessen Ok, this is done in `6055e93`.

**Comment by Omnikar** [comment]
> 2. There appears to be another bug (that was already there, not in your code) where lines that have multiple selections on them get multi-commented.  For example, if a line has two selections, then it will be prefixed with `// //` instead of `//`.  I don't know if you want to tackle that as well, but if you're up for it then we might as well roll it into the same PR.  Totally up to you.

Fixed in a7dd731e92f71ba4f2842105d9307d6258a83d08.

File: helix-core/src/comment.rs [hunk 2]
```diff
@@ -29,34 +30,45 @@ fn find_line_comment(
...
+    // selections on one line don't each try to change it.
+    let mut affected_lines: Vec<usize> = Vec::new();
+
     let token = token.unwrap_or("//");
     let comment = Tendril::from(format!("{} ", token));
 
     for selection in selection {
         let start = text.char_to_line(selection.from());
         let end = text.char_to_line(selection.to());
         let lines = start..end + 1;
```
Comment (pickfire) [inline helix-core/src/comment.rs:62]: Should we restructure this in a way that we only iterate over each necessary line once? Like this

1. We get all the lines covering all the selections, maybe with `HashSet`
2. We iterate each line separately rather than within the loop of `selection`

This way, we have a separate line processing and don't have to keep `affected_lines`.

Comment (Omnikar) [reply helix-core/src/comment.rs:62]: That seems like a good idea.

Comment (Omnikar) [reply helix-core/src/comment.rs:62]: I tried to implement it, but I am now encountering a panic whenever multiple lines are commented.

Comment (Omnikar) [reply helix-core/src/comment.rs:62]: Could the panic be a result of the lines not being iterated over in order due to the `HashSet`?

Comment (Omnikar) [reply helix-core/src/comment.rs:62]: The panic stopped happening when I converted the `HashSet` to a `Vec` and then sorted it before iterating over it.

Comment (cessen) [reply helix-core/src/comment.rs:62]: > Should we restructure this in a way that we only iterate over each necessary line once?

Agreed.
 
>     1. We get all the lines covering all the selections, maybe with `HashSet`

Probably don't need a `HashSet`.  Just push the line numbers to be commented/uncommented onto a `Vec`.  In other words, instead of returning a `Vec` of lines to be ignored (like it is now) return a `Vec` of the lines to operate on.  Then you can just iterate over those.

Comment (pickfire) [reply helix-core/src/comment.rs:62]: ~~But `HashSet` is better here since we need to keep searching whether the line is in the `Vec` to de-duplicate.~~

Ah, I didn't take the enforced line ordered into account, maybe we can just `lines = start.min(last_line + 1).......`?

Comment (cessen) [reply helix-core/src/comment.rs:62]: Yeah, that's pretty much what I was thinking.

Comment (Omnikar) [reply helix-core/src/comment.rs]: Alright, I've implemented it.

File: helix-core/src/comment.rs [hunk 3]
```diff
@@ -45,31 +51,32 @@ pub fn toggle_line_comments(doc: &Rope, selection: &Selection, token: Option<&st
...
+    }
 
-        changes.reserve((end - start).saturating_sub(skipped.len()));
+    let (commented, to_change, min, margin) = find_line_comment(&token, text, lines);
 
-        for line in lines {
-            if skipped.contains(&line) {
-                continue;
-            }
+    changes.reserve(to_change.len());
```
Comment (pickfire) [inline helix-core/src/comment.rs:66]: Why not initialize changes here?
```suggestion
    let changes = Vec::with_capacity(to_change.len());
```

**Review by pickfire — APPROVED** [review]
Beside the change mentioned looks good to me. Not tested.

Thanks for working on this. :D

File: helix-core/src/comment.rs (hunk 3 above)
Comment (Omnikar) [reply helix-core/src/comment.rs:66]: Ah, you're right. Though the suggested change doesn't remove the original `changes` declaration, and doesn't have a `mut` in the new declaration.

Comment (pickfire) [reply helix-core/src/comment.rs:66]: Oh, I forgot that.

Comment (pickfire) [reply helix-core/src/comment.rs:66]: Or we could do collect.

Comment (Omnikar) [reply helix-core/src/comment.rs:66]: Collect what?

File: helix-core/src/comment.rs [hunk 4]
```diff
@@ -29,12 +29,18 @@ fn find_line_comment(
                 // considered uncommented.
                 commented = false;
             }
-        } else {
-            // blank line
-            skipped.push(line);
+
+            // determine margin of 0 or 1 for uncommenting; if any comment token is not followed by a space,
+            // a margin of 0 is used for all lines.
+            if matches!(line_slice.get_char(pos + token.len()), Some(c) if c != ' ') {
```
Comment (archseer) [inline helix-core/src/comment.rs:35]: `token.len()` is in bytes whereas this is indexing by char. You probably need to `let token_len = token.chars().count()` outside the loop.

Comment (archseer) [reply helix-core/src/comment.rs:35]: I also think you can do what codemirror does and determine the margin per line (if get_char == Some(" ") then +1) https://github.com/codemirror/comment/blob/429551c1e778f1a10da5990e57dcf69c55c38fae/src/comment.ts#L189

File: helix-core/src/comment.rs [hunk 5]
```diff
@@ -91,8 +98,8 @@ mod test {
         let text = state.doc.slice(..);
 
         let res = find_line_comment("//", text, 0..3);
-        // (commented = true, skipped = [line 1], min = col 2)
-        assert_eq!(res, (false, vec![1], 2));
+        // (commented = true, to_change = [line 0, line 2], min = col 2, margin = 1)
+        assert_eq!(res, (false, vec![0, 2], 2, 1));
```
Comment (archseer) [inline helix-core/src/comment.rs:102]: There's a TODO for a test with no margin after the comment, can you add a case for it?

**Review by archseer — CHANGES_REQUESTED** [review]

File: helix-core/src/comment.rs (hunk 4 above)
Comment (Omnikar) [reply helix-core/src/comment.rs:35]: > I also think you can do what codemirror does and determine the margin per line (if get_char == Some(" ") then +1) https://github.com/codemirror/comment/blob/429551c1e778f1a10da5990e57dcf69c55c38fae/src/comment.ts#L189

Would that cause the margin to expand until encountering a non-space character?

File: helix-core/src/comment.rs (hunk 5 above)
Comment (Omnikar) [reply helix-core/src/comment.rs:102]: I tried adding a case reusing the `state` from the previous tests, but it seems that the selection must have been altered by the last test, because when I manually set `state.doc` and toggle the comments, the last line isn't affected; it does however work properly if I reset the selection by adding a copy of this line:
```rs
state.selection = Selection::single(0, state.doc.len_chars() - 1);
```

Comment (Omnikar) [reply helix-core/src/comment.rs:102]: Also, why do these tests have `.clone()` in each of these lines? It doesn't seem to be needed.
```rs
state.selection = state.selection.clone().map(transaction.changes());
```

File: helix-core/src/comment.rs [hunk 6]
```diff
@@ -29,47 +30,53 @@ fn find_line_comment(
                 // considered uncommented.
                 commented = false;
             }
-        } else {
-            // blank line
-            skipped.push(line);
+
+            // determine margin of 0 or 1 for uncommenting; if any comment token is not followed by a space,
+            // a margin of 0 is used for all lines.
+            if matches!(line_slice.get_char(pos + token_len), Some(c) if c != ' ') {
```
Comment (cessen) [inline helix-core/src/comment.rs:36]: The `matches!()` here is unneeded since it's only checking a single case.  You can just do:

```rust
if line_slice.get_char(pos + token_len) == Some(' ') {
```

File: helix-core/src/comment.rs (hunk 5 above)
Comment (archseer) [reply helix-core/src/comment.rs:102]: I think it used to be needed, that's why

Comment (Omnikar) [reply helix-core/src/comment.rs:102]: But it isn't needed now, so should I remove them?

File: helix-core/src/comment.rs [hunk 7]
```diff
@@ -1,17 +1,18 @@
 use crate::{
     find_first_non_whitespace_char, Change, Rope, RopeSlice, Selection, Tendril, Transaction,
 };
-use core::ops::Range;
 use std::borrow::Cow;
 
 fn find_line_comment(
```
Comment (pickfire) [inline helix-core/src/comment.rs:6]: Can you please add a comment `///` for this? The return is getting a bit long so we may want to explain what it returns.

Comment (Omnikar) [reply helix-core/src/comment.rs:6]: You want me to add a documentation comment for `find_line_comment`?

**Review by pickfire — APPROVED** [review]
Looks good to me besides on the comment that it should have. Not tested for a second time.

File: helix-core/src/comment.rs (hunk 7 above)
Comment (Omnikar) [reply helix-core/src/comment.rs:15]: Ok

**Comment by Omnikar** [comment]
I deleted the master branch of my fork accidentally, sorry.
