### PR TITLE
Fix panic when starting helix tutor

### LINKED ISSUE #11351: helix panics when trying to start :tutor
### Summary

Starting helix and trying to run the nix tutor immediately panics.

### Reproduction Steps

 

I tried this:

1. `hx`
2. `:tutor`
I expected this to happen:

That the helix tutor be started.

Instead, this happened:
Helix crashed with the following error:
```
❯ RUST_BACKTRACE=full hx
thread 'main' panicked at helix-view/src/document.rs:1083:57:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x55f07a27715b - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbb235daedd7c6190
   1:     0x55f07948e780 - core::fmt::write::h3ed6aeaa977c8e45
   2:     0x55f07a272ee3 - std::io::Write::write_fmt::h78b18af5775fedb5
   3:     0x55f07a276ef4 - std::sys_common::backtrace::print::h85035a511aafe7a8
   4:     0x55f07a278e70 - std::panicking::default_hook::{{closure}}::hcce8cea212785a25
   5:     0x55f07a278b8f - std::panicking::default_hook::hf5fcb0f213fe709a
   6:     0x55f07a27953f - std::panicking::rust_panic_with_hook::h095fccf1dc9379ee
   7:     0x55f07a279259 - std::panicking::begin_panic_handler::{{closure}}::h032ba12139b353db
   8:     0x55f07a277656 - std::sys_common::backtrace::__rust_end_short_backtrace::h9259bc2ff8fd0f76
   9:     0x55f07a279000 - rust_begin_unwind
  10:     0x55f079386ca5 - core::panicking::panic_fmt::h784f20a50eaab275
  11:     0x55f079386d63 - core::panicking::panic::hb837a5ebbbe5b188
  12:     0x55f079efc230 - helix_view::document::Document::pickup_last_saved_time::ha421dad7765454a0
  13:     0x55f079e9b419 - helix_term::commands::typed::tutor::h439c57ab70dd6df6
  14:     0x55f079e168e0 - helix_term::commands::typed::command_mode::{{closure}}::h14a3d4f465dd897d
  15:     0x55f079e2b8cd - <helix_term::ui::prompt::Prompt as helix_term::compositor::Component>::handle_event::h38d88fbc01632d35
  16:     0x55f079a5f6f5 - helix_term::compositor::Compositor::handle_event::h6efe7775e495607b
  17:     0x55f079ffdfc0 - hx::main_impl::{{closure}}::h70fafffa6571ad84
  18:     0x55f079ffb468 - tokio::runtime::park::CachedParkThread::block_on::h8461841775cdb088
  19:     0x55f07a036424 - hx::main::h8ba69e1a98becde2
  20:     0x55f07a053e83 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf27d6bb4e671f866
  21:     0x55f07a053e9d - std::rt::lang_start::{{closure}}::h02d42b636343d75d
  22:     0x55f07a269905 - std::rt::lang_start_internal::h6939038e2873596b
  23:     0x55f07a036a05 - main
  24:     0x7efe5329d0ce - __libc_start_call_main
  25:     0x7efe5329d189 - __libc_start_main@GLIBC_2.2.5
  26:     0x55f07940a815 - _start
  27:                0x0 - <unknown>
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

Helix log file was empty (removed it before reproducing, and it doesn't get filled with anything)
</details>

### Platform

Linux

### Terminal Emulator

alacritty/kitty/konsole

### Installation Method

flake

### Helix Version

helix 24.7 (30fb63cc3df96a0c79820dd2980a570cce11c8c3)

### PR DESCRIPTION
**Pull request by dnaq**
Closes #11351

### CODE REVIEW

File: helix-view/src/document.rs [hunk 1]
```diff
@@ -1080,20 +1080,26 @@ impl Document {
...
                     );
                     SystemTime::now()
                 }
             },
-            Err(e) => {
-                log::error!(
-                    "Use a system time instead of fs' mtime: failed to file's metadata: {e}"
-                );
+            None => {
+                log::error!("No current path, can't resolve last saved time");
```
Comment (dnaq) [inline helix-view/src/document.rs:1102]: I'm not sure this log message is needed, maybe it could be removed completely?

Comment (pascalkuthe) [reply helix-view/src/document.rs:1102]: A log message is not needed, a scratch buffer is completely valid case

Comment (dnaq) [reply helix-view/src/document.rs]: Removed the log message

**Review by pascalkuthe — APPROVED** [review]

File: helix-view/src/document.rs [hunk 2]
```diff
@@ -1080,22 +1080,25 @@ impl Document {
...
+                        log::error!(
+                            "Use a system time instead of fs' mtime not supported on this platform"
+                        );
+                        SystemTime::now()
+                    }
+                },
+                Err(e) => {
                     log::error!(
-                        "Use a system time instead of fs' mtime not supported on this platform"
+                        "Use a system time instead of fs' mtime: failed to file's metadata: {e}"
```
Comment (the-mikedavis) [inline helix-view/src/document.rs:1096]:
```suggestion
                        "Using system time instead of fs' mtime: failed to read file's metadata: {e}"
```

File: helix-view/src/document.rs [hunk 3]
```diff
@@ -1080,22 +1080,25 @@ impl Document {
     }
 
     pub fn pickup_last_saved_time(&mut self) {
-        self.last_saved_time = match self.path.as_mut().unwrap().metadata() {
-            Ok(metadata) => match metadata.modified() {
-                Ok(mtime) => mtime,
-                Err(_) => {
+        self.last_saved_time = match self.path().as_mut() {
```
Comment (the-mikedavis) [inline helix-view/src/document.rs:1083]: It's unrelated to these changes but the `as_mut` is unnecessary since `Path::metadata` takes a `&Path`

```suggestion
        self.last_saved_time = match self.path() {
```

Comment (dnaq) [reply helix-view/src/document.rs:1083]: I agree with both the comments, but those apply to the code as it was before the PR. If you still want me to apply the changes I'd be happy to do so.

Comment (the-mikedavis) [reply helix-view/src/document.rs:1083]: Yeah although they're not totally related to the fix I think it's fine to land them in this PR

**Comment by dnaq** [comment]
Updated the PR, and also changed the wording of the other log message to be consistent.

**Review by the-mikedavis — APPROVED** [review]

**Comment by pascalkuthe** [comment]
thanks!

**Comment by dnaq** [comment]
Sorry, it seems like I failed to push my latest changes (only the commit message), was on mobile. Sorry for that, would you mind reopening the PR?

**Comment by pascalkuthe** [comment]
hmm all the sugggestions by @the-mikedavis are already applied as far as I can tell. Yyou can still bush to this branch and then we can see what changes were missed and reopen if necessary

**Comment by pascalkuthe** [comment]
Ah right the `as_mut` change was missed. I think both of us missed that. You can just make a separate PR for that I think. That is not so critical that it would require a revert

**Comment by dnaq** [comment]
Both the as_mut change as well as the logging changes, in addition the commit message is wrong (since it says it fixed those things as well). I can make a new PR though.

**Comment by dnaq** [comment]
#11358 is the pr that fixes this, sorry for that
