### PR TITLE
Fix finding injection layer in tree cursor with nested layers

### LINKED ISSUE #11299: tree-sitter movements unreliable in vue files
### Summary

When editting vue files, it used to be impossible to use tree-sitter movements within the `<script>` tags. I was very happy to learn that release 24.03 made this possible. Unfortunately, I found that it does not reliably work for me. In many cases it works just as expected, but in many cases it doesn't - i.e. it behaves the way it did before, meaning `A-o` expands to include the entire `<script>` tag rather than the parent in the JS/TS syntax tree. Unfortunately, it's very hard to predict when that happens. I even found cases where it consistently fails on some lines and consistently works on others. E.g. I have something like this:

```typescript
foo.map(x => {
  const bar = 'baz';
  return `foo is ${bar}`;
})
```

where tree-sitter motions *do not* work in the lines up to `const bar ...` but *do* work starting at `return ...`. I am very puzzled when that happens so it's hard to give you exact reproduction steps (unless I would paste the entire file in here, which I can't).

### Reproduction Steps

 

I tried this:

1. `hx example.vue`
2. navigate to the `<script>` region
3. press `A-o`

I expected this to happen:
*Always* expand selection to the closest parent in the JS/TS tree.

Instead, this happened:
*Sometimes* the selection is being expanded to the closest parent in the HTML tree, i.e. the entire `<script>` tag.

### Helix log

_No response_

### Platform

Linux

### Terminal Emulator

alacritty

### Installation Method

pacman

### Helix Version

24.7

### PR DESCRIPTION
**Pull request by the-mikedavis**
The `take_while` should limit the ranges we consider to those that end on/after the searched `end`: the ranges are sorted by `end` ascending and if a tree has nested injection layers, the starts might be sorted in descending.

For example

```vue
<script setup lang="ts">
const foo = 'bar'.match(/foo/);
const bar = foo;
</script>
```

L2 and L3 are a typescript layer and the `/foo/` part is a small regex layer. If you used `A-o` before the regex layer you would select the entire typescript layer. The search in `layer_id_containing_byte_range` would not consider the typescript layer since the regex layer comes earlier in `injection_ranges` and that layer's start is after `end`.

The `partition_point` in the line above this change leads us to the start of the ranges where `range.end >= end` and we want to limit our search to layers where that remains true.

Fixes #11299

### CODE REVIEW

**Comment by pascalkuthe** [comment]
I am not sure this is quite the right fix. The way partition point works is that you supply it a predicate. The perdicate is true for every index small than the returned index and false for every index >= the returned index.

That means that the new `take_while` condition is useless. The `take_while` predicate is the opposite of the partition point predicate and therefore pre definition always true. 

What the `take_while` condition was supposed to prevent was the following situation:

```
| injection 0 |              | injection 1 |   ... many many more injections
                  | range |
```

here the range does not belong to any injection. However the partition point will return 1. That means that we now linear search the entire (potentially huge) list of injections. 

I think you found the right bug but the fix should be different (what you did works but it makes this condition useless and is a performance problem)

My understanding is that injection ranges should form a tree (since the ranges get intersected every injection range is a subrange of its parent range, sibling ranges are always non-overlapping). Lets consider an example topology:

```
   |child 1 |  |range|  | child 2 |
|       sibling 1                    |     | sibling 2 |
```


This get sorted as follows:

`[child1, child 2, sibling 1, sibling 2]`

What we want is `sibling 1`. And we want to stop after `sibling 1` and look at `sibling 2` (ideally we also wouldn't look at `child 2` but that is not possible). After the portion point we get `[child 2, sibling 1, sibling 2]`. The bug is caused because the algorithm rightfully identifier that `child 2` is not relevant. That means we stop the search before we can look at `sibling 1`. 

The best fix here would be to actually store injections as a real tree. That is what I am doing in my rewrite of our tree sitter code. For now with this flattened tree we have we can only apply the `take_while` predicate on the root layer. So fixing this would simply require `take_while( we need to change the `take_while` predicate to `range.start < end || range.depth != 0`. In practice this should work almost as well since all situations with a ton of injections I am aware of always have the injections at the root layer.

**Comment by the-mikedavis** [comment]
Ah right, the current `take_while` would always be true. I think we can just remove the take_while since `injection_ranges` only has non-root layers

**Comment by pascalkuthe** [comment]
Ah I think the predicate needs to check for depth `1` not depth 0. Basically in the example above stopping at sibling 1 is ok and quite a good idea for performance reasons

**Comment by pascalkuthe** [comment]
basically I mean the take while scondition should only apply to injections that are injected into the root layre. But I guess if root is depth zero than their depth is 1 and not 0

File: helix-core/src/syntax/tree_cursor.rs [hunk 1]
```diff
@@ -204,7 +204,7 @@ impl<'a> TreeCursor<'a> {
 
         self.injection_ranges[start_idx..]
             .iter()
-            .take_while(|range| range.start < end)
+            .take_while(|range| range.end >= end)
```
Comment (pascalkuthe) [inline helix-core/src/syntax/tree_cursor.rs:207]:
```suggestion
            .take_while(|range| range.start < end || range.depth > 1)
```

this should work

Comment (the-mikedavis) [reply helix-core/src/syntax/tree_cursor.rs]: It should be possible to set up some unit tests. We have a few at the bottom of `syntax` that set up a parser and then use it for a case

**Review by archseer — APPROVED** [review]
