### PR TITLE
UTF Conserve BOM bytes and properly support UTF16

### LINKED ISSUE #6246: Helix doesn't maintain BOM
### Summary

When a file with the [UTF-8 Byte Order Mark](https://en.wikipedia.org/wiki/Byte_order_mark) (initial byte sequence `EF BB BF`) is opened, it is not preserved on save. While this generally isn't a major issue, it does mean any file changed with `hx` will be marked as changed by `git`, for example, even if you've made no character-wise changes.

### Reproduction Steps

 

I tried this:

1. `printf '\xEF\xBB\xBFtest\n' > bom-file`
2. make sure `file bom-file` reports `bom-file: Unicode text, UTF-8 (with BOM) text`
3. `hx bom-file` and `:wq` immediately afterward

I expected this to happen:
`file bom-file` reports `bom-file: Unicode text, UTF-8 (with BOM) text` once again, for the BOM is maintained

Instead, this happened:
`file bom-file` reports `bom-file: ASCII text`, for the BOM is gone

### Helix log

_No response_

### Platform

Linux 6.1.14-100.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Feb 26 00:31:11 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Terminal Emulator

kitty 0.26.5

### Helix Version

helix 22.12

### LINKED ISSUE #6542: UTF16: reading file is fine, but writing file is garbage
### Summary

When reading from UTF16 file, helix decode it correctly, but when writing back the file on disk, it write back garbage data.

#### I tried this:

1. `wget https://raw.githubusercontent.com/stain/encoding-test-files/master/utf16.txt` - download a sample UTF16 file inside this project
1. `file utf16.txt` - print `utf16.txt: Unicode text, UTF-16, little-endian text`
1. `hx`
1. In helix, type `:x`
1. `file utf16.txt` - now print `utf16.txt: ISO-8859 text`  :warning:  

#### I expected this to happen:

helix to convert the file to UTF8 - or keep UTF16 little endian

#### Instead, this happened:

helix written something else completely - ASCII character survive the change of encoding but any character outside ASCII is not Unicode characters.

#### File content 

<details><summary>hexdump before file edit</summary>

```
00000000  ff fe 70 00 72 00 65 00  6d 00 69 00 e8 00 72 00  |..p.r.e.m.i...r.|
00000010  65 00 20 00 69 00 73 00  20 00 66 00 69 00 72 00  |e. .i.s. .f.i.r.|
00000020  73 00 74 00 0a 00 70 00  72 00 65 00 6d 00 69 00  |s.t...p.r.e.m.i.|
00000030  65 00 00 03 72 00 65 00  20 00 69 00 73 00 20 00  |e...r.e. .i.s. .|
00000040  73 00 6c 00 69 00 67 00  68 00 74 00 6c 00 79 00  |s.l.i.g.h.t.l.y.|
00000050  20 00 64 00 69 00 66 00  66 00 65 00 72 00 65 00  | .d.i.f.f.e.r.e.|
00000060  6e 00 74 00 0a 00 1a 04  38 04 40 04 38 04 3b 04  |n.t.....8.@.8.;.|
00000070  3b 04 38 04 46 04 30 04  20 00 69 00 73 00 20 00  |;.8.F.0. .i.s. .|
00000080  43 00 79 00 72 00 69 00  6c 00 6c 00 69 00 63 00  |C.y.r.i.l.l.i.c.|
00000090  0a 00 01 d8 00 dc 20 00  61 00 6d 00 20 00 44 00  |...... .a.m. .D.|
000000a0  65 00 73 00 65 00 72 00  65 00 74 00 0a 00        |e.s.e.r.e.t...|
000000ae
```

</details>

<details><summary>hexdump after file edit</summary>

```
00000000  70 72 65 6d 69 e8 72 65  20 69 73 20 66 69 72 73  |premi.re is firs|
00000010  74 0a 70 72 65 6d 69 65  26 23 37 36 38 3b 72 65  |t.premie&#768;re|
00000020  20 69 73 20 73 6c 69 67  68 74 6c 79 20 64 69 66  | is slightly dif|
00000030  66 65 72 65 6e 74 0a 26  23 31 30 35 30 3b 26 23  |ferent.&#1050;&#|
00000040  31 30 38 30 3b 26 23 31  30 38 38 3b 26 23 31 30  |1080;&#1088;&#10|
00000050  38 30 3b 26 23 31 30 38  33 3b 26 23 31 30 38 33  |80;&#1083;&#1083|
00000060  3b 26 23 31 30 38 30 3b  26 23 31 30 39 34 3b 26  |;&#1080;&#1094;&|
00000070  23 31 30 37 32 3b 20 69  73 20 43 79 72 69 6c 6c  |#1072; is Cyrill|
00000080  69 63 0a 26 23 36 36 35  36 30 3b 20 61 6d 20 44  |ic.&#66560; am D|
00000090  65 73 65 72 65 74 0a                              |eseret.|
00000097
```

</details>

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-04-01T21:43:04.411 helix_view::clipboard [DEBUG] Using wl-copy+wl-paste to interact with the system and selection (primary) clipboard
2023-04-01T21:43:04.412 helix_vcs [ERROR] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepositoryWithinFs {
            path: "/tmp",
            limit: "/",
        },
    ),
}
2023-04-01T21:43:04.412 helix_vcs [ERROR] failed to open diff base for /tmp/utf16.txt
2023-04-01T21:43:04.412 helix_vcs [ERROR] Error {
    context: "failed to open git repo",
    source: Discover(
        NoGitRepositoryWithinFs {
            path: "/tmp",
            limit: "/",
        },
    ),
}
2023-04-01T21:43:04.412 helix_vcs [ERROR] failed to obtain current head name for /tmp/utf16.txt
2023-04-01T21:43:04.412 helix_view::editor [DEBUG] editor status: Loaded 1 file.
2023-04-01T21:43:04.415 helix_tui::backend::crossterm [DEBUG] The keyboard enhancement protocol is supported in this terminal (checked in 3.104306ms)
2023-04-01T21:43:04.415 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-01T21:43:04.812 helix_term::application [DEBUG] received editor event: IdleTimer
2023-04-01T21:43:04.903 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-01T21:43:05.062 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-01T21:43:05.215 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-01T21:43:05.367 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-01T21:43:05.767 helix_term::application [DEBUG] received editor event: IdleTimer
2023-04-01T21:43:05.975 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-01T21:43:06.150 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-01T21:43:06.376 helix_term::application [DEBUG] received editor event: IdleTimer
2023-04-01T21:43:06.382 helix_view::document [DEBUG] submitting save of doc 'Some("/tmp/utf16.txt")'
2023-04-01T21:43:06.382 helix_term::job [DEBUG] waiting on jobs...
2023-04-01T21:43:06.383 helix_view::document [DEBUG] doc 1 revision updated 0 -> 0
2023-04-01T21:43:06.383 helix_term::commands::typed [DEBUG] quitting...
2023-04-01T21:43:06.383 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-01T21:43:06.383 helix_term::job [DEBUG] waiting on jobs...
2023-04-01T21:43:06.383 helix_term::job [DEBUG] waiting on jobs...
```

</details>

### Platform

Linux - Fedora 38

### Terminal Emulator

kitty 0.26.5

### Helix Version

helix 23.03

### PR DESCRIPTION
**Pull request by Alexis-Lapierre**
Create an enum EncodingBom in `helix-view/src/document.rs` that represent the Document encoding with BOM information.

Previous behaviour:

```bash
$ printf '\xEF\xBB\xBFtest\n' > utf8
$ file utf8
utf8: Unicode text, UTF-8 (with BOM) text
$ hx utf8    # Only type ':x' inside helix
$ file utf8
utf8: ASCII text
```

New behaviour:

```bash
$ printf '\xEF\xBB\xBFtest\n' > utf8
$ file utf8
utf8: Unicode text, UTF-8 (with BOM) text
$ hx utf8    # Only type ':x' inside helix
$ file utf8
utf8: Unicode text, UTF-8 (with BOM) text
```

This close #6246.

I'm still new to Rust, so feedback to improve this pull request is appreciated.

## Edit

After some work, I removed the enum EncodingBom and replaced it by a boolean value, as per the feedback from @archseer.

I added some more commits on top of it to support UTF16 on top of UTF8. I had to implement an enum Encoder to buffer the writes to UTF16 since `encoding_rs` does not support writing UTF16 files.

So this pull request now also close #6542 on top of #6246.

I tested my branch against UTF8 with and without BOM, and UTF16 LE and BE.

### CODE REVIEW

**Comment by kirawi** [comment]
`encoding_rs` looks to also handle UTF-16LE and UTF-16BE: https://docs.rs/encoding_rs/latest/src/encoding_rs/lib.rs.html#3757

**Comment by pascalkuthe** [comment]
yeah:
``` rust

    /// Performs non-incremental BOM sniffing.
    ///
    /// The argument must either be a buffer representing the entire input
    /// stream (non-streaming case) or a buffer representing at least the first
    /// three bytes of the input stream (streaming case).
    ///
    /// Returns `Some((UTF_8, 3))`, `Some((UTF_16LE, 2))` or
    /// `Some((UTF_16BE, 2))` if the argument starts with the UTF-8, UTF-16LE
    /// or UTF-16BE BOM or `None` otherwise.
    ///
    /// Available via the C wrapper.
    #[inline]
    pub fn for_bom(buffer: &[u8]) -> Option<(&'static Encoding, usize)> {
        if buffer.starts_with(b"\xEF\xBB\xBF") {
            Some((UTF_8, 3))
        } else if buffer.starts_with(b"\xFF\xFE") {
            Some((UTF_16LE, 2))
        } else if buffer.starts_with(b"\xFE\xFF") {
            Some((UTF_16BE, 2))
        } else {
            None
        }
    }
    ```

**Comment by Alexis-Lapierre** [comment]
At the start I implemented UTF16 support with this merge request, but I reverted it (8e38adf30e16839d68f4cabb87734fcab0f6e5f4) because editing UTF16 on master mess up the file.

Here is the behaviour I have on master:
image

utf16.txt was downloaded from https://github.com/stain/encoding-test-files/blob/master/utf16.txt.

If it is reproducible on more machines, we should probably create an issue for that

**Comment by Alexis-Lapierre** [comment]
> At the start I implemented UTF16 support with this merge request, but I reverted it ([8e38adf](https://github.com/helix-editor/helix/commit/8e38adf30e16839d68f4cabb87734fcab0f6e5f4)) because editing UTF16 on master mess up the file.
> 
> Here is the behaviour I have on master: image
> 
> utf16.txt was downloaded from https://github.com/stain/encoding-test-files/blob/master/utf16.txt.
> 
> If it is reproducible on more machines, we should probably create an issue for that

I created #6542 to explain in more details the problem I encountered while writing this pull request for UTF16

**Comment by kirawi** [comment]
`encoding_rs` only supports decoding of UTF-16: https://github.com/hsivonen/encoding_rs/issues/31#issuecomment-382991993

**Comment by pascalkuthe** [comment]
> `encoding_rs` only supports decoding of UTF-16: [hsivonen/encoding_rs#31 (comment)](https://github.com/hsivonen/encoding_rs/issues/31#issuecomment-382991993)

to be fair std supports encoding utf-16 so it shouldn't be too hard to roll our encoder: https://github.com/hsivonen/encoding_rs/issues/31#issuecomment-552665090 (can be done more efficiently and would look different in our case, simply iterating the doc chars and converting each to utf16 should work decently enough)

File: helix-view/src/document.rs [hunk 1]
```diff
@@ -115,6 +116,58 @@ pub struct SavePoint {
     revert: Mutex<Transaction>,
 }
 
+// An enum representing the encoding and if it contain a byte order mark
+#[derive(Debug, Clone)]
+pub enum EncodingBom {
+    UTF8,
+    NoBom(&'static Encoding),
+}
```
Comment (archseer) [inline helix-view/src/document.rs:124]: This could be `Copy`. But it also seems a bit of a footgun that it can either be `UTF8` or `NoBom(UTF8)`.

File: helix-view/src/document.rs [hunk 2]
```diff
@@ -115,6 +116,58 @@ pub struct SavePoint {
...
+    fn from(value: &'static Encoding) -> Self {
+        EncodingBom::NoBom(value)
+    }
+}
+
+impl Default for EncodingBom {
+    fn default() -> Self {
+        EncodingBom::NoBom(encoding::UTF_8)
+    }
+}
```
Comment (archseer) [inline helix-view/src/document.rs:169]: I'd move this right after the struct definition to make it more obvious

File: helix-view/src/document.rs (hunk 1 above)
Comment (archseer) [reply helix-view/src/document.rs:124]: I'd rather structure the encoding field on the document to be a tuple `(Encoding, bool)` or a separate bool field. Then we can pattern match:

```rust
match {
  (UTF8, true) =>
  (UTF16_BE, true) =>
  (UTF16_LE, true) =>
  (encoding, _ignore) => 
```

or

```rust
fn has_bom() -> bool {
   matches!((encoding, bom), (UTF8 | UTF16_BE | UTF_16_LE, true))
}
```

Comment (Alexis-Lapierre) [reply helix-view/src/document.rs:124]: Funnily enough, I came to the opposite conclusion when exploring what could be done for bom support, in this branch: https://github.com/helix-editor/helix/compare/master...Alexis-Lapierre:helix:wip_conserve_bom_on_file_save

I first created a boolean to track the bom status, but I decided against it because sometime we could enter an invalid state. What should we do if Document is in state `encoding: windows-1252, has_bom: true` ?

I came to the conclusion that having an enum that track the bom status would not allow to be in an incoherent state, and that's why I made this choice.

Comment (Alexis-Lapierre) [reply helix-view/src/document.rs]: EncodingBom now derive Copy.

File: helix-view/src/document.rs (hunk 2 above)
Comment (Alexis-Lapierre) [reply helix-view/src/document.rs]: This impl is now moved just below EncodingBom declaration.

**Comment by Alexis-Lapierre** [comment]
NB: I'm waiting for  #6549 to be merged to remove aacf4e36a4a88ddd162a242406bb857327fabf12 from this merge request, so that helix support utf8 and utf16 bom

File: helix-view/src/document.rs (hunk 1 above)
Comment (Alexis-Lapierre) [reply helix-view/src/document.rs]: I replaced EncodingBom by a boolean in [0ea7235](https://github.com/helix-editor/helix/pull/6497/commits/0ea7235f029c5b5b3562f68642db85a9f9344e46), as requested.

**Comment by Alexis-Lapierre** [comment]
> NB: I'm waiting for #6549 to be merged to remove [aacf4e3](https://github.com/helix-editor/helix/commit/aacf4e36a4a88ddd162a242406bb857327fabf12) from this merge request, so that helix support utf8 and utf16 bom

I implemented the proper way to save files in UTF16 with buffering in this commit: 642d9e738af79dd05a1d203aee3cff529f83d709 .

**Review by pascalkuthe — DISMISSED** [review]
This LGTM. The utf16 encoding implementation is exactly what I had in mind and endsup less disruptive to the codebase (while being faster) and feels more inline with what is actually changed (adding an.improved encoder instead of adding special cases to the code that uses the encoder). This could use some integration tests tough both for the bom and encoding handeling. This kind of stuff should ne pretty easy to write tests for. I don't have a lot of utf-16 text on hand to test this manually :D

**Comment by Alexis-Lapierre** [comment]
> This LGTM. The utf16 encoding implementation is exactly what I had in mind and endsup less disruptive to the codebase (while being faster) and feels more inline with what is actually changed (adding an.improved encoder instead of adding special cases to the code that uses the encoder). This could use some integration tests tough both for the bom and encoding handeling. This kind of stuff should ne pretty easy to write tests for. I don't have a lot of utf-16 text on hand to test this manually :D

Thank you for your comment, I am waiting on the second reviewer to see if I need to modify anything in my pull request.
I think I'll make a follow up pull request adding the unit tests after this pr.

**Comment by pascalkuthe** [comment]
We usually keep tests in the same PR if they are not too complex so I would prefer if you add it here. The tests should just be simple integration tests (in `helix-term/src/tests`) that open an utf16 file with the editor and check that the text of the active document is equal to what is expected and that the file remains unchanged after saving (you can do versions with and without BOM) so even if something about the code changes these tests would not interact with your API so the risk of duplicate work is fairly small IMO.

**Comment by Alexis-Lapierre** [comment]
OK thanks for the feedback. Expect an update on this Pull Request during this week.

**Comment by Alexis-Lapierre** [comment]
I've added https://github.com/helix-editor/helix/commit/1ec6cdd27411af534bb88a4682f7411f32ee64c8

The commit add a simple integration test that repeat the steps to reproduce #6542 and #6246.

**Review by pascalkuthe — APPROVED** [review]
thanks for adding those tests! LGTM now altough we will likely wait until after the bugfix release to merge

**Comment by kekePower** [comment]
This looks like it's working as expected. Thanks for you efforts!

```
% file *txt
utf16-helix-01.txt: Unicode text, UTF-16, little-endian text
utf16-nvim-01.txt:  Unicode text, UTF-16, little-endian text
utf16.txt:          Unicode text, UTF-16, little-endian text
```
I opened utx16.txt and wrote the file to disk using helix 23.03 with this patch and neovim from git master.

**Review by the-mikedavis — APPROVED** [review]
