### PR TITLE
fix division by zero when prompt completion area is too small

### LINKED ISSUE #9523: attempt to divide by zero when resizing the terminal
### Summary

similarly to #1403, the program crashes when resizing the terminal while the preview/info box is displayed
see the reproduction steps below

### Reproduction Steps

 

I tried this:

1. open a terminal
2. run helix
3. press colon to open the prompt
4. press tab to show the preview/info box above the items
6. make the terminal really small (0 x 0)

I expected this to happen:

- helix resizes accordingly

Instead, this happened:

- helix crashed

### Helix log

thread 'main' panicked at helix-term/src/ui/prompt.rs:404:34:
attempt to divide by zero

### Platform

arch linux

### Terminal Emulator

alacritty

### Installation Method

pacman

### Helix Version

helix 23.10

### PR DESCRIPTION
**Pull request by diegostafa**
fixes #9523

### CODE REVIEW

File: helix-term/src/ui/prompt.rs [hunk 1]
```diff
@@ -401,7 +401,7 @@ impl Prompt {
 
             let offset = self
                 .selection
-                .map(|selection| selection / items * items)
+                .map(|selection| selection / std::cmp::max(1, items * items))
```
Comment (the-mikedavis) [inline helix-term/src/ui/prompt.rs:404]: `/` and `*` are left-to-right associative in Rust but this is grouping them right-to-left: before it was `(selection / items) * items` but now it's `selection / (items * items)`.

Let's leave this expression untouched instead and check that `completion_area.height > 0` in the `if` condition for this block. Figuring out the offset doesn't make sense when there are no items and there's no need to try to render the completion popup if we don't have space for it

**Review by the-mikedavis — CHANGES_REQUESTED** [review]

**Review by the-mikedavis — APPROVED** [review]
