### PR TITLE
Fix find commands for buffers with non-LF line-endings

### LINKED ISSUE #8057: T<ret> on windows selects the previous newline
### Summary

Pressing `T<ret>` on a line of text has the same effect as pressing `F<ret>`, the previous newline is selected:

image

Note that setting line-ending to `lf` makes `T` behave correctly.

### Reproduction Steps

1. Put cursor on a line of text.
2. Press `T<ret>`

### Platform

Windows

### Terminal Emulator

Windows Terminal Version: 1.17.11461.0

### Helix Version

helix 23.05 (7f5940be)

### PR DESCRIPTION
**Pull request by woojiq**
Adds separate method for finding `<ret>` char.

Closes #8057 

Resolves TODO: https://github.com/helix-editor/helix/blob/79c04251547e6c0c21366d322e268a6581c0f5dd/helix-term/src/commands.rs#L1270-L1273

### CODE REVIEW

**Review by pascalkuthe — COMMENTED** [review]
I think this is an ok fix but I think a better solution would be to special case this branch. And just use ropey to find the next line ending/start from the cursor (look at the implementation of gl/gh). That should be faster and correctly handle files with mixed line endings (resolving the TODO comment here)

**Comment by woojiq** [comment]
Done. Thank you for the suggestion. There are some edge cases thought. Comments explain them more clearly.

File: helix-term/src/commands.rs [hunk 1]
```diff
@@ -1253,6 +1253,69 @@ fn extend_next_long_word_end(cx: &mut Context) {
...
+                } else {
+                    line as usize
+                }
+            }
+        };
+
+        let pos = match (direction, inclusive) {
+            (Direction::Forward, true) => line_end_char_index(&text, find_on_line),
+            (Direction::Forward, false) => {
+                graphemes::prev_grapheme_boundary(text, line_end_char_index(&text, find_on_line))
```
Comment (pascalkuthe) [inline helix-term/src/commands.rs:1302]: nit: I know other parts of the codebase do the same thing but selections will be normalized to grapheme boundaries anyway so you can just do `line_end_char_index(...) - 1` instead and it will be a bit more efficient

File: helix-term/src/commands.rs [hunk 2]
```diff
@@ -1253,6 +1253,69 @@ fn extend_next_long_word_end(cx: &mut Context) {
...
+            }
+            (Direction::Backward, true) => {
+                graphemes::prev_grapheme_boundary(text, text.line_to_char(find_on_line))
```
Comment (pascalkuthe) [inline helix-term/src/commands.rs:1305]:
```suggestion
                line_end_char_index(&text, find_on_line)
```

this is more consistent with the line above (and also a tiny bit faster)

**Review by pascalkuthe — COMMENTED** [review]
this looks very nice, some style nits but it seems like you covered all edgecases :+1:

**Review by pascalkuthe — APPROVED** [review]

File: helix-term/src/commands.rs [hunk 3]
```diff
@@ -1266,13 +1325,9 @@ fn find_char(cx: &mut Context, direction: Direction, inclusive: bool, extend: bo
...
                 ..
-            } =>
-            // TODO: this isn't quite correct when CRLF is involved.
-            // This hack will work in most cases, since documents don't
-            // usually mix line endings.  But we should fix it eventually
-            // anyway.
-            {
-                doc!(cx.editor).line_ending.as_str().chars().next().unwrap()
+            } => {
+                find_char_ret(cx, count, direction, inclusive, extend);
```
Comment (the-mikedavis) [inline helix-term/src/commands.rs:1329]: minor nit: let's call this `find_line_ending` instead

**Review by pascalkuthe — DISMISSED** [review]

File: helix-term/src/commands.rs (hunk 3 above)
Comment (the-mikedavis) [reply helix-term/src/commands.rs]: Specifically I'm looking for "line ending" to be in the name since we use that language consistently throughout the codebase & docs. `find_char_ending` I think is ambiguous but `find_char_line_ending` / `find_line_ending_char` etc would be good

Comment (woojiq) [reply helix-term/src/commands.rs]: Oops 😅

**Review by the-mikedavis — APPROVED** [review]

**Review by pascalkuthe — APPROVED** [review]
