### PR TITLE
Make repeat operator work with completion edits

### LINKED ISSUE #1517: 'Repeat Last Change' not working with autocompletion
Using an autocompletion in insert mode, then repeating the last change with `.` won't paste the autocompletion but the characters used to choose the autocompletion entry.

### Reproduction steps

* Go in insert mode
* Use an autocompletion
* Go in normal mode
* use `.` to paste last modification 

Instead of the completion, It will paste the keys pressed to select the completion, not the actual completed text.
I.e. choosing a completion with  `tab` will paste a tab in place of the completed text,  with `C-j` will paste a j, with `down` will go next line and override text below, … 

Peek 2022-01-15 08-35

### Environment

- Platform: Linux
- Helix version: master branch (v0.5.0-373-g3a34036)

### PR DESCRIPTION
**Pull request by matszczygiel**
This hopefully fixes the problem with repeating last change when code action occurred. Closes #1517

### CODE REVIEW

**Comment by matszczygiel** [comment]
Unfortunately, there are still some problems . It is not ready to merge yet.

File: helix-term/src/ui/completion.rs [hunk 1]
```diff
@@ -114,7 +117,63 @@ impl Completion {
...
+                    let text = text.trim_start_matches::<&str>(&prefix).to_owned();
+                    CompleteAction {
+                        start: 0,
+                        end: 0,
+                        text,
+                    }
+                };
+
+                Some(action)
             }
```
[the remark this answers is not in the document]
Comment (matszczygiel) [reply helix-term/src/ui/completion.rs]: I applied your suggestion. It worked pretty well.

**Comment by matszczygiel** [comment]
According to my humble testing it works now. @archseer could you please take a look ?

File: helix-term/src/ui/editor.rs [hunk 2]
```diff
@@ -735,8 +742,35 @@ impl EditorView {
...
+                            log::error!("Replaying completion: {compl:?}");
+
+                            let shift_position =
+                                |pos: usize| -> usize { pos + cursor - compl.trigger_pos };
+
+                            let tx = Transaction::change(
+                                doc.text(),
+                                compl.transaction.changes_iter().map(|(start, end, t)| {
+                                    (shift_position(start), shift_position(end), t)
+                                }),
```
Comment (archseer) [inline helix-term/src/ui/editor.rs:765]: This will can include multiple changes like new imports being added. You will want to find and use only the single change where trigger position was between start and end.

File: helix-term/src/ui/completion.rs [hunk 3]
```diff
@@ -138,8 +144,11 @@ impl Completion {
 
                     // initialize a savepoint
                     doc.savepoint();
-
                     doc.apply(&transaction, view.id);
+                    editor.last_completion = Some(CompleteAction {
+                        trigger_pos: trigger_offset,
```
Comment (archseer) [inline helix-term/src/ui/completion.rs:149]: Let's name the field `trigger_offset`

File: helix-term/src/ui/editor.rs [hunk 4]
```diff
@@ -999,6 +1033,12 @@ impl Component for EditorView {
                                     consumed = true;
 
                                     if callback.is_some() {
+                                        if let Some(compl) = cx.editor.last_completion.take() {
+                                            self.last_insert
+                                                .1
+                                                .push(InsertEvent::CompletionApply(compl));
+                                        }
```
Comment (archseer) [inline helix-term/src/ui/editor.rs:1040]: If the event was consumed (even to just close the prompt), then no command was ran == no text edits. Remove this and keep the one below on line 1050

File: helix-view/src/editor.rs [hunk 5]
```diff
@@ -249,9 +249,17 @@ pub struct Editor {
     pub idle_timer: Pin<Box<Sleep>>,
     pub last_motion: Option<Motion>,
 
+    pub last_completion: Option<CompleteAction>,
+
     pub exit_code: i32,
 }
 
+#[derive(Default, Debug, Clone)]
```
Comment (archseer) [inline helix-view/src/editor.rs:257]: Is `Default` necessary here?

**Review by archseer — CHANGES_REQUESTED** [review]

File: helix-term/src/ui/editor.rs (hunk 2 above)
Comment (matszczygiel) [reply helix-term/src/ui/editor.rs]: Changed that. The only thing that bothers me is doing this `filter_map` on every replay. Maybe there is some way to cache that. On the other hand this code does not run when replay is not used.
I didn't noticed any lag when replaying on the release build though, so maybe such micro optimization is not worth it.
@archseer what do you think ?

File: helix-term/src/ui/editor.rs [hunk 6]
```diff
@@ -735,8 +742,38 @@ impl EditorView {
...
+                                            (shift_position(start), shift_position(end), t)
+                                        })
+                                    }),
+                            );
+                            doc.apply(&tx, view.id);
+                        }
+                        InsertEvent::TriggerCompletion => {
+                            let (_, doc) = current!(cxt.editor);
+                            doc.savepoint();
+                        }
```
Comment (archseer) [inline helix-term/src/ui/editor.rs:775]: I don't think this is necessary, it's just for reverting completion changes when you tab through the completion menu. I'd remove `InsertEvent::TriggerCompletion`

File: helix-term/src/ui/editor.rs [hunk 7]
```diff
@@ -735,8 +742,38 @@ impl EditorView {
...
+                            let tx = Transaction::change(
+                                doc.text(),
+                                compl
+                                    .transaction
+                                    .changes_iter()
+                                    .filter_map(|(start, end, t)| {
+                                        (start..=end).contains(&compl.trigger_offset).then(|| {
+                                            (shift_position(start), shift_position(end), t)
+                                        })
+                                    }),
```
Comment (archseer) [inline helix-term/src/ui/editor.rs:768]: > The only thing that bothers me is doing this filter_map on every replay. Maybe there is some way to cache that.

Let's do the filter_map inside `ui::completion` and store a `Vec<Change>` on the CompleteAction instead.

File: helix-view/src/editor.rs [hunk 8]
```diff
@@ -249,9 +249,17 @@ pub struct Editor {
     pub idle_timer: Pin<Box<Sleep>>,
     pub last_motion: Option<Motion>,
 
+    pub last_completion: Option<CompleteAction>,
+
     pub exit_code: i32,
 }
 
+#[derive(Debug, Clone)]
```
Comment (archseer) [inline helix-view/src/editor.rs:257]: Does this need to be `Clone`?

File: helix-term/src/ui/editor.rs [hunk 9]
```diff
@@ -34,12 +34,19 @@ use tui::buffer::Buffer as Surface;
...
     keymaps: Keymaps,
     on_next_key: Option<Box<dyn FnOnce(&mut commands::Context, KeyEvent)>>,
-    last_insert: (commands::MappableCommand, Vec<KeyEvent>),
+    last_insert: (commands::MappableCommand, Vec<InsertEvent>),
     pub(crate) completion: Option<Completion>,
     spinners: ProgressSpinners,
     autoinfo: Option<Info>,
 }
 
+#[derive(Debug, Clone)]
```
Comment (archseer) [inline helix-term/src/ui/editor.rs:43]: Does this need to be `Clone`?

File: helix-term/src/ui/editor.rs (hunk 6 above)
Comment (matszczygiel) [reply helix-term/src/ui/editor.rs:775]: Actually I think it is. When I remove this, the completion changes are applied after the text typed by the user.
Peek 2022-02-17 16-02

File: helix-term/src/ui/editor.rs (hunk 7 above)
Comment (matszczygiel) [reply helix-term/src/ui/editor.rs:768]: Ok

File: helix-view/src/editor.rs (hunk 8 above)
Comment (matszczygiel) [reply helix-view/src/editor.rs:257]: Yes, because of this `clone` https://github.com/helix-editor/helix/blob/master/helix-term/src/ui/editor.rs#L769

File: helix-term/src/ui/editor.rs (hunk 9 above)
Comment (matszczygiel) [reply helix-term/src/ui/editor.rs:43]: Same as in case of `CompleteAction`

File: helix-term/src/ui/editor.rs (hunk 6 above)
Comment (archseer) [reply helix-term/src/ui/editor.rs:770]: Ah right, because you also have that `doc.restore` on L751. You should remove both `savepoint()` and `restore()` then it should work.

Comment (matszczygiel) [reply helix-term/src/ui/editor.rs:770]: @archseer it's the same story when I remove both lines. The `save`  and `restore` logic is copied from completion logic. Otherwise it doesn't work.

Comment (archseer) [reply helix-term/src/ui/editor.rs:770]: Ah right. This is what happens:

`std::` <- completion triggers, doc.savepoint() is called
`std::thre` <- filters completion items
`Enter` <- clears back to save point `std::` then applies the completion.

I'll do some testing to see if I can avoid that.

**Comment by archseer** [comment]
Thanks for working on this! I'll merge this as is since it fixes a big annoyance. I'll see if I can remove `snapshot()`/`restore()` in a follow up.
