### PR TITLE
Fix snippet parsing

### LINKED ISSUE #6288: LSP snippet: Golang completion error
### Summary

golang textDocument/completion

List of completion returned in response,  where the ordinal number of newText starts at 1, not 0, I don't know if that's what's causing it.

For example, typing `fmt.Println` yields `fmt.Println(<cursor>`, this should be `fmt.Println(<cursor>)` .

WX20230313-111324

response data like this:

```diff
{
  "jsonrpc": "2.0",
  "result": {
    "isIncomplete": true,
    "items": [
      {
        "label": "Append",
        "kind": 3,
        "detail": "func(b []byte, a ...any) []byte",
        "documentation": "Append formats using the default formats for its operands, appends the result to\nthe byte slice, and returns the updated slice.\n",
        "preselect": true,
        "sortText": "00000",
        "filterText": "Append",
        "insertTextFormat": 2,
        "textEdit": {
          "range": {
            "start": {
              "line": 5,
              "character": 5
            },
            "end": {
              "line": 5,
              "character": 5
            }
          },
+          "newText": "Append(${1:})"
        }
      },
      {
        "label": "Appendf",
        "kind": 3,
        "detail": "func(b []byte, format string, a ...any) []byte",
        "documentation": "Appendf formats according to a format specifier, appends the result to the byte\nslice, and returns the updated slice.\n",
        "sortText": "00001",
        "filterText": "Appendf",
        "insertTextFormat": 2,
        "textEdit": {
          "range": {
            "start": {
              "line": 5,
              "character": 5
            },
            "end": {
              "line": 5,
              "character": 5
            }
          },
+          "newText": "Appendf(${1:})"
        }
      },
      {
        "label": "Appendln",
        "kind": 3,
        "detail": "func(b []byte, a ...any) []byte",
        "documentation": "Appendln formats using the default formats for its operands, appends the result\nto the byte slice, and returns the updated slice. Spaces are always added\nbetween operands and a newline is appended.\n",
        "sortText": "00002",
        "filterText": "Appendln",
        "insertTextFormat": 2,
        "textEdit": {
          "range": {
            "start": {
              "line": 5,
              "character": 5
            },
            "end": {
              "line": 5,
              "character": 5
            }
          },
 +         "newText": "Appendln(${1:})"
        }
      },
      {
        "label": "Errorf",
        "kind": 3,
        "detail": "func(format string, a ...any) error",
        "documentation": "Errorf formats according to a format specifier and returns the string as a\nvalue that satisfies error.\n\nIf the format specifier includes a %w verb with an error operand,\nthe returned error will implement an Unwrap method returning the operand.\nIf there is more than one %w verb, the returned error will implement an\nUnwrap method returning a []error containing all the %w operands in the\norder they appear in the arguments.\nIt is invalid to supply the %w verb with an operand that does not implement\nthe error interface. The %w verb is otherwise a synonym for %v.\n",
        "sortText": "00003",
        "filterText": "Errorf",
        "insertTextFormat": 2,
        "textEdit": {
          "range": {
            "start": {
              "line": 5,
              "character": 5
            },
            "end": {
              "line": 5,
              "character": 5
            }
          },
+          "newText": "Errorf(${1:})"
        }
      },
      // ...
    ]
  },
  "id": 10
}
```

### Reproduction Steps

 

I tried this:

```shell
mkdir hello
cd hello
go mod init hello
touch main.go
hx main.go
```

```go
package main

import "fmt"

func main() {
	fmt.Println( // <---- here
}
```

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-03-13T10:48:03.382 helix_lsp::transport [INFO] -> {"jsonrpc":"2.0","method":"textDocument/completion","params":{"position":{"character":5,"line":4},"textDocument":{"uri":"file:///Users/erasin/hello/main.go"}},"id":8}
2023-03-13T10:48:03.388 helix_lsp::transport [INFO] <- {"jsonrpc":"2.0","result":{"isIncomplete":true,"items":[{"label":"Append","kind":6,"detail":"(from \"fmt\")","preselect":true,"sortText":"00000","filterText":"Append","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Append"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Appendf","kind":6,"detail":"(from \"fmt\")","sortText":"00001","filterText":"Appendf","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Appendf"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Appendln","kind":6,"detail":"(from \"fmt\")","sortText":"00002","filterText":"Appendln","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Appendln"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Errorf","kind":6,"detail":"(from \"fmt\")","sortText":"00003","filterText":"Errorf","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Errorf"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Formatter","kind":6,"detail":"(from \"fmt\")","sortText":"00004","filterText":"Formatter","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Formatter"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Fprint","kind":6,"detail":"(from \"fmt\")","sortText":"00005","filterText":"Fprint","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Fprint"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Fprintf","kind":6,"detail":"(from \"fmt\")","sortText":"00006","filterText":"Fprintf","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Fprintf"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Fprintln","kind":6,"detail":"(from \"fmt\")","sortText":"00007","filterText":"Fprintln","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Fprintln"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Fscan","kind":6,"detail":"(from \"fmt\")","sortText":"00008","filterText":"Fscan","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Fscan"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Fscanf","kind":6,"detail":"(from \"fmt\")","sortText":"00009","filterText":"Fscanf","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Fscanf"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Fscanln","kind":6,"detail":"(from \"fmt\")","sortText":"00010","filterText":"Fscanln","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Fscanln"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"GoStringer","kind":6,"detail":"(from \"fmt\")","sortText":"00011","filterText":"GoStringer","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"GoStringer"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Print","kind":6,"detail":"(from \"fmt\")","sortText":"00012","filterText":"Print","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Print"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Printf","kind":6,"detail":"(from \"fmt\")","sortText":"00013","filterText":"Printf","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Printf"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Println","kind":6,"detail":"(from \"fmt\")","sortText":"00014","filterText":"Println","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Println"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Scan","kind":6,"detail":"(from \"fmt\")","sortText":"00015","filterText":"Scan","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Scan"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"ScanState","kind":6,"detail":"(from \"fmt\")","sortText":"00016","filterText":"ScanState","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"ScanState"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Scanf","kind":6,"detail":"(from \"fmt\")","sortText":"00017","filterText":"Scanf","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Scanf"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Scanln","kind":6,"detail":"(from \"fmt\")","sortText":"00018","filterText":"Scanln","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Scanln"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Scanner","kind":6,"detail":"(from \"fmt\")","sortText":"00019","filterText":"Scanner","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Scanner"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Sprint","kind":6,"detail":"(from \"fmt\")","sortText":"00020","filterText":"Sprint","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Sprint"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Sprintf","kind":6,"detail":"(from \"fmt\")","sortText":"00021","filterText":"Sprintf","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Sprintf"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Sprintln","kind":6,"detail":"(from \"fmt\")","sortText":"00022","filterText":"Sprintln","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Sprintln"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Sscan","kind":6,"detail":"(from \"fmt\")","sortText":"00023","filterText":"Sscan","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Sscan"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Sscanf","kind":6,"detail":"(from \"fmt\")","sortText":"00024","filterText":"Sscanf","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Sscanf"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Sscanln","kind":6,"detail":"(from \"fmt\")","sortText":"00025","filterText":"Sscanln","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Sscanln"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"State","kind":6,"detail":"(from \"fmt\")","sortText":"00026","filterText":"State","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"State"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]},{"label":"Stringer","kind":6,"detail":"(from \"fmt\")","sortText":"00027","filterText":"Stringer","insertTextFormat":2,"textEdit":{"range":{"start":{"line":4,"character":5},"end":{"line":4,"character":5}},"newText":"Stringer"},"additionalTextEdits":[{"range":{"start":{"line":1,"character":0},"end":{"line":1,"character":0}},"newText":"\nimport \"fmt\"\n"}]}]},"id":8}
```

</details>

### Platform

macos

### Terminal Emulator

alacritty 0.13

### Helix Version

helix (master branch 14f1a62367fe70456201c0a64174b643cf294fdd)

### PR DESCRIPTION
**Pull request by pascalkuthe**
There were multiple smaller bugs in the snippet parser.
This PR fixes them, I have included a more detailed explanation
in each commit.

Fixes #6288 and additional bugs mentioned in comments there and in #6293.

It turns out that #6293 was the correct fix. We can not allow an empty string in `text` on `zero_or_more`/`one_or_more` combinations because that would always cause an infinite loop (the parser would keep succeeding without advancing the input). Furthermore, it was correct that we were using a list here. That's how VSCode works and how other parts of the standard describe it too. I think the grammar is simply wrong here. I left a comment in the sourcecode explaining that.

However, #6288 should have never occurred even with that bug. The snippet parser should have reported an error instead. The reason it didn't was that the snippet parser simply returned any text it hadn't parsed, but we never checked that that text was actually empty. I made sure we do check that all text is actually parsed to avoid accepting snippets that fail to parse in the future.

Finally, after the comments from @the-mikedavis on #6293 I looked into the text parsing some more and found that we didn't handle escape sequences quite right which required a slightly larger change to the `text` combinatior to fix (in the process I also cleaned the function up a bit and allowed it to match empty strings where it doesn't cause an infinite loop)

### CODE REVIEW

**Comment by erasin** [comment]
LGTM, thanks fix this issues.

File: helix-lsp/src/snippet.rs [hunk 1]
```diff
@@ -368,23 +396,37 @@ mod parser {
...
+    }
+
+    pub fn parse_all(s: &str) -> Result<Snippet, &str> {
+        parse(s).and_then(|(remainder, snippet)| {
+            if remainder.is_empty() {
+                Ok(snippet)
+            } else {
+                Err(remainder)
+            }
+        })
```
Comment (the-mikedavis) [inline helix-lsp/src/snippet.rs:429]: This seems like a reasonable behavior for `parse`. Can we just replace `parse` with the `parse_all` implementation?

**Review by the-mikedavis — COMMENTED** [review]
These changes look good 👍

Just some minor comments/questions

File: helix-lsp/src/snippet.rs (hunk 1 above)
Comment (pascalkuthe) [reply helix-lsp/src/snippet.rs]: yeah, good point this makes the diff smaller too :+1:  I was thinking we might want to parse a snippet with something else afterward but we can just use `snippet().parse(text)` then
