### PR TITLE
Consider actual indentation of previous line for smart indent

### LINKED ISSUE #6235: C/C++ `namespace` incorrect indentation
### Summary

When I define a namespace, the indentation doesn't behave as expected, instead behaving as a top level statement.

VSCode

https://user-images.githubusercontent.com/79347623/224097721-d698f7b4-e592-4d94-a3f8-74146f135721.mov

Helix

https://user-images.githubusercontent.com/79347623/224097794-42410218-ec41-47b0-9d16-82ef7e671f11.mov

### Reproduction Steps

 

I tried this:

1. `hx main.cpp`
2. Declare a namespace
3. Any declaration inside the namespace will have incorrect indentation.

I expected this to happen:
Correct indentation.

Instead, this happened:
No indentation.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```

2023-03-09T10:56:25.746 helix_lsp::transport [ERROR] err <- "I[10:56:25.745] Homebrew clangd version 12.0.1\n"
2023-03-09T10:56:25.747 helix_lsp::transport [ERROR] err <- "I[10:56:25.746] PID: 80470\n"
2023-03-09T10:56:25.747 helix_lsp::transport [ERROR] err <- "I[10:56:25.746] Working directory: /Users/roger/Documents/Dev/up/pa/sesion-11\n"
2023-03-09T10:56:25.747 helix_lsp::transport [ERROR] err <- "I[10:56:25.746] argv[0]: /opt/homebrew/opt/llvm@12/bin/clangd\n"
2023-03-09T10:56:25.747 helix_lsp::transport [ERROR] err <- "I[10:56:25.747] Starting LSP over stdin/stdout\n"
2023-03-09T10:56:25.749 helix_lsp::transport [ERROR] err <- "I[10:56:25.748] <-- initialize(0)\n"
2023-03-09T10:56:25.769 helix_lsp::transport [ERROR] err <- "I[10:56:25.769] --> reply:initialize(0) 20 ms\n"
2023-03-09T10:56:25.770 helix_lsp::transport [ERROR] err <- "I[10:56:25.770] <-- initialized\n"
2023-03-09T10:56:25.770 helix_lsp::transport [ERROR] err <- "I[10:56:25.770] <-- textDocument/didOpen\n"
2023-03-09T10:56:25.771 helix_lsp::transport [ERROR] err <- "I[10:56:25.771] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:25.771 helix_lsp::transport [ERROR] err <- "I[10:56:25.771] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 0 with command clangd fallback\n"
2023-03-09T10:56:25.771 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:25.771 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:25.825 helix_lsp::transport [ERROR] err <- "I[10:56:25.825] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:26.390 helix_lsp::transport [ERROR] err <- "I[10:56:26.390] <-- textDocument/signatureHelp(1)\n"
2023-03-09T10:56:26.401 helix_lsp::transport [ERROR] err <- "I[10:56:26.401] --> reply:textDocument/signatureHelp(1) 11 ms\n"
2023-03-09T10:56:26.824 helix_lsp::transport [ERROR] err <- "I[10:56:26.824] <-- textDocument/didChange\n"
2023-03-09T10:56:26.854 helix_lsp::transport [ERROR] err <- "I[10:56:26.854] <-- textDocument/completion(2)\n"
2023-03-09T10:56:26.860 helix_lsp::transport [ERROR] err <- "I[10:56:26.860] Code complete: sema context TopLevel, query scopes [] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:26.860 helix_lsp::transport [ERROR] err <- "I[10:56:26.860] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:26.860 helix_lsp::transport [ERROR] err <- "I[10:56:26.860] --> reply:textDocument/completion(2) 5 ms\n"
2023-03-09T10:56:26.879 helix_lsp::transport [ERROR] err <- "I[10:56:26.879] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:26.879 helix_lsp::transport [ERROR] err <- "I[10:56:26.879] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 1 with command clangd fallback\n"
2023-03-09T10:56:26.879 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:26.879 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:26.909 helix_lsp::transport [ERROR] err <- "I[10:56:26.909] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:27.115 helix_lsp::transport [ERROR] err <- "I[10:56:27.115] <-- textDocument/didChange\n"
2023-03-09T10:56:27.148 helix_lsp::transport [ERROR] err <- "I[10:56:27.148] <-- textDocument/completion(3)\n"
2023-03-09T10:56:27.152 helix_lsp::transport [ERROR] err <- "I[10:56:27.152] Code complete: sema context TopLevel, query scopes [] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:27.152 helix_lsp::transport [ERROR] err <- "I[10:56:27.152] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:27.152 helix_lsp::transport [ERROR] err <- "I[10:56:27.152] --> reply:textDocument/completion(3) 4 ms\n"
2023-03-09T10:56:27.170 helix_lsp::transport [ERROR] err <- "I[10:56:27.170] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:27.171 helix_lsp::transport [ERROR] err <- "I[10:56:27.171] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 2 with command clangd fallback\n"
2023-03-09T10:56:27.171 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:27.171 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:27.180 helix_lsp::transport [ERROR] err <- "I[10:56:27.180] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:27.225 helix_lsp::transport [ERROR] err <- "I[10:56:27.225] <-- textDocument/didChange\n"
2023-03-09T10:56:27.258 helix_lsp::transport [ERROR] err <- "I[10:56:27.258] <-- textDocument/completion(4)\n"
2023-03-09T10:56:27.263 helix_lsp::transport [ERROR] err <- "I[10:56:27.263] Code complete: sema context TopLevel, query scopes [] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:27.263 helix_lsp::transport [ERROR] err <- "I[10:56:27.263] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:27.263 helix_lsp::transport [ERROR] err <- "I[10:56:27.263] --> reply:textDocument/completion(4) 4 ms\n"
2023-03-09T10:56:27.280 helix_lsp::transport [ERROR] err <- "I[10:56:27.280] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:27.281 helix_lsp::transport [ERROR] err <- "I[10:56:27.281] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 3 with command clangd fallback\n"
2023-03-09T10:56:27.281 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:27.281 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:27.289 helix_lsp::transport [ERROR] err <- "I[10:56:27.289] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:27.302 helix_lsp::transport [ERROR] err <- "I[10:56:27.302] <-- textDocument/didChange\n"
2023-03-09T10:56:27.335 helix_lsp::transport [ERROR] err <- "I[10:56:27.335] <-- textDocument/completion(5)\n"
2023-03-09T10:56:27.339 helix_lsp::transport [ERROR] err <- "I[10:56:27.339] Code complete: sema context TopLevel, query scopes [] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:27.339 helix_lsp::transport [ERROR] err <- "I[10:56:27.339] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:27.339 helix_lsp::transport [ERROR] err <- "I[10:56:27.339] --> reply:textDocument/completion(5) 4 ms\n"
2023-03-09T10:56:27.354 helix_lsp::transport [ERROR] err <- "I[10:56:27.354] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:27.354 helix_lsp::transport [ERROR] err <- "I[10:56:27.354] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 4 with command clangd fallback\n"
2023-03-09T10:56:27.354 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:27.354 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:27.363 helix_lsp::transport [ERROR] err <- "I[10:56:27.363] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:27.771 helix_lsp::transport [ERROR] err <- "I[10:56:27.771] <-- textDocument/didChange\n"
2023-03-09T10:56:27.773 helix_lsp::transport [ERROR] err <- "I[10:56:27.773] <-- textDocument/signatureHelp(6)\n"
2023-03-09T10:56:27.783 helix_lsp::transport [ERROR] err <- "I[10:56:27.783] --> reply:textDocument/signatureHelp(6) 10 ms\n"
2023-03-09T10:56:27.802 helix_lsp::transport [ERROR] err <- "I[10:56:27.802] <-- textDocument/completion(7)\n"
2023-03-09T10:56:27.805 helix_lsp::transport [ERROR] err <- "I[10:56:27.805] Code complete: sema context TopLevel, query scopes [] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:27.805 helix_lsp::transport [ERROR] err <- "I[10:56:27.805] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:27.805 helix_lsp::transport [ERROR] err <- "I[10:56:27.805] --> reply:textDocument/completion(7) 3 ms\n"
2023-03-09T10:56:27.826 helix_lsp::transport [ERROR] err <- "I[10:56:27.826] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:27.826 helix_lsp::transport [ERROR] err <- "I[10:56:27.826] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 5 with command clangd fallback\n"
2023-03-09T10:56:27.826 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:27.826 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:27.836 helix_lsp::transport [ERROR] err <- "I[10:56:27.836] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:27.920 helix_lsp::transport [ERROR] err <- "I[10:56:27.920] <-- textDocument/didChange\n"
2023-03-09T10:56:27.921 helix_lsp::transport [ERROR] err <- "I[10:56:27.921] <-- textDocument/signatureHelp(8)\n"
2023-03-09T10:56:27.932 helix_lsp::transport [ERROR] err <- "I[10:56:27.931] --> reply:textDocument/signatureHelp(8) 10 ms\n"
2023-03-09T10:56:27.952 helix_lsp::transport [ERROR] err <- "I[10:56:27.952] <-- textDocument/completion(9)\n"
2023-03-09T10:56:27.955 helix_lsp::transport [ERROR] err <- "I[10:56:27.955] Code complete: sema context TopLevel, query scopes [] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:27.955 helix_lsp::transport [ERROR] err <- "I[10:56:27.955] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:27.955 helix_lsp::transport [ERROR] err <- "I[10:56:27.955] --> reply:textDocument/completion(9) 3 ms\n"
2023-03-09T10:56:27.975 helix_lsp::transport [ERROR] err <- "I[10:56:27.975] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:27.975 helix_lsp::transport [ERROR] err <- "I[10:56:27.975] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 6 with command clangd fallback\n"
2023-03-09T10:56:27.975 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:27.975 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:27.983 helix_lsp::transport [ERROR] err <- "I[10:56:27.983] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:28.062 helix_lsp::transport [ERROR] err <- "I[10:56:28.062] <-- textDocument/didChange\n"
2023-03-09T10:56:28.063 helix_lsp::transport [ERROR] err <- "I[10:56:28.063] <-- textDocument/signatureHelp(10)\n"
2023-03-09T10:56:28.074 helix_lsp::transport [ERROR] err <- "I[10:56:28.074] --> reply:textDocument/signatureHelp(10) 10 ms\n"
2023-03-09T10:56:28.094 helix_lsp::transport [ERROR] err <- "I[10:56:28.094] <-- textDocument/completion(11)\n"
2023-03-09T10:56:28.097 helix_lsp::transport [ERROR] err <- "I[10:56:28.097] Code complete: sema context TopLevel, query scopes [] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:28.098 helix_lsp::transport [ERROR] err <- "I[10:56:28.098] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:28.098 helix_lsp::transport [ERROR] err <- "I[10:56:28.098] --> reply:textDocument/completion(11) 3 ms\n"
2023-03-09T10:56:28.113 helix_lsp::transport [ERROR] err <- "I[10:56:28.113] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:28.113 helix_lsp::transport [ERROR] err <- "I[10:56:28.113] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 7 with command clangd fallback\n"
2023-03-09T10:56:28.113 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:28.113 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:28.121 helix_lsp::transport [ERROR] err <- "I[10:56:28.121] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:28.208 helix_lsp::transport [ERROR] err <- "I[10:56:28.208] <-- textDocument/didChange\n"
2023-03-09T10:56:28.210 helix_lsp::transport [ERROR] err <- "I[10:56:28.210] <-- textDocument/signatureHelp(12)\n"
2023-03-09T10:56:28.221 helix_lsp::transport [ERROR] err <- "I[10:56:28.221] --> reply:textDocument/signatureHelp(12) 11 ms\n"
2023-03-09T10:56:28.259 helix_lsp::transport [ERROR] err <- "I[10:56:28.259] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:28.260 helix_lsp::transport [ERROR] err <- "I[10:56:28.260] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 8 with command clangd fallback\n"
2023-03-09T10:56:28.260 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:28.260 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:28.288 helix_lsp::transport [ERROR] err <- "I[10:56:28.288] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:28.557 helix_lsp::transport [ERROR] err <- "I[10:56:28.557] <-- textDocument/didChange\n"
2023-03-09T10:56:28.590 helix_lsp::transport [ERROR] err <- "I[10:56:28.590] <-- textDocument/completion(13)\n"
2023-03-09T10:56:28.595 helix_lsp::transport [ERROR] err <- "I[10:56:28.595] Code complete: sema context TopLevel, query scopes [] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:28.595 helix_lsp::transport [ERROR] err <- "I[10:56:28.595] Code complete: 6 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 6 returned.\n"
2023-03-09T10:56:28.596 helix_lsp::transport [ERROR] err <- "I[10:56:28.596] --> reply:textDocument/completion(13) 5 ms\n"
2023-03-09T10:56:28.612 helix_lsp::transport [ERROR] err <- "I[10:56:28.612] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:28.612 helix_lsp::transport [ERROR] err <- "I[10:56:28.612] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 9 with command clangd fallback\n"
2023-03-09T10:56:28.612 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:28.612 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:28.641 helix_lsp::transport [ERROR] err <- "I[10:56:28.641] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:28.678 helix_lsp::transport [ERROR] err <- "I[10:56:28.678] <-- textDocument/didChange\n"
2023-03-09T10:56:28.733 helix_lsp::transport [ERROR] err <- "I[10:56:28.733] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:28.733 helix_lsp::transport [ERROR] err <- "I[10:56:28.733] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 10 with command clangd fallback\n"
2023-03-09T10:56:28.733 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:28.733 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:28.744 helix_lsp::transport [ERROR] err <- "I[10:56:28.744] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:28.766 helix_lsp::transport [ERROR] err <- "I[10:56:28.766] <-- textDocument/didChange\n"
2023-03-09T10:56:28.822 helix_lsp::transport [ERROR] err <- "I[10:56:28.822] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:28.822 helix_lsp::transport [ERROR] err <- "I[10:56:28.822] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 11 with command clangd fallback\n"
2023-03-09T10:56:28.822 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:28.822 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:28.835 helix_lsp::transport [ERROR] err <- "I[10:56:28.835] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:28.917 helix_lsp::transport [ERROR] err <- "I[10:56:28.917] <-- textDocument/didChange\n"
2023-03-09T10:56:28.973 helix_lsp::transport [ERROR] err <- "I[10:56:28.973] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:28.973 helix_lsp::transport [ERROR] err <- "I[10:56:28.973] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 12 with command clangd fallback\n"
2023-03-09T10:56:28.973 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:28.974 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:28.987 helix_lsp::transport [ERROR] err <- "I[10:56:28.987] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:29.020 helix_lsp::transport [ERROR] err <- "I[10:56:29.020] <-- textDocument/didChange\n"
2023-03-09T10:56:29.075 helix_lsp::transport [ERROR] err <- "I[10:56:29.075] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:29.076 helix_lsp::transport [ERROR] err <- "I[10:56:29.075] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 13 with command clangd fallback\n"
2023-03-09T10:56:29.076 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:29.076 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:29.089 helix_lsp::transport [ERROR] err <- "I[10:56:29.088] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:29.337 helix_lsp::transport [ERROR] err <- "I[10:56:29.337] <-- textDocument/didChange\n"
2023-03-09T10:56:29.337 helix_lsp::transport [ERROR] err <- "I[10:56:29.337] <-- textDocument/didChange\n"
2023-03-09T10:56:29.392 helix_lsp::transport [ERROR] err <- "I[10:56:29.392] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:29.392 helix_lsp::transport [ERROR] err <- "I[10:56:29.392] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 15 with command clangd fallback\n"
2023-03-09T10:56:29.392 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:29.392 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:29.409 helix_lsp::transport [ERROR] err <- "I[10:56:29.409] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:30.142 helix_lsp::transport [ERROR] err <- "I[10:56:30.142] <-- textDocument/didChange\n"
2023-03-09T10:56:30.142 helix_lsp::transport [ERROR] err <- "I[10:56:30.142] <-- textDocument/didChange\n"
2023-03-09T10:56:30.198 helix_lsp::transport [ERROR] err <- "I[10:56:30.197] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:30.198 helix_lsp::transport [ERROR] err <- "I[10:56:30.198] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 17 with command clangd fallback\n"
2023-03-09T10:56:30.198 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:30.198 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:30.212 helix_lsp::transport [ERROR] err <- "I[10:56:30.212] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:31.688 helix_lsp::transport [ERROR] err <- "I[10:56:31.688] <-- textDocument/didChange\n"
2023-03-09T10:56:31.721 helix_lsp::transport [ERROR] err <- "I[10:56:31.721] <-- textDocument/completion(14)\n"
2023-03-09T10:56:31.725 helix_lsp::transport [ERROR] err <- "I[10:56:31.725] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:31.725 helix_lsp::transport [ERROR] err <- "I[10:56:31.725] --> reply:textDocument/completion(14) 3 ms\n"
2023-03-09T10:56:31.742 helix_lsp::transport [ERROR] err <- "I[10:56:31.742] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:31.742 helix_lsp::transport [ERROR] err <- "I[10:56:31.742] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 18 with command clangd fallback\n"
2023-03-09T10:56:31.742 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:31.742 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:31.751 helix_lsp::transport [ERROR] err <- "I[10:56:31.751] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:31.789 helix_lsp::transport [ERROR] err <- "I[10:56:31.789] <-- textDocument/didChange\n"
2023-03-09T10:56:31.822 helix_lsp::transport [ERROR] err <- "I[10:56:31.822] <-- textDocument/completion(15)\n"
2023-03-09T10:56:31.825 helix_lsp::transport [ERROR] err <- "I[10:56:31.825] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:31.825 helix_lsp::transport [ERROR] err <- "I[10:56:31.825] --> reply:textDocument/completion(15) 3 ms\n"
2023-03-09T10:56:31.844 helix_lsp::transport [ERROR] err <- "I[10:56:31.844] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:31.844 helix_lsp::transport [ERROR] err <- "I[10:56:31.844] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 19 with command clangd fallback\n"
2023-03-09T10:56:31.844 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:31.844 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:31.851 helix_lsp::transport [ERROR] err <- "I[10:56:31.851] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:31.884 helix_lsp::transport [ERROR] err <- "I[10:56:31.884] <-- textDocument/didChange\n"
2023-03-09T10:56:31.917 helix_lsp::transport [ERROR] err <- "I[10:56:31.917] <-- textDocument/completion(16)\n"
2023-03-09T10:56:31.922 helix_lsp::transport [ERROR] err <- "I[10:56:31.922] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:31.922 helix_lsp::transport [ERROR] err <- "I[10:56:31.922] --> reply:textDocument/completion(16) 5 ms\n"
2023-03-09T10:56:31.935 helix_lsp::transport [ERROR] err <- "I[10:56:31.935] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:31.935 helix_lsp::transport [ERROR] err <- "I[10:56:31.935] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 20 with command clangd fallback\n"
2023-03-09T10:56:31.935 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:31.935 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:31.942 helix_lsp::transport [ERROR] err <- "I[10:56:31.942] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:31.987 helix_lsp::transport [ERROR] err <- "I[10:56:31.987] <-- textDocument/didChange\n"
2023-03-09T10:56:32.019 helix_lsp::transport [ERROR] err <- "I[10:56:32.019] <-- textDocument/completion(17)\n"
2023-03-09T10:56:32.024 helix_lsp::transport [ERROR] err <- "I[10:56:32.024] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:32.024 helix_lsp::transport [ERROR] err <- "I[10:56:32.024] --> reply:textDocument/completion(17) 4 ms\n"
2023-03-09T10:56:32.042 helix_lsp::transport [ERROR] err <- "I[10:56:32.042] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:32.042 helix_lsp::transport [ERROR] err <- "I[10:56:32.042] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 21 with command clangd fallback\n"
2023-03-09T10:56:32.042 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:32.042 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:32.049 helix_lsp::transport [ERROR] err <- "I[10:56:32.049] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:32.149 helix_lsp::transport [ERROR] err <- "I[10:56:32.149] <-- textDocument/didChange\n"
2023-03-09T10:56:32.183 helix_lsp::transport [ERROR] err <- "I[10:56:32.183] <-- textDocument/completion(18)\n"
2023-03-09T10:56:32.187 helix_lsp::transport [ERROR] err <- "I[10:56:32.187] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:32.187 helix_lsp::transport [ERROR] err <- "I[10:56:32.187] --> reply:textDocument/completion(18) 3 ms\n"
2023-03-09T10:56:32.204 helix_lsp::transport [ERROR] err <- "I[10:56:32.204] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:32.204 helix_lsp::transport [ERROR] err <- "I[10:56:32.204] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 22 with command clangd fallback\n"
2023-03-09T10:56:32.204 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:32.204 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:32.213 helix_lsp::transport [ERROR] err <- "I[10:56:32.213] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:32.790 helix_lsp::transport [ERROR] err <- "I[10:56:32.790] <-- textDocument/didChange\n"
2023-03-09T10:56:32.791 helix_lsp::transport [ERROR] err <- "I[10:56:32.791] <-- textDocument/signatureHelp(19)\n"
2023-03-09T10:56:32.798 helix_lsp::transport [ERROR] err <- "I[10:56:32.798] --> reply:textDocument/signatureHelp(19) 6 ms\n"
2023-03-09T10:56:32.845 helix_lsp::transport [ERROR] err <- "I[10:56:32.845] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:32.845 helix_lsp::transport [ERROR] err <- "I[10:56:32.845] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 23 with command clangd fallback\n"
2023-03-09T10:56:32.846 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:32.846 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:32.853 helix_lsp::transport [ERROR] err <- "I[10:56:32.853] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:33.594 helix_lsp::transport [ERROR] err <- "I[10:56:33.594] <-- textDocument/didChange\n"
2023-03-09T10:56:33.626 helix_lsp::transport [ERROR] err <- "I[10:56:33.626] <-- textDocument/completion(20)\n"
2023-03-09T10:56:33.631 helix_lsp::transport [ERROR] err <- "I[10:56:33.631] Code complete: sema context TopLevel, query scopes [hello::,] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:33.631 helix_lsp::transport [ERROR] err <- "I[10:56:33.631] Code complete: 2 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 2 returned.\n"
2023-03-09T10:56:33.631 helix_lsp::transport [ERROR] err <- "I[10:56:33.631] --> reply:textDocument/completion(20) 4 ms\n"
2023-03-09T10:56:33.649 helix_lsp::transport [ERROR] err <- "I[10:56:33.649] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:33.650 helix_lsp::transport [ERROR] err <- "I[10:56:33.650] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 24 with command clangd fallback\n"
2023-03-09T10:56:33.650 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:33.650 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:33.656 helix_lsp::transport [ERROR] err <- "I[10:56:33.656] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:33.671 helix_lsp::transport [ERROR] err <- "I[10:56:33.671] <-- textDocument/didChange\n"
2023-03-09T10:56:33.726 helix_lsp::transport [ERROR] err <- "I[10:56:33.726] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:33.727 helix_lsp::transport [ERROR] err <- "I[10:56:33.727] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 25 with command clangd fallback\n"
2023-03-09T10:56:33.727 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:33.727 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:33.738 helix_lsp::transport [ERROR] err <- "I[10:56:33.738] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:33.755 helix_lsp::transport [ERROR] err <- "I[10:56:33.755] <-- textDocument/didChange\n"
2023-03-09T10:56:33.811 helix_lsp::transport [ERROR] err <- "I[10:56:33.811] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:33.811 helix_lsp::transport [ERROR] err <- "I[10:56:33.811] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 26 with command clangd fallback\n"
2023-03-09T10:56:33.811 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:33.811 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:33.823 helix_lsp::transport [ERROR] err <- "I[10:56:33.823] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:33.960 helix_lsp::transport [ERROR] err <- "I[10:56:33.960] <-- textDocument/didChange\n"
2023-03-09T10:56:34.012 helix_lsp::transport [ERROR] err <- "I[10:56:34.012] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:34.013 helix_lsp::transport [ERROR] err <- "I[10:56:34.013] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 27 with command clangd fallback\n"
2023-03-09T10:56:34.013 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:34.013 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:34.026 helix_lsp::transport [ERROR] err <- "I[10:56:34.026] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:34.130 helix_lsp::transport [ERROR] err <- "I[10:56:34.130] <-- textDocument/didChange\n"
2023-03-09T10:56:34.163 helix_lsp::transport [ERROR] err <- "I[10:56:34.163] <-- textDocument/completion(21)\n"
2023-03-09T10:56:34.167 helix_lsp::transport [ERROR] err <- "I[10:56:34.167] Code complete: sema context SymbolOrNewName, query scopes [hello::,] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:34.168 helix_lsp::transport [ERROR] err <- "I[10:56:34.168] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:34.168 helix_lsp::transport [ERROR] err <- "I[10:56:34.168] --> reply:textDocument/completion(21) 4 ms\n"
2023-03-09T10:56:34.185 helix_lsp::transport [ERROR] err <- "I[10:56:34.185] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:34.185 helix_lsp::transport [ERROR] err <- "I[10:56:34.185] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 28 with command clangd fallback\n"
2023-03-09T10:56:34.185 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:34.185 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:34.196 helix_lsp::transport [ERROR] err <- "I[10:56:34.196] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:34.204 helix_lsp::transport [ERROR] err <- "I[10:56:34.204] <-- textDocument/didChange\n"
2023-03-09T10:56:34.237 helix_lsp::transport [ERROR] err <- "I[10:56:34.237] <-- textDocument/completion(22)\n"
2023-03-09T10:56:34.239 helix_lsp::transport [ERROR] err <- "I[10:56:34.239] Code complete: sema context SymbolOrNewName, query scopes [hello::,] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:34.240 helix_lsp::transport [ERROR] err <- "I[10:56:34.240] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:34.240 helix_lsp::transport [ERROR] err <- "I[10:56:34.240] --> reply:textDocument/completion(22) 2 ms\n"
2023-03-09T10:56:34.259 helix_lsp::transport [ERROR] err <- "I[10:56:34.259] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:34.259 helix_lsp::transport [ERROR] err <- "I[10:56:34.259] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 29 with command clangd fallback\n"
2023-03-09T10:56:34.259 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:34.259 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:34.270 helix_lsp::transport [ERROR] err <- "I[10:56:34.270] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:34.329 helix_lsp::transport [ERROR] err <- "I[10:56:34.329] <-- textDocument/didChange\n"
2023-03-09T10:56:34.363 helix_lsp::transport [ERROR] err <- "I[10:56:34.363] <-- textDocument/completion(23)\n"
2023-03-09T10:56:34.368 helix_lsp::transport [ERROR] err <- "I[10:56:34.368] Code complete: sema context SymbolOrNewName, query scopes [hello::,] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:34.368 helix_lsp::transport [ERROR] err <- "I[10:56:34.368] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:34.368 helix_lsp::transport [ERROR] err <- "I[10:56:34.368] --> reply:textDocument/completion(23) 5 ms\n"
2023-03-09T10:56:34.384 helix_lsp::transport [ERROR] err <- "I[10:56:34.384] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:34.384 helix_lsp::transport [ERROR] err <- "I[10:56:34.384] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 30 with command clangd fallback\n"
2023-03-09T10:56:34.384 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:34.384 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:34.391 helix_lsp::transport [ERROR] err <- "I[10:56:34.391] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:34.597 helix_lsp::transport [ERROR] err <- "I[10:56:34.597] <-- textDocument/didChange\n"
2023-03-09T10:56:34.599 helix_lsp::transport [ERROR] err <- "I[10:56:34.599] <-- textDocument/signatureHelp(24)\n"
2023-03-09T10:56:34.609 helix_lsp::transport [ERROR] err <- "I[10:56:34.609] --> reply:textDocument/signatureHelp(24) 10 ms\n"
2023-03-09T10:56:34.650 helix_lsp::transport [ERROR] err <- "I[10:56:34.650] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:34.650 helix_lsp::transport [ERROR] err <- "I[10:56:34.650] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 31 with command clangd fallback\n"
2023-03-09T10:56:34.650 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:34.650 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:34.658 helix_lsp::transport [ERROR] err <- "I[10:56:34.658] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:35.215 helix_lsp::transport [ERROR] err <- "I[10:56:35.215] <-- textDocument/signatureHelp(25)\n"
2023-03-09T10:56:35.225 helix_lsp::transport [ERROR] err <- "I[10:56:35.225] --> reply:textDocument/signatureHelp(25) 9 ms\n"
2023-03-09T10:56:35.450 helix_lsp::transport [ERROR] err <- "I[10:56:35.450] <-- textDocument/didChange\n"
2023-03-09T10:56:35.500 helix_lsp::transport [ERROR] err <- "I[10:56:35.500] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:35.500 helix_lsp::transport [ERROR] err <- "I[10:56:35.500] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 32 with command clangd fallback\n"
2023-03-09T10:56:35.500 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:35.500 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:35.513 helix_lsp::transport [ERROR] err <- "I[10:56:35.513] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:35.705 helix_lsp::transport [ERROR] err <- "I[10:56:35.705] <-- textDocument/didChange\n"
2023-03-09T10:56:35.760 helix_lsp::transport [ERROR] err <- "I[10:56:35.760] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:35.760 helix_lsp::transport [ERROR] err <- "I[10:56:35.760] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 33 with command clangd fallback\n"
2023-03-09T10:56:35.760 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:35.760 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:35.772 helix_lsp::transport [ERROR] err <- "I[10:56:35.772] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:36.873 helix_lsp::transport [ERROR] err <- "I[10:56:36.873] <-- textDocument/didChange\n"
2023-03-09T10:56:36.907 helix_lsp::transport [ERROR] err <- "I[10:56:36.906] <-- textDocument/completion(26)\n"
2023-03-09T10:56:36.912 helix_lsp::transport [ERROR] err <- "I[10:56:36.912] Code complete: sema context Statement, query scopes [hello::,] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:36.912 helix_lsp::transport [ERROR] err <- "I[10:56:36.912] Code complete: 2 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 2 returned.\n"
2023-03-09T10:56:36.912 helix_lsp::transport [ERROR] err <- "I[10:56:36.912] --> reply:textDocument/completion(26) 5 ms\n"
2023-03-09T10:56:36.929 helix_lsp::transport [ERROR] err <- "I[10:56:36.929] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:36.929 helix_lsp::transport [ERROR] err <- "I[10:56:36.929] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 34 with command clangd fallback\n"
2023-03-09T10:56:36.929 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:36.929 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:36.939 helix_lsp::transport [ERROR] err <- "I[10:56:36.939] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:37.011 helix_lsp::transport [ERROR] err <- "I[10:56:37.011] <-- textDocument/didChange\n"
2023-03-09T10:56:37.067 helix_lsp::transport [ERROR] err <- "I[10:56:37.066] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:37.067 helix_lsp::transport [ERROR] err <- "I[10:56:37.067] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 35 with command clangd fallback\n"
2023-03-09T10:56:37.067 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:37.067 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:37.080 helix_lsp::transport [ERROR] err <- "I[10:56:37.080] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:37.157 helix_lsp::transport [ERROR] err <- "I[10:56:37.157] <-- textDocument/didChange\n"
2023-03-09T10:56:37.212 helix_lsp::transport [ERROR] err <- "I[10:56:37.212] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:37.213 helix_lsp::transport [ERROR] err <- "I[10:56:37.213] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 36 with command clangd fallback\n"
2023-03-09T10:56:37.213 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:37.213 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:37.225 helix_lsp::transport [ERROR] err <- "I[10:56:37.225] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:37.914 helix_lsp::transport [ERROR] err <- "I[10:56:37.914] <-- textDocument/didChange\n"
2023-03-09T10:56:37.914 helix_lsp::transport [ERROR] err <- "I[10:56:37.914] <-- textDocument/didChange\n"
2023-03-09T10:56:37.969 helix_lsp::transport [ERROR] err <- "I[10:56:37.969] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:37.970 helix_lsp::transport [ERROR] err <- "I[10:56:37.970] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 38 with command clangd fallback\n"
2023-03-09T10:56:37.970 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:37.970 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:37.985 helix_lsp::transport [ERROR] err <- "I[10:56:37.985] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:39.353 helix_lsp::transport [ERROR] err <- "I[10:56:39.353] <-- textDocument/didChange\n"
2023-03-09T10:56:39.353 helix_lsp::transport [ERROR] err <- "I[10:56:39.353] <-- textDocument/didChange\n"
2023-03-09T10:56:39.404 helix_lsp::transport [ERROR] err <- "I[10:56:39.404] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:39.404 helix_lsp::transport [ERROR] err <- "I[10:56:39.404] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 40 with command clangd fallback\n"
2023-03-09T10:56:39.404 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:39.404 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:39.417 helix_lsp::transport [ERROR] err <- "I[10:56:39.417] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:41.799 helix_lsp::transport [ERROR] err <- "I[10:56:41.799] <-- textDocument/signatureHelp(27)\n"
2023-03-09T10:56:41.811 helix_lsp::transport [ERROR] err <- "I[10:56:41.810] --> reply:textDocument/signatureHelp(27) 11 ms\n"
2023-03-09T10:56:41.829 helix_lsp::transport [ERROR] err <- "I[10:56:41.829] <-- textDocument/completion(28)\n"
2023-03-09T10:56:41.832 helix_lsp::transport [ERROR] err <- "I[10:56:41.832] Code complete: sema context Statement, query scopes [hello::,] (AnyScope=true), expected type <none>\n"
2023-03-09T10:56:41.832 helix_lsp::transport [ERROR] err <- "I[10:56:41.832] Code complete: 1 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 1 returned.\n"
2023-03-09T10:56:41.832 helix_lsp::transport [ERROR] err <- "I[10:56:41.832] --> reply:textDocument/completion(28) 3 ms\n"
2023-03-09T10:56:41.958 helix_lsp::transport [ERROR] err <- "I[10:56:41.958] <-- textDocument/didChange\n"
2023-03-09T10:56:42.015 helix_lsp::transport [ERROR] err <- "I[10:56:42.014] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:42.015 helix_lsp::transport [ERROR] err <- "I[10:56:42.015] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 41 with command clangd fallback\n"
2023-03-09T10:56:42.015 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:42.015 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:42.030 helix_lsp::transport [ERROR] err <- "I[10:56:42.030] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:42.701 helix_lsp::transport [ERROR] err <- "I[10:56:42.701] <-- textDocument/didChange\n"
2023-03-09T10:56:42.734 helix_lsp::transport [ERROR] err <- "I[10:56:42.734] <-- textDocument/completion(29)\n"
2023-03-09T10:56:42.739 helix_lsp::transport [ERROR] err <- "I[10:56:42.739] Code complete: 0 results from Sema, 0 from Index, 0 matched, 0 from identifiers, 0 returned.\n"
2023-03-09T10:56:42.739 helix_lsp::transport [ERROR] err <- "I[10:56:42.739] --> reply:textDocument/completion(29) 5 ms\n"
2023-03-09T10:56:42.756 helix_lsp::transport [ERROR] err <- "I[10:56:42.756] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:42.757 helix_lsp::transport [ERROR] err <- "I[10:56:42.757] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 42 with command clangd fallback\n"
2023-03-09T10:56:42.757 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:42.757 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:42.765 helix_lsp::transport [ERROR] err <- "I[10:56:42.765] --> textDocument/publishDiagnostics\n"
2023-03-09T10:56:43.480 helix_lsp::transport [ERROR] err <- "I[10:56:43.480] <-- textDocument/didSave\n"
2023-03-09T10:56:43.535 helix_lsp::transport [ERROR] err <- "I[10:56:43.535] Failed to find compilation database for /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp\n"
2023-03-09T10:56:43.535 helix_lsp::transport [ERROR] err <- "I[10:56:43.535] ASTWorker building file /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp version 42 with command clangd fallback\n"
2023-03-09T10:56:43.535 helix_lsp::transport [ERROR] err <- "[/Users/roger/Documents/Dev/up/pa/sesion-11]\n"
2023-03-09T10:56:43.535 helix_lsp::transport [ERROR] err <- "/Library/Developer/CommandLineTools/usr/bin/clang /Users/roger/Documents/Dev/up/pa/sesion-11/mainn.cpp -fsyntax-only -resource-dir=/opt/homebrew/Cellar/llvm@12/12.0.1_1/lib/clang/12.0.1 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk\n"
2023-03-09T10:56:47.738 helix_lsp::transport [ERROR] err <- "I[10:56:47.738] <-- shutdown(30)\n"
2023-03-09T10:56:47.738 helix_lsp::transport [ERROR] err <- "I[10:56:47.738] --> reply:shutdown(30) 0 ms\n"
2023-03-09T10:56:47.739 helix_lsp::transport [ERROR] err <- "I[10:56:47.739] <-- exit\n"
2023-03-09T10:56:47.739 helix_lsp::transport [ERROR] err <- "I[10:56:47.739] LSP finished, exiting with status 0\n"
2023-03-09T10:56:54.738 helix_view::editor [ERROR] editor error: no such command: 'log'


```

</details>

### Platform

macOS

### Terminal Emulator

alacritty 0.11.0 (8dbaa0b)

### Helix Version

helix 22.12 (ce1fb9e6)

### LINKED ISSUE #7206: C++ indentation is wrong for access specifiers
### Summary

Closing bracket of class methods in access specifiers is not indented properly.

```
class Foo {
  public:
    Foo() {
    
  } // missing an indent
}
```

### Reproduction Steps

Create a method after an access specifier and let helix auto indent the closing bracket. 

Expected closing bracket to be in-line with the method name.

### Helix log

_No response_

### Platform

Linux

### Terminal Emulator

foot 1.14.0

### Helix Version

helix 23.05 (3a8592ab)

### PR DESCRIPTION
**Pull request by Triton171**
Essentially, to compute the indentation of a new line, we run an indent query both for the insertion position and for a non-empty line above. Then, we add the difference of these computed indents to the actual indentation of the line above. This makes indent queries a lot more resilient: Any error / inconsistency which applies to both lines will be canceled out, e.g.:
- Incorrect / Incomplete indent queries. In particular, incomplete indent queries are no longer worse than no indent queries with this change. This should also make it easier to contribute new languages since one can start by adding a few simple captures and then gradually add more.
- Incorrect parsing of the syntax tree by tree-sitter (e.g. if the code is incomplete)
- Different formatting styles where only one can correctly be handled by indent queries. This is especially interesting for languages like Markdown and LaTex where indent queries weren't really feasible until now due to the variation in formatting.

The main thing still missing from this PR is some way to disable relative indent queries. While this shouldn't really be necessary when using Helix, relative indent computation makes debugging indent queries more difficult. Should this be an option? Or is there a better way to do it?
I also haven't tested my changes a lot, so I appreciate it if anyone wants to try it out. I'll also use it myself for some time before marking the PR ready for merging.

The only significant downside of this change is that we now compute 2 (or in rare cases 3) indent queries when inserting a new line. The time needed for this only becomes noticable when inserting a new line with many cursors at once. If this is an issue, we could disable smart indent when inserting many (e.g. > 1000) newlines at once. For now, I think it is fine though (I haven't seen any complaints about the current indent queries being slow with many cursors either).

Fixes #6235
Fixes #7206
Fixes (partially) #6939 and #1725

### CODE REVIEW

**Comment by clo4** [comment]
After I manually closed #8124, I realised it shouldn't have been because plain text is still an issue - this PR would also have closed that, given that it works great with plain text. Fantastic contribution, looking forward to when this is merged! It feels great to use.

File: helix-core/src/indent.rs [hunk 1]
```diff
@@ -849,24 +936,76 @@ pub fn indent_for_newline(
...
+                // line. This makes indentation computation more resilient to
+                // incomplete queries, incomplete source code & differing indentation
+                // styles for the same language.
+                // However, using the indent of a previous line as a baseline may not
+                // make sense, e.g. if it has a different alignment than the new line.
+                // In order to prevent edge cases with long running times, we only try
+                // a constant number of (non-empty) lines.
+                const MAX_ATTEMPTS: usize = 2;
+                let mut num_attempts = 0;
+                for line_idx in (0..=line_before).rev() {
```
Comment (pascalkuthe) [inline helix-core/src/indent.rs:970]: Instead of iterating line indecies you can use `text.lines_at(line_before + 1).reversed()` to iterate lines (it's faster/more ideomatic)

Comment (pascalkuthe) [reply helix-core/src/indent.rs:970]: You could also handle the max attempt by adding `take(MAX_ATTEMPTS)`

File: book/src/configuration.md [hunk 2]
```diff
@@ -65,6 +65,7 @@ Its settings will be merged with the configuration directory `config.toml` and t
 | `workspace-lsp-roots` | Directories relative to the workspace root that are treated as LSP roots. Should only be set in `.helix/config.toml` | `[]` |
 | `default-line-ending` | The line ending to use for new documents. Can be `native`, `lf`, `crlf`, `ff`, `cr` or `nel`. `native` uses the platform's native line ending (`crlf` on Windows, otherwise `lf`). | `native` |
 | `insert-final-newline` | Whether to automatically insert a trailing line-ending on write if missing | `true` |
+| `indent-heuristic` | How the indentation for a newly inserted line is computed: `simple` just copies the indentation level from the previous line, `tree-sitter` computes the indentation based on the syntax tree and `hybrid` combines both approaches | `hybrid`
```
[the remark this answers is not in the document]
Comment (Triton171) [reply book/src/configuration.md]: Is there a way to set a language setting for all languages at once? I think that the main use case of this option will be for debugging changes to the indent queries / heuristic, where changing the config for each relevant language might be tedious.

In case a language doesn't have queries, the `simple` heuristic is always used as a fallback (`hybrid` falls back to `tree-sitter` and `tree-sitter` falls back to `simple`). Buggy / low quality queries also shouldn't be a bug issue anymore. An empty indent query file with the `hybrid` heuristic should be essentially equivalent to using the `simple` heuristic and each added pattern will generally only improve the experience.
The only issue are incorrect patterns that e.g. often apply `@indent` where it isn't needed. Such patterns should never be added in the first place though, so I'm not sure if we need a mechanism to work around them.

[the remark this answers is not in the document]
Comment (pascalkuthe) [reply book/src/configuration.md]: Ah that's even better than I missed that there was such a fallback on my first read. Now it's clearer that there is documentation for it 👍 

It is possible to create language settings with a global fallback but it does indeed seem like it's not needed here

File: helix-core/src/indent.rs (hunk 1 above)
Comment (Triton171) [reply helix-core/src/indent.rs:967]: Just iterating lines doesn't work here because `treesitter_indent_for_pos` needs a line index. Using `take(MAX_ATTEMPTS)` would work but it would slightly change the logic: Currently, blank lines are not counted towards the number of attempts, since we don't do any indent computation on them. If we did count blank lines, this would cause us to fallback to the `tree-sitter` heuristic much more often.

Comment (pascalkuthe) [reply helix-core/src/indent.rs:967]: Fair enough, it's a bit slower to iterate lines this way (about 5x) but it doesn't matter too much here I supposed.

**Comment by Triton171** [comment]
Thanks for the reminder that this PR still exists :D. I rebased it onto the latest master and added 2 alignment queries for C, mainly since they aid the new hybrid indent heuristic in choosing a suitable baseline. Since I've daily-driven this for the past few months at work (doing C++ development), I'm reasonably confident that the code shouldn't have any major bugs.

Some other languages might also still have missing alignment queries which could cause issues with the new indent heuristic. I think these should be rare, so we can just fix them whenever they are reported (there's not really a way to find them other than using Helix to edit code in the language for a significant amount of time).

**Review by archseer — APPROVED** [review]

**Review by the-mikedavis — APPROVED** [review]

**Review by archseer — APPROVED** [review]
As always, thanks for improving our indentation capabilities! 🎉
