### PR TITLE
Convert clipboard line ending to document line ending when pasting

### LINKED ISSUE #715: Pasting changes document's line-ending from LF to CRLF
### Reproduction steps

1. `cargo new <x>`
2. Paste text:
```rs
enum State {
    /// Within a delimiter.
    Delimiter,
    /// After backslash, but before starting word.
    Backslash,
    /// Within an unquoted word.
    Unquoted,
    /// After backslash in an unquoted word.
    UnquotedBackslash,
    /// Within a single quoted word.
    SingleQuoted,
    /// Within a double quoted word.
    DoubleQuoted,
    /// After backslash inside a double quoted word.
    DoubleQuotedBackslash,
    /// Inside a comment.
    Comment,
}
```
3. Line ending changes to CRLF, but `:line-ending` reports it's still LF.

### Environment

- Platform:  Windows
- Helix version: 6e21a748b87a4eb9381ea0d24117711c5b547ab1

### PR DESCRIPTION
**Pull request by kirawi**
Resolves #715

WIP because it doesn't play nice with the LSP.

### CODE REVIEW

File: helix-core/src/line_ending.rs [hunk 1]
```diff
@@ -151,6 +170,12 @@ pub fn get_line_ending_of_str(line: &str) -> Option<LineEnding> {
     }
 }
 
+pub fn set_line_ending_of_str(doc: &str, line_ending: LineEnding) -> String {
+    doc.lines()
+        .map(|line| format!("{}{}", line, line_ending.as_str()))
+        .collect()
+}
```
Comment (archseer) [inline helix-core/src/line_ending.rs:177]: Extremely inefficient, please use https://doc.rust-lang.org/std/primitive.str.html#method.replace

Comment (archseer) [reply helix-core/src/line_ending.rs:177]: (You can drop this whole method and inline the call to `replace`)

File: helix-term/src/commands.rs [hunk 2]
```diff
@@ -1454,7 +1454,8 @@ mod cmd {
             _ => bail!("invalid line ending"),
         };
 
-        doc_mut!(cx.editor).line_ending = line_ending;
+        let (view, doc) = current!(cx.editor);
+        doc.set_line_ending(view.id, line_ending);
```
Comment (archseer) [inline helix-term/src/commands.rs:1458]: This should be done in a separate "convert" method. `set_line_ending` was supposed to be a way to reinterpret the current document without changing it.

\cc @cessen

**Review by archseer — CHANGES_REQUESTED** [review]

File: helix-term/src/commands.rs (hunk 2 above)
Comment (kirawi) [reply helix-term/src/commands.rs:1458]: Ah, if it writes the line endings that way, then this change is probably unnecessary.

File: helix-core/src/line_ending.rs (hunk 1 above)
Comment (archseer) [reply helix-core/src/line_ending.rs:177]: Ah right, it might use mixed line endings, hmm...

File: helix-term/src/commands.rs (hunk 2 above)
Comment (kirawi) [reply helix-term/src/commands.rs:1458]: Never mind, I thought that it would write to the file with the set line ending, but it doesn't seem to work that way. If it did, then `:reload` would be a good substitute.

**Comment by cessen** [comment]
Yeah, I think what we actually want to do here is have a stand-alone function that (probably?) takes a `&str` and a target line ending, and returns a `String` with all non-specialized line endings replaced with the target line ending.  Then we can just call that from the paste command to do the conversion before actually pasting.

The non-specialized line endings are `CRLF`, `LF`, `CR`, `LS`, and `Nel`, and should be replaced as needed.

(`FF`, `VT`, and `PS` have special uses, and shouldn't be replaced.  Incidentally, I just noticed I screwed that up here: https://github.com/helix-editor/helix/blob/fe17b99ab399d1ee5483ad54c6b124af869afdb6/helix-term/src/commands.rs#L1427-L1435 Ha ha.  So we should probably put what counts as "specialized" or not somewhere centralized, so we only have to get it right once.  Probably just a `const &[]` of the relevant line endings will do, so we can call `contains()`)

**Comment by cessen** [comment]
This prompted me to investigate the purpose of the various line endings further, which led me to this:
https://www.unicode.org/standard/reports/tr13/tr13-5.html

It's actually not *entirely* clear to me yet which line endings should be treated as "specialized" or not.  So let's definitely centralize that, and then we can adjust as needed later.  (I'm suspecting that everything except `CRLF`, `LF`, `CR`, and `Nel` should probably be treated as specialized, but I'm not sure.)

**Comment by kirawi** [comment]
Perhaps we could use `memchr` to check for the line endings? It's already a dependency.

**Comment by archseer** [comment]
```rust
    // only compile the regex once
    #[allow(clippy::trivial_regex)]
    static REGEX: Lazy<Regex> =
        Lazy::new(|| Regex::new(r"\r\n|\r|\n").unwrap());
    REGEX.replace_all(paste_string, new_line_ending)
```

**Comment by archseer** [comment]
I'd completely drop the line ending conversion from this PR and only land the clipboard change. Fixing document-wide line endings is simple to do from the terminal, we can implement a better solution later.

File: helix-term/src/commands.rs [hunk 3]
```diff
@@ -3433,7 +3437,11 @@ fn paste_impl(
         .iter()
         .any(|value| get_line_ending_of_str(value).is_some());
 
-    let mut values = values.iter().cloned().map(Tendril::from).chain(repeat);
+    let mut values = values
+        .iter()
+        .map(|value| PASTE_LINE_ENDING_REGEX.replace_all(value, doc.line_ending.as_str()))
```
Comment (kirawi) [inline helix-term/src/commands.rs:3442]: In the future, this could probably be optimized by running `map_while` when `linewise` is true.

**Comment by cessen** [comment]
> ```
> Lazy::new(|| Regex::new(r"\r\n|\r|\n").unwrap());
> ```

Yeah, for now I think that's good.  We know at those should be replaced, and if/when I get around to more fully investigating the Unicode line ending situation I'll make a PR to include any others that should be covered as well.

File: helix-term/src/commands.rs [hunk 4]
```diff
@@ -3415,6 +3415,10 @@ enum Paste {
     After,
 }
 
+// Only compiled once.
+#[allow(clippy::trivial_regex)]
+static PASTE_LINE_ENDING_REGEX: Lazy<Regex> = Lazy::new(|| Regex::new(r"\r\n|\r|\n").unwrap());
```
Comment (archseer) [inline helix-term/src/commands.rs:3420]: Call it REGEX and move it inside the fn. Rust allows us to nest and scope arbitrarily so that way the static value is only visible within the fn.

Comment (archseer) [reply helix-term/src/commands.rs:3420]: https://github.com/helix-editor/helix/blob/94abc52b3b0929f399cea14e1efcf2c1d0a31ad8/helix-term/src/commands.rs#L1056-L1065

**Review by archseer — CHANGES_REQUESTED** [review]
