### PR TITLE
Fix unwrap bug in DAP

### LINKED ISSUE #6782: Go debug (delve) causing Helix to panic
### Summary

When running the debugger (`<space>g`, set a breakpoint, then start the debugger), helix panics with
```
seth@hydrogen:~/dev/go/helloworld $ RUST_BACKTRACE=1 hx helloworld.go
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: IO(Os { code: 32, kind: BrokenPipe, message: "Broken pipe" })', helix-dap/src/transport.rs:264:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
   5: tokio::runtime::task::core::Core<T,S>::poll
   6: tokio::runtime::task::harness::Harness<T,S>::poll
   7: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
   8: tokio::runtime::scheduler::multi_thread::worker::Context::run
   9: tokio::macros::scoped_tls::ScopedKey<T>::set
  10: tokio::runtime::scheduler::multi_thread::worker::run
  11: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  12: tokio::runtime::task::core::Core<T,S>::poll
  13: tokio::runtime::task::harness::Harness<T,S>::poll
  14: tokio::runtime::blocking::pool::Inner::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Reproduction Steps

 

I tried this:

1. `RUST_BACKTRACE=1 hx helloworld.go`
2. `<space>gb` to set a breakpoint
3. `l` to launch debug target, select binary, enter in full path of the `helloworld` executable

I expected this to happen:
delve to start within helix

Instead, this happened:
panic as described above

### Helix log

Here's an extract of helix.log run with -vv:

<details><summary>~/.cache/helix/helix.log</summary>

```
2023-04-16T17:58:11.194 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-16T17:58:11.194 helix_dap::transport [INFO] -> DAP {"type":"request","seq":1,"command":"launch","arguments":{"cwd":"/home/seth/dev/go/helloworld","mode":"exec","program":"/home/seth/dev/go/helloworld/helloworld"}}
2023-04-16T17:58:11.397 helix_dap::transport [INFO] <- DAP {"seq":0,"type":"event","event":"initialized"}
2023-04-16T17:58:11.397 helix_dap::transport [INFO] <- DAP event Initialized(None)
2023-04-16T17:58:11.397 helix_dap::transport [INFO] <- DAP {"seq":0,"type":"response","request_seq":1,"success":true,"command
":"launch"}
2023-04-16T17:58:11.397 helix_dap::transport [INFO] <- DAP success in response to 1
2023-04-16T17:58:11.397 helix_term::application [DEBUG] received editor event: DebuggerEvent(Event(Initialized(None)))2023-04-16T17:58:11.397 helix_dap::transport [INFO] -> DAP {"type":"request","seq":2,"command":"configurationDone","arguments
":null}
2023-04-16T17:58:11.398 helix_dap::transport [INFO] <- DAP {"seq":0,"type":"event","event":"output","body":{"category":"console","output":"Type 'dlv help' for list of commands.\n","source":{}}}
2023-04-16T17:58:11.398 helix_dap::transport [INFO] <- DAP event Output(Output { output: "Type 'dlv help' for list of commands.\n", category: Some("console"), group: None, line: None, column: None, variables_reference: None, source: Some(Source { name: None, path: None, source_reference: None, presentation_hint: None, origin: None, sources: None, adapter_data: None, checksums: None }), data: None })
2023-04-16T17:58:11.398 helix_dap::transport [INFO] <- DAP {"seq":0,"type":"response","request_seq":2,"success":true,"command":"configurationDone"}
2023-04-16T17:58:11.398 helix_dap::transport [INFO] <- DAP success in response to 2
2023-04-16T17:58:11.398 helix_view::editor [DEBUG] editor status: Debugged application started
2023-04-16T17:58:11.398 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-16T17:58:11.399 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-16T17:58:11.400 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-16T17:58:11.401 helix_dap::transport [INFO] <- DAP {"seq":0,"type":"event","event":"terminated","body":{}}
2023-04-16T17:58:11.401 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-16T17:58:11.401 helix_dap::transport [INFO] <- DAP event Terminated(Some(Terminated { restart: None }))
2023-04-16T17:58:11.402 helix_term::application [DEBUG] received editor event: DebuggerEvent(Event(Output(Output { output: "T
ype 'dlv help' for list of commands.\n", category: Some("console"), group: None, line: None, column: None, variables_reference: None, source: Some(Source { name: None, path: None, source_reference: None, presentation_hint: None, origin: None, sources: None, adapter_data: None, checksums: None }), data: None })))
2023-04-16T17:58:11.402 helix_view::handlers::dap [INFO] Type 'dlv help' for list of commands.

2023-04-16T17:58:11.402 helix_view::editor [DEBUG] editor status: Debug (console): Type 'dlv help' for list of commands.

2023-04-16T17:58:11.402 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-16T17:58:11.403 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2023-04-16T17:58:11.403 helix_term::application [DEBUG] received editor event: DebuggerEvent(Event(Terminated(Some(Terminated { restart: None }))))
```

</details>

### Platform

linux (void) 6.1.21_1 #1 SMP PREEMPT_DYNAMIC Fri Mar 24 00:43:29 UTC 2023 x86_64 GNU/Linux

### Terminal Emulator

blink.sh / mosh / tmux

### Helix Version

22.12-577-g4cdba7cc

### PR DESCRIPTION
**Pull request by A-Walrus**
Fixes #6782

### CODE REVIEW

File: helix-dap/src/client.rs [hunk 1]
```diff
@@ -62,12 +62,10 @@ impl Client {
...
-        if transport == "tcp" && port_arg.is_some() {
-            Self::tcp_process(command, args, port_arg.unwrap(), id).await
-        } else if transport == "stdio" {
-            Self::stdio(command, args, id)
-        } else {
-            Result::Err(Error::Other(anyhow!("Incorrect transport {}", transport)))
+        match (transport, port_arg) {
+            ("tcp", Some(port_arg)) => Self::tcp_process(command, args, port_arg, id).await,
+            ("stdio", _) => Self::stdio(command, args, id),
+            _ => Result::Err(Error::Other(anyhow!("Incorrect transport {}", transport))),
```
Comment (A-Walrus) [inline helix-dap/src/client.rs:68]: This isn't directly related, but I just wanted to get rid of an unnecessary unwrap. If you want I can separate this to a different PR.

File: helix-view/src/handlers/dap.rs [hunk 2]
```diff
@@ -321,6 +321,7 @@ impl Editor {
                             }
                         }
                         None => {
+                            self.debugger = None;
```
Comment (pascalkuthe) [inline helix-view/src/handlers/dap.rs:324]: This seems like a seperate bug fix to me. I think this is correct and needed to ensure that the debugger is actually removed once it terminates, right? This seems like the right fix to me and I ran into this bug before so it's great to see this fixed too

**Review by pascalkuthe — APPROVED** [review]
good catch, thanks! The CI seems to have failed for unrelated reasons lets hope it passes on a second try

File: helix-view/src/handlers/dap.rs (hunk 2 above)
Comment (A-Walrus) [reply helix-view/src/handlers/dap.rs:324]: Yeah it's separate, but related. Without this trying to add a breakpoint after the debugger terminated would show an error, better than crashing but still not great.

Comment (pascalkuthe) [reply helix-view/src/handlers/dap.rs:324]: yeah this is what I ran into too in the past, good catch :)

**Review by the-mikedavis — APPROVED** [review]

**Comment by sbromberger** [comment]
Thanks for the quick fix! I'll give it a try today.
