### PR TITLE
diff full-doc LSP edits

### LINKED ISSUE #3859: Write (:w) in HTML files selects the whole file and loses position when HTML LSP is active
### Summary

Issuing a `:w` command in an HTML file selects the whole file and loses your current position when HTML LSP is active.

### Reproduction Steps

 

I tried this:

1. `npm i -g vscode-langservers-extracted` to install HTML LSP
1. Create HTML file
2. `:w`

## I expected this to happen:

File is saved. Nothing is selected. My position is saved.

## Instead, this happened:

File is saved. Everything is selected. My position is lost (reverts to top).

Note that this behaviour does _not_ occur if the LSP is not installed/active.

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
2022-09-16T11:57:07.545 helix_term::application [ERROR] Language Server: Method not found client/r
```

</details>

### Platform

Linux (Fedora Silverblue 36)

### Terminal Emulator

Black Box 

### Helix Version

helix 22.08.1 (714db9c6)

### PR DESCRIPTION
**Pull request by kirawi**
Resolves #3859 by generating a diff if the LSP replaces the entire document.

### CODE REVIEW

File: helix-lsp/src/lib.rs [hunk 1]
```diff
@@ -204,6 +204,19 @@ pub mod util {
         // in reverse order.
         edits.sort_unstable_by_key(|edit| edit.range.start);
 
+        if edits.len() == 1 {
```
Comment (kirawi) [inline helix-lsp/src/lib.rs:207]: Is it possible for a text edit that replaces the document to have subsequent text edits? If not, then deleting this check should be alright.

File: helix-lsp/src/lib.rs [hunk 2]
```diff
@@ -204,6 +204,17 @@ pub mod util {
         // in reverse order.
         edits.sort_unstable_by_key(|edit| edit.range.start);
 
+        // If the edit is a full document replacement, then we generate a diff.
+        let is_document_replacement = matches!(edits.first().and_then(|edit| {
+            let start = lsp_pos_to_pos(doc, edit.range.start, offset_encoding)?;
+            let end = lsp_pos_to_pos(doc, edit.range.end, offset_encoding)?;
+            Some(start..end)
+        }), Some(range) if range == (0..doc.len_chars()));
```
Comment (archseer) [inline helix-lsp/src/lib.rs:212]: It seems wasteful to precompute this if edits.len() isn't 1, so I'd put this in a nested if

Comment (kirawi) [reply helix-lsp/src/lib.rs]: Fixed.

File: helix-lsp/src/lib.rs [hunk 3]
```diff
@@ -204,6 +204,20 @@ pub mod util {
...
         edits.sort_unstable_by_key(|edit| edit.range.start);
 
+        // Generate a diff if the edit is a full document replacement.
+        #[allow(clippy::collapsible_if)]
+        if edits.len() == 1 {
+            let is_document_replacement = matches!(edits.first().and_then(|edit| {
+                let start = lsp_pos_to_pos(doc, edit.range.start, offset_encoding)?;
+                let end = lsp_pos_to_pos(doc, edit.range.end, offset_encoding)?;
+                Some(start..end)
+            }), Some(range) if range == (0..doc.len_chars()));
```
Comment (the-mikedavis) [inline helix-lsp/src/lib.rs:214]: I think this is a bit cleaner if it's just an equality check:

```suggestion
            let is_document_replacement = edits.first().and_then(|edit| {
                let start = lsp_pos_to_pos(doc, edit.range.start, offset_encoding)?;
                let end = lsp_pos_to_pos(doc, edit.range.end, offset_encoding)?;
                Some(start..end)
            }) == Some(0..doc.len_chars());
```

File: helix-lsp/src/lib.rs (hunk 1 above)
Comment (dead10ck) [reply helix-lsp/src/lib.rs:209]: Logically I don't think it would make a difference anyway; either the first edit is the whole document or it's not.

File: helix-lsp/src/lib.rs [hunk 4]
```diff
@@ -204,6 +204,20 @@ pub mod util {
         // in reverse order.
         edits.sort_unstable_by_key(|edit| edit.range.start);
 
+        // Generate a diff if the edit is a full document replacement.
+        #[allow(clippy::collapsible_if)]
+        if edits.len() == 1 {
+            let is_document_replacement = edits.first().and_then(|edit| {
```
Comment (dead10ck) [inline helix-lsp/src/lib.rs:210]: As clippy is telling us here, you don't need this intermediate variable.

**Review by dead10ck — COMMENTED** [review]
Couple minor things, but this looks good! Thanks.

File: helix-lsp/src/lib.rs (hunk 4 above)
Comment (kirawi) [reply helix-lsp/src/lib.rs:210]: The clippy warning is for turning it into one `if` statement. Clippy actually tells you to use an intermediate statement.

Comment (the-mikedavis) [reply helix-lsp/src/lib.rs:210]: Looks like two clippy rules are fighting each other, [`collapsible_if`](https://rust-lang.github.io/rust-clippy/rust-1.64.0/index.html#collapsible_if) and [`block_in_if_conditions`](https://rust-lang.github.io/rust-clippy/rust-1.64.0/index.html#blocks_in_if_conditions). I think this is the lesser of the two evils here readability-wise 👍

**Comment by the-mikedavis** [comment]
Gave this a test for https://github.com/helix-editor/helix/issues/3859 against master and this works great!

**Review by the-mikedavis — APPROVED** [review]
