### PR TITLE
fix!+feat: improve hex-color parsing

### LINKED ISSUE #14852: theme hex-color parsing accepts `+`
### Summary

Quoted from [the docs](https://doc.rust-lang.org/1.82.0/std/primitive.u8.html#method.from_str_radix):
> The string is expected to be an optional + sign followed by digits

Therefore, if a theme-file has a "color" like `#+1+2+3` it'll be interpreted as `#010203`. Here's the relevant code:
https://github.com/helix-editor/helix/blob/095227ef2f0308b097f981facc745fae77949c81/helix-view/src/theme.rs#L577-L589

I'm willing to open a PR, but there's at least 2 ways to solve this, so I'm not sure which would be preferred

See also: rust-lang/rust-clippy#16213

### Reproduction Steps

I tried this:

1. `hx path-to-foobar-theme`
2. Replace any hexadecimal nibble-pair RGB value such that the 1st nibble is `+`
3. `:w`
4. `:theme foobar`

I expected this to happen: Error in log and fallback to default terminal color-palette

Instead, this happened: No error. One theme color is slightly or radically different, likely darker than the original

### Helix log

<details><summary>~/.cache/helix/helix.log</summary>

```
```

</details>

### Platform

irrelevant

### Terminal Emulator

irrelevant

### Installation Method

source

### Helix Version

25.07-310-g0952

### PR DESCRIPTION
**Pull request by Rudxain**
- fixes #14852 (reasonable breaking-change)
- reject bogus hex-color lengths (questionable breaking-change)
- adds support for hex-color short-hand notation (`#abc` = `#aabbcc`)
- adds many tests
- fixes "revealed" malformed hexcodes in themes, to make CI happy :)
  - `ashokai_urple` (introduced in #14446)
  - many others, because of the unused alpha channel

### CODE REVIEW

**Comment by Rudxain** [comment]
@the-mikedavis I'm sorry for the ping, but IDK who should review this :confused:

File: helix-stdx/src/hex.rs
Comment (the-mikedavis) [inline helix-stdx/src/hex.rs:1]: This can live in graphics.rs, it doesn't need its own module in stdx

File: helix-view/src/theme.rs [hunk 1]
```diff
@@ -561,7 +561,18 @@ impl ThemePalette {
...
         if s.starts_with('#') {
-            Self::hex_string_to_rgb(s)
+            match Color::from_hex(match s.len() {
+                // RGB
+                4 | 7 => s,
+                // RGBA (ignoring alpha)
+                5 => &s[0..4],
+                9 => &s[0..7],
+                // HACK: return None
+                _ => "",
```
Comment (the-mikedavis) [inline helix-view/src/theme.rs]: Let's explicitly reject alpha if provided, and bail instead of using `""` with an error message that points out the unexpected length

File: helix-view/src/graphics.rs [hunk 2]
```diff
@@ -5,6 +5,47 @@ use std::{
...
+    }
+}
+
+/// Decodes a nibble into an octet, repeating its value on each half.
+/// That is, the value is its own padding.
+///
+/// # Errors
+/// If the byte `h` is not an ASCII nibble
+#[must_use]
+pub const fn dupe_from_nibble(mut h: u8) -> Option<u8> {
```
Comment (the-mikedavis) [inline helix-view/src/graphics.rs]:
```suggestion
const fn dupe_from_nibble(mut h: u8) -> Option<u8> {
```

File: helix-view/src/graphics.rs [hunk 3]
```diff
@@ -275,14 +316,25 @@ impl Color {
...
+    pub fn from_hex(h: &str) -> Option<Self> {
+        let h = h.as_bytes();
+        if !h.starts_with(b"#") {
             return None;
         }
-        match [1..=2, 3..=4, 5..=6].map(|i| hex.get(i).and_then(|c| u8::from_str_radix(c, 16).ok()))
-        {
-            [Some(r), Some(g), Some(b)] => Some(Self::Rgb(r, g, b)),
+
+        let (pair, nibble) = (byte_from_hex, dupe_from_nibble);
```
Comment (the-mikedavis) [inline helix-view/src/graphics.rs]: A `use` seems more idiomatic here even if it takes two lines instead of one

File: helix-view/src/graphics.rs (hunk 2 above)
Comment (Rudxain) [reply helix-view/src/graphics.rs]: I forgot about that while moving code :sweat_smile:. Thanks for the reminder!

File: helix-view/src/graphics.rs (hunk 3 above)
Comment (Rudxain) [reply helix-view/src/graphics.rs]: I didn't know that was possible (aliasing something already in scope) :eyes:.

Also, in case the hex stuff gets extracted back into a module, the presence of `use` should be easier to edit, so I agree

**Review by the-mikedavis — APPROVED** [review]

**Comment by Rudxain** [comment]
I now remember that `book/src/themes.md` should've been updated to mention shorthand notation

**Comment by Rudxain** [comment]
I've opened #15326
