### PR TITLE
keymap: Test backslash escaping in commands

### LINKED ISSUE #5144: `expected a borrowed string for key` with backslash in key binding
Breaking version: `helix 22.12 (0f2ae35a)`
This worked fine in `22.08`

Config:
```toml
[keys.normal]
"3" = [
  ":pipe sed -E 's/\\s+$//g'"
]
```

Command:
`./target/debug/hx --config /tmp/config.toml -vvv --log /tmp/helix.log`

Error:
```
Bad config: invalid type: string ":pipe sed -E 's/\\s+$//g'", expected a borrowed string for key `keys.normal.3` at line 3 column 3
```

This seems to be caused by the double backslash in the command. Replacing it with `:pipe sed -E 's/ +$//g'` fixes the issue for now.

Log:

<details>
<summary>Nothing interesting</summary>

```
2022-12-13T10:27:43.585 helix_loader [DEBUG] Located configuration folders: ["/Users/me/vendor/helix/.helix"]
2022-12-13T10:27:43.642 helix_view::clipboard [DEBUG] Using pbcopy+pbpaste to interact with the system clipboard
2022-12-13T10:27:43.642 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE | WRITABLE
2022-12-13T10:27:43.642 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE | WRITABLE
2022-12-13T10:27:43.642 mio::poll [TRACE] registering event source with poller: token=Token(0), interests=READABLE
2022-12-13T10:27:43.642 mio::poll [TRACE] registering event source with poller: token=Token(1), interests=READABLE
2022-12-13T10:27:43.643 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-13T10:27:44.038 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-13T10:27:44.145 helix_term::commands::typed [DEBUG] quitting...
2022-12-13T10:27:44.145 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-13T10:27:44.235 helix_term::commands::typed [DEBUG] quitting...
2022-12-13T10:27:44.235 helix_view::document [DEBUG] id 1 modified - last saved: 0, current: 0
2022-12-13T10:27:44.235 helix_term::job [DEBUG] waiting on jobs...
2022-12-13T10:27:44.235 helix_term::job [DEBUG] waiting on jobs...
2022-12-13T10:27:44.237 mio::poll [TRACE] deregistering event source from poller
2022-12-13T10:27:44.237 mio::poll [TRACE] deregistering event source from poller
```
</details>

System:

```
rustc 1.65.0 (897e37553 2022-11-02)
cargo 1.65.0 (4bc8f24d3 2022-10-20)
Darwin 22.1.0, arm64 (macOS 13.0.1 on M1 chip)
```

### PR DESCRIPTION
**Pull request by ds-cbo**
Fixes #5144

### CODE REVIEW

File: helix-term/src/commands.rs [hunk 1]
```diff
@@ -506,12 +515,16 @@ impl PartialEq for MappableCommand {
...
+                    ..
                 },
                 MappableCommand::Typable {
-                    name: second_name, ..
+                    name: second_name,
+                    args: second_args,
+                    ..
                 },
-            ) => first_name == second_name,
+            ) => first_name == second_name && first_args == second_args,
```
Comment (ds-cbo) [inline helix-term/src/commands.rs:527]: This was necessary to make the test check whether the argument was parsed correctly. I did not consider whether this would change any other behaviour

File: helix-term/src/keymap.rs [hunk 2]
```diff
@@ -184,7 +184,7 @@ impl<'de> serde::de::Visitor<'de> for KeyTrieVisitor {
         S: serde::de::SeqAccess<'de>,
     {
         let mut commands = Vec::new();
-        while let Some(command) = seq.next_element::<&str>()? {
+        while let Some(command) = seq.next_element::<Cow<str>>()? {
```
Comment (ds-cbo) [inline helix-term/src/keymap.rs:187]: This single line is the gist of the fix. If the rest of the commit is unacceptable, feel free to remove everything but this line

File: helix-term/src/keymap.rs [hunk 3]
```diff
@@ -600,4 +600,43 @@ mod tests {
...
+        };
+
+        let expectation = Keymap::new(KeyTrie::Node(KeyTrieNode::new(
+            "",
+            hashmap! {
+                key => KeyTrie::Sequence(vec!{
+                    MappableCommand::select_all,
+                    MappableCommand::Typable {
+                        name: "pipe".to_owned(),
+                        args: vec!{
```
Comment (ds-cbo) [inline helix-term/src/keymap.rs:628]: I don't like the number of `.to_owned()` here, but I also don't know of a good way to reduce them

**Comment by pascalkuthe** [comment]
This PR is now redundant now after https://github.com/helix-editor/helix/commit/e83ce7224063afc52d44f9c2b68e3c5a03412f5c

**Comment by gibbz00** [comment]
Close it?

**Comment by the-mikedavis** [comment]
I would still like to get in the Debug change and the new test case. I'll rebase this on top of e83ce72

File: helix-term/src/keymap.rs (hunk 3 above)
Comment (the-mikedavis) [reply helix-term/src/keymap.rs:628]: These are fine since you need a String. I changed it to `.to_string()` to match the test cases above though

File: helix-term/src/commands.rs (hunk 1 above)
Comment (the-mikedavis) [reply helix-term/src/commands.rs:524]: I don't think this should have any runtime impact. AFAIK PartialEq is only used on this enum for test cases and for the keymap test cases
