### PR TITLE
use PathBuf::to_string_lossy() instead of to_str()

### LINKED ISSUE #1646: Helix crashes when invoking file picker
### Reproduction steps
Helix crashes for me on a fresh installation without configuration when invoking the file picker (with `space+f`):
```thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', helix-term/src/ui/mod.rs:161:18```

It also crashes immediately when running `hx .` from the home directory, but not when running `hx [folder]` from the home directory. Confusingly, `hx .` in `~/folder` leads to a crash again.

### Environment

- Platform: Linux
- Terminal emulator:  Kitty (but also on others)
- Helix version: helix 0.6.0 (1bcb624a)

### PR DESCRIPTION
**Pull request by kirawi**
Fixes #1646 #1569

Also preemptively changes other uses of `as_str()` because they look like places where a similar panic would happen.

### CODE REVIEW

File: helix-term/src/ui/mod.rs [hunk 1]
```diff
@@ -155,11 +155,7 @@ pub fn file_picker(root: PathBuf, config: &helix_view::editor::Config) -> FilePi
         files,
         move |path: &PathBuf| {
             // format_fn
-            path.strip_prefix(&root)
-                .unwrap_or(path)
-                .to_str()
-                .unwrap()
-                .into()
```
Comment (archseer) [inline helix-term/src/ui/mod.rs:162]: This can be hundreds of allocations on a large list. You should try to use to_str() then fallback.

File: helix-term/src/ui/mod.rs [hunk 2]
```diff
@@ -286,9 +282,7 @@ pub mod completers {
         let (dir, file_name) = if input.ends_with(std::path::MAIN_SEPARATOR) {
             (path, None)
         } else {
-            let file_name = path
-                .file_name()
-                .map(|file| file.to_str().unwrap().to_owned());
+            let file_name = path.file_name().map(|file| file.to_string_lossy());
```
Comment (archseer) [inline helix-term/src/ui/mod.rs:285]: I don't think it makes sense to include lossy results under completion since this won't result in a valid filepath anyway (and when you try to open the file you'll instead be making a new one). We should filter out these results instead

**Review by archseer — CHANGES_REQUESTED** [review]

File: helix-term/src/ui/mod.rs (hunk 1 above)
Comment (kirawi) [reply helix-term/src/ui/mod.rs:162]: Would it allocate? `to_string_lossy` returns a `Cow<str>`

Comment (archseer) [reply helix-term/src/ui/mod.rs:162]: Ah okay, then that's fine.

File: helix-term/src/ui/mod.rs [hunk 3]
```diff
@@ -331,7 +327,7 @@ pub mod completers {
                         path.push("");
                     }
 
-                    let path = path.to_str().unwrap().to_owned();
+                    let path = path.to_string_lossy().into_owned();
```
Comment (archseer) [inline helix-term/src/ui/mod.rs:330]: This is still part of the completion and it should return None here instead of an invalid lossy result

File: helix-term/src/commands.rs [hunk 4]
```diff
@@ -4119,8 +4117,8 @@ fn goto_impl(
                                         .map(|path| path.to_path_buf())
                                         .unwrap_or(path)
                                 })
+                                .map(|path| Cow::from(path.to_string_lossy().into_owned()))
                                 .ok()
-                                .and_then(|path| path.to_str().map(|path| path.to_owned().into()))
```
Comment (kirawi) [inline helix-term/src/commands.rs:4123]: Should I leave this as it was?

**Review by pickfire — APPROVED** [review]
Looks good to me.
