### PR TITLE
Don't panic on LSP not starting/misbehaving 

### LINKED ISSUE #33: Issues with `pyls`
Seems like Helix panics when it tries to open Python files specifically, I tried both large and small files, it panicked on both, both when the file is given using the CLI and both when selected through the `:open <file.py>` option.
I was able to open `TOML, Rust, C, C++, txt, XML, CSV, JSON` perfectly well.

```
❯ hx ~/path/to/file.py
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', helix-lsp/src/transport.rs:103:60
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', helix-lsp/src/client.rs:156:18
```

Reproducible in both `helix-git` and `helix-bin` AUR packages.
(Seems like it also panics when I try to extract the version on the `helix-git` package)
```
❯ hx --version
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory (os error 2)', helix-term/src/main.rs:117:46
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Active Rust versions:
```
nightly-x86_64-unknown-linux-gnu (default)
rustc 1.54.0-nightly (657bc0188 2021-05-31)
```

### PR DESCRIPTION
**Pull request by batonius**
Fixes #33 and probably #103.

### CODE REVIEW

File: helix-view/src/editor.rs [hunk 1]
```diff
@@ -155,7 +155,7 @@ impl Editor {
             let language_server = doc
                 .language
                 .as_ref()
-                .and_then(|language| self.language_servers.get(language));
+                .and_then(|language| self.language_servers.get(language).ok());
```
Comment (archseer) [inline helix-view/src/editor.rs:158]: This is better than the old behavior (crashing), but we need to find a way to log LSP errors to the UI (`set_error` isn't available here)

**Comment by archseer** [comment]
Great work!
